// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 13/12/2016 by Alexey Morozov

namespace Aspose.Words
{
    /// <summary>
    /// Implements saved attribute collection.
    /// </summary>
    /// <remarks>
    /// AM. The only reason for this class is to make equals to saved attributes.
    /// Hope we will remove TableFormattingExpaned class soon and this class will be removed as well.
    /// </remarks>
    internal class AttrCollectionBackup
    {
        internal AttrCollectionBackup(WordAttrCollection pr)
        {
            mPr = pr;
        }

        /// <summary>
        /// Determines whether the specified object is equal in value to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != typeof(AttrCollectionBackup))
                return false;
            return Equals((AttrCollectionBackup)obj);
        }

        internal bool Equals(AttrCollectionBackup rhs)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, rhs))
                return false;
            if (ReferenceEquals(this, rhs))
                return true;

            return mPr.Equals(rhs.Pr, null);
        }

        public override int GetHashCode()
        {
            return (mPr != null)
                ? mPr.GetHashCode()
                : 0;
        }

        internal WordAttrCollection Pr
        {
            get { return mPr; }
        }

        private readonly WordAttrCollection mPr;
    }
}
