// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 01/15/2012 by Denis Darkin

namespace Aspose.Words
{
    /// <summary>
    /// specifies the characters which can be used to fill in the space created by a positional tab. 
    /// This character shall be repeated as required to completely fill the tab spacing generated by the positional tab character.
    /// </summary>
    internal enum AbsolutePositionTabLeaderChar
    {
        /// <summary>
        /// Specifies that the leader character for this positional tab stop shall be a dot.
        /// </summary>
        Dot,

        /// <summary>
        /// Specifies that the leader character for this positional tab stop shall be a hyphen.
        /// </summary>
        Hyphen,
        
        /// <summary>
        /// Specifies that the leader character for this positional tab stop shall be a centered dot.
        /// </summary>
        MiddleDot,

        /// <summary>
        /// Specifies that there shall be no leader character for this positional tab.
        /// </summary>
        None,

        /// <summary>
        /// Specifies that the leader character for this positional tab stop shall be an underscore.
        /// </summary>
        Underscore,

        /// <summary>
        /// Defaults to <see cref="None"/>. 
        /// </summary>
        /// <remarks>This default is AW specific, it is not defined in OOXML specification.</remarks>
        Default = None
    }
}
