// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 12/05/2005 by Roman Korchagin

using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Aspose.Collections.Generic;

namespace Aspose.Words
{
    /// <summary>
    /// A collection of <see cref="TabStop"/> objects that represent custom tabs for a paragraph or a style.
    /// <para>To learn more, visit the <a href="https://docs.aspose.com/words/net/aspose-words-document-object-model/">Aspose.Words Document Object Model (DOM)</a> documentation article.</para>
    /// </summary>
    /// <remarks>
    /// <p>In Microsoft Word documents, a tab stop can be defined in the properties of a paragraph
    /// style or directly in the properties of a paragraph. A style can be based on another style.
    /// Therefore, the complete set of tab stops for a given object is a combination of tab stops
    /// defined directly on this object and tab stops inherited from the parent styles.</p>
    ///
    /// <p>In Aspose.Words, when you obtain a <see cref="TabStopCollection"/> for a paragraph or a style,
    /// it contains only the custom tab stops defined directly for this paragraph or style.
    /// The collection does not include tab stops defined in the parent styles or default tab stops.</p>
    ///
    /// <seealso cref="ParagraphFormat"/>
    /// <seealso cref="TabStop"/>
    /// <seealso cref="Aspose.Words.Document.DefaultTabStop"/>
    /// </remarks>
    /// <dev>
    /// This whole collection is stored in the paragraph attributes as a single attribute.
    /// </dev>

    // TODO This class is marked as Serializable, but it contains some unserializable fields, what raises an exception during serialization.
    // var obj = new TabStopCollection();
    // MemoryStream ms = new MemoryStream();
    // BinaryFormatter bf = new BinaryFormatter();
    // bf.Serialize(ms, obj);
    // Should we remove this attribute or fix the serialization?
    [Serializable]
    public class TabStopCollection : InternableComplexAttr, IExpandableAttr
    {
        internal TabStopCollection()
        {
        }

        /// <summary>
        /// Clones this instance of text spacing.
        /// </summary>
        internal TabStopCollection Clone()
        {
            TabStopCollection lhs = (TabStopCollection)MemberwiseClone();

            lhs.mItems = new SortedIntegerListGeneric<TabStop>();
            for (int i = 0; i < Count; i++)
                lhs.mItems.Add(mItems.GetKey(i), mItems.GetByIndex(i).Clone());

            return lhs;
        }

        /// <summary>
        /// Determines whether the specified <see cref="TabStopCollection"/> is equal in value to the current <see cref="TabStopCollection"/>.
        /// </summary>
        public bool Equals(TabStopCollection rhs)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, rhs))
                return false;
            if (ReferenceEquals(this, rhs))
                return true;

            if (mHasTolerances != rhs.mHasTolerances)
                return false;

            if (this.Count != rhs.Count)
                return false;

            for (int i = 0; i < this.Count; i++)
            {
                if (!this[i].Equals(rhs[i]))
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Determines whether the specified object is equal in value to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != typeof(TabStopCollection))
                return false;
            return Equals((TabStopCollection)obj);
        }

        /// <summary>
        /// Serves as a hash function for this type.
        /// </summary>
        /// <javaName>int hashCode()</javaName>
        public override int GetHashCode()
        {
            return (mItems.GetHashCode() * 397) ^ mHasTolerances.GetHashCode();
        }

        /// <summary>
        /// Gets the number of tab stops in the collection.
        /// </summary>
        public int Count
        {
            get { return mItems.Count; }
        }

        /// <summary>
        /// Returns true if "has tolerances" was explicitly set to true or if one of the
        /// tab stops has a non zero tolerance.
        ///
        /// MS Word sometimes writes sprm with tolerances although there are no tolerances,
        /// I want to be able to write the sprm in exactly the same way, that's why I need
        /// to be able to set "has tolerances" explicitly.
        /// </summary>
        internal bool HasTolerances
        {
            get
            {
                if (mHasTolerances)
                    return true;

                for (int i = 0; i < Count; i++)
                {
                    if (this[i].ToleranceTwips != 0)
                        return true;
                }
                return false;
            }
            set
            {
                mHasTolerances = value;
            }
        }

        /// <overloads>Retrieves a tab stop from the collection.</overloads>
        /// <summary>
        /// Gets a tab stop at the given index.
        /// </summary>
        /// <param name="index">An index into the collection of tab stops.</param>
        public TabStop this[int index]
        {
            get { return mItems.GetByIndex(index); }
        }

        /// <summary>
        /// Gets a tab stop at the specified position.
        /// </summary>
        /// <remarks>
        /// Returns <c>null</c> if no tab stop is found at the specified position.
        /// </remarks>
        /// <param name="position">The position (in points) of the tab stop.</param>
        [SuppressMessage("Microsoft.Design", "CA1043:UseIntegralOrStringArgumentForIndexers",
            Justification = "Public API, as designed.")]
        public TabStop this[double position]
        {
            get { return GetByPositionTwips(ConvertUtilCore.PointToTwip(position)); }
        }

        /// <summary>
        /// Retrieves a tab stop at the specified position in twips.
        /// </summary>
        internal TabStop GetByPositionTwips(int positionTwips)
        {
            return mItems[positionTwips];
        }

        /// <summary>
        /// Deletes all tab stop positions.
        /// </summary>
        public void Clear()
        {
            NotifyChanging();
            mItems.Clear();
        }

        /// <summary>
        /// Gets the position (in points) of the tab stop at the specified index.
        /// </summary>
        /// <param name="index">An index into the collection of tab stops.</param>
        /// <returns>The position of the tab stop.</returns>
        public double GetPositionByIndex(int index)
        {
            return ConvertUtilCore.TwipToPoint(GetPositionTwipsByIndex(index));
        }

        /// <summary>
        /// Gets a position in twips of a tab stop at the specified index.
        /// </summary>
        internal int GetPositionTwipsByIndex(int index)
        {
            return mItems.GetKey(index);
        }

        /// <summary>
        /// Gets the index of a tab stop with the specified position in points.
        /// </summary>
        public int GetIndexByPosition(double position)
        {
            return GetIndexByPositionTwips(ConvertUtilCore.PointToTwip(position));
        }

        /// <summary>
        /// Gets index of a tab stop with the specified position in twips.
        /// </summary>
        internal int GetIndexByPositionTwips(int positionTwips)
        {
            return mItems.IndexOfKey(positionTwips);
        }

        /// <summary>
        /// Adds or replaces a tab stop in the collection.
        /// </summary>
        /// <remarks>
        /// <p>If a tab stop already exists at the specified position, it is replaced.</p>
        /// </remarks>
        /// <param name="tabStop">A tab stop object to add.</param>
        public void Add(TabStop tabStop)
        {
            NotifyChanging();
            if (tabStop == null)
                throw new ArgumentNullException("tabStop");
            mItems[tabStop.PositionTwips] = tabStop;
        }

        /// <summary>
        /// Adds or replaces a tab stop in the collection.
        /// </summary>
        /// <remarks>
        /// <p>If a tab stop already exists at the specified position, it is replaced.</p>
        /// </remarks>
        /// <param name="position">A position (in points) where to add the tab stop.</param>
        /// <param name="alignment">A <see cref="TabAlignment"/> value that
        /// specifies the alignment of text at the tab stop.</param>
        /// <param name="leader">A <see cref="TabLeader"/> value that
        /// specifies the type of the leader line displayed under the tab character.</param>
        public void Add(double position, TabAlignment alignment, TabLeader leader)
        {
            Add(new TabStop(position, alignment, leader));
        }

        /// <summary>
        /// Removes a tab stop at the specified position from the collection.
        /// </summary>
        /// <param name="position">The position (in points) of the tab stop to remove.</param>
        public void RemoveByPosition(double position)
        {
            RemoveByPositionTwips(ConvertUtilCore.PointToTwip(position));
        }

        internal void RemoveByPositionTwips(int positionTwips)
        {
            NotifyChanging();
            mItems.Remove(positionTwips);
        }

        /// <summary>
        /// Removes a tab stop at the specified index from the collection.
        /// </summary>
        /// <param name="index">An index into the collection of tab stops.</param>
        public void RemoveByIndex(int index)
        {
            NotifyChanging();
            mItems.RemoveAt(index);
        }

        /// <summary>
        /// Gets a first tab stop to the right of the specified position.
        /// </summary>
        /// <remarks>
        /// <p>Skips tab stops with <see cref="TabStop.Alignment"/> set to <see cref="TabAlignment.Bar"/>.</p>
        /// </remarks>
        /// <param name="position">The reference position (in points).</param>
        /// <returns>A tab stop object or <c>null</c> if a suitable tab stop was not found.</returns>
        public TabStop After(double position)
        {
            int positionTwips = ConvertUtilCore.PointToTwip(position);
            for (int i = 0; i < Count; i++)
            {
                if (GetPositionTwipsByIndex(i) > positionTwips)
                {
                    TabStop tabStop = this[i];
                    if (tabStop.Alignment != TabAlignment.Bar)
                        return tabStop;
                }
            }
            return null;
        }

        /// <summary>
        /// Gets a first tab stop to the left of the specified position.
        /// </summary>
        /// <remarks>
        /// <p>Skips tab stops with <see cref="TabStop.Alignment"/> set to <see cref="TabAlignment.Bar"/>.</p>
        /// </remarks>
        /// <param name="position">The reference position (in points).</param>
        /// <returns>A tab stop object or <c>null</c> if a suitable tab stop was not found.</returns>
        public TabStop Before(double position)
        {
            int positionTwips = ConvertUtilCore.PointToTwip(position);
            for (int i = Count - 1; i >= 0; i--)
            {
                if (GetPositionTwipsByIndex(i) < positionTwips)
                {
                    TabStop tabStop = this[i];
                    if (tabStop.Alignment != TabAlignment.Bar)
                        return tabStop;
                }
            }
            return null;
        }

        internal void RemoveClearTabStops()
        {
            NotifyChanging();
            for (int i = Count - 1; i >= 0; i--)
            {
                if (this[i].IsClear)
                    RemoveByIndex(i);
            }
        }

        /// <summary>
        /// Gets the array of positions of the bar tabs. In points.
        /// </summary>
        internal float[] GetBarTabPositions()
        {
            int barTabCount = 0;
            for (int i = 0; i < Count; i++)
            {
                if (this[i].Alignment == TabAlignment.Bar)
                    barTabCount++;
            }

            float[] barTabPositions = new float[barTabCount];
            int barTabIdx = 0;

            for (int tabIdx = 0; tabIdx < Count; tabIdx++)
            {
                if (this[tabIdx].Alignment == TabAlignment.Bar)
                {
                    barTabPositions[barTabIdx] = (float)this[tabIdx].Position;
                    barTabIdx++;
                }
            }

            return barTabPositions;
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        bool IComplexAttr.IsInheritedComplexAttr
        {
            // This attribute is never inherited in our model.
            // It basically means if tab stops are defined on a style and you request tab stops on a paragraph,
            // you will get an empty collection of tab stops.
            // On one hand, it could be improved by making the attribute inheritable, but on the other
            // hand it will complicate the inner workings too much that I don't want to do it.
            get { return false; }
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        IComplexAttr IComplexAttr.DeepCloneComplexAttr()
        {
            TabStopCollection lhs = (TabStopCollection)MemberwiseClone();
            lhs.mItems = new SortedIntegerListGeneric<TabStop>();
            for (int i = 0; i < Count; i++)
                lhs.mItems.Add(GetPositionTwipsByIndex(i), this[i].Clone());

            return lhs;
        }

        /// <summary>
        /// IExpandableAttr
        /// </summary>
        IExpandableAttr IExpandableAttr.Expand(IExpandableAttr parentAttr)
        {
            TabStopCollection dstTabStops;

            if (parentAttr != null)
                dstTabStops = (TabStopCollection)parentAttr.DeepCloneComplexAttr();
            else
                dstTabStops = new TabStopCollection();

            int dstLegacyTabStopIdx = dstTabStops.GetLegacyTabStopIndex();

            // Merge our tab stops into the parent tabstops.
            for (int i = 0; i < Count; i++)
            {
                TabStop srcTabStop = this[i];

                // WORDSNET-23264 Override existing legacy TabStop instead of just adding a new one.
                if (srcTabStop.IsLegacyTab && (dstLegacyTabStopIdx != -1))
                {
                    dstTabStops.RemoveByIndex(dstLegacyTabStopIdx);
                    // We suppose there can be only one legacy TabStop in collection,
                    // but lets advance the position just in case to ensure that.
                    dstLegacyTabStopIdx = dstTabStops.Count;
                }

                // Even if it is a "clear position" tab stop we need to add it to the resulting
                // collection (not delete a tab stop in the specific position) because the
                // output might be used in writing to a DOC file where this command is required.

                dstTabStops.Add(srcTabStop.Clone());
            }

            dstTabStops.RemoveClearingWithTolerance();
            return dstTabStops;
        }

        /// <summary>
        /// IExpandableAttr
        /// </summary>
        void IExpandableAttr.Collapse(IExpandableAttr parentAttr)
        {
            if (parentAttr == null)
                return;

            TabStopCollection parentTabStops = (TabStopCollection)parentAttr;
            for (int i = 0; i < parentTabStops.Count; i++)
            {
                TabStop parentTabStop = parentTabStops[i];

                int childTabStopIndex = GetIndexByPosition(parentTabStop.Position);
                if (childTabStopIndex >= 0)
                {
                    // Remove a child tab if a same tab exists in the base.
                    TabStop childTabStop = this[childTabStopIndex];
                    if (childTabStop.Equals(parentTabStop))
                        RemoveByIndex(childTabStopIndex);
                }
                else
                {
                        // If a tab exists in the base, but not in child, add a "clear" tab to the child.
                        Add(parentTabStop.Position, TabAlignment.Clear, TabLeader.None);
                }
            }
        }

        /// <summary>
        /// Removes adjacent clearing tab if they are within 25 twips.
        /// </summary>
        /// <remarks>
        /// AM. It seems Word removes such tabs when does TabStopCollection expanding.
        /// Otherwise we failed to write revision properly, for example in TestDefect15121.docx.
        /// </remarks>
        internal void RemoveClearingWithTolerance()
        {
            if (Count == 0)
                return;

            NotifyChanging();

            for (int i = Count - 1; i > 0; i--)
            {
                TabStop tab = this[i];
                TabStop prevTab = this[i - 1];

                // Remove clear tab stop, if it is within 25 twips from the previous clear tab stop.
                if (tab.IsClear && prevTab.IsClear && (tab.PositionTwips - prevTab.PositionTwips <= 25))
                    RemoveByIndex(i);
            }
        }

        /// <summary>
        /// Returns index of TabStop with <see cref="TabStop.IsLegacyTab"/>
        /// property set to <c>true</c>, or -1 if not found.
        /// </summary>
        internal int GetLegacyTabStopIndex()
        {
            for (int i = 0; i < Count; i++)
            {
                if (this[i].IsLegacyTab)
                    return i;
            }

            return -1;
        }

        internal TabStop LegacyTabStop
        {
            get
            {
                int legacyTabStopIndex = GetLegacyTabStopIndex();

                return legacyTabStopIndex >= 0
                    ? this[legacyTabStopIndex]
                    : null;
            }
        }

        private SortedIntegerListGeneric<TabStop> mItems = new SortedIntegerListGeneric<TabStop>();
        private bool mHasTolerances;
    }
}
