// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 22/03/2022 by Edward Voronov

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace Aspose.Foundation.Tests.Tests.Common
{
    [TestFixture]
    [JavaAttributes.JavaDelete("Not a test.")]
    public class TestLanguageOnly
    {
        [Test, Ignore("Not a test.")]
        public void GenerateLanguageOnlyConstants()
        {
            Language[] languages = Enum.GetValues(typeof(Language))
                .Cast<Language>()
                .Where(p => p != Language.InvariantCulture && p != Language.LanguageNotSet)
                .ToArray();

            Dictionary<int, Language> constants = languages
                .Where(p => LanguageOnly.ToLanguageOnly((int)p) == (int)p)
                .ToDictionary(p => (int)p, p => p);

            foreach (Language language in languages)
            {
                int languageOnly = LanguageOnly.ToLanguageOnly((int)language);

                if (constants.ContainsKey(languageOnly))
                    continue;

                constants.Add(languageOnly, language);
            }

            Debug.WriteLine($"        // The constants below are generated by {nameof(TestLanguageOnly)}.{nameof(GenerateLanguageOnlyConstants)}");
            Debug.WriteLine(string.Join(
                Environment.NewLine,
                constants.Select(p => $"        public const int {GetConstantName(p.Value.ToString())} = (int)Language.{p.Value.ToString()} & 0xff;")));
        }

        private static string GetConstantName(string defaultName)
        {
            switch (defaultName)
            {
                case "SindhiDevanagaric": return "Devangari";
                case "ChineseSimplified": return "Chinese";
                case "TigrignaEthiopia": return "Ethiopian";
                case "TibetanChina": return "Tibetan";
                default:
                    return defaultName;
            }
        }
    }
}
