// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 31/08/2007 by Vladimir Averkin

using Aspose.Words.Nrx;
using Aspose.Words.RW.Nrx.Reader;

namespace Aspose.Words.RW.Docx.Reader
{
    /// <summary>
    /// Provides methods for parsing 'w:p' element.
    /// NOTE: this class should be immutable (state cannot be modified after it is created).
    /// </summary>
    internal class  DocxParaReader : NrxParaReaderBase
    {
        internal DocxParaReader(DocxParaPrReader paraPrReader,
            DocxInlineReader inlineReader)
        {
            Debug.Assert(paraPrReader != null);
            Debug.Assert(inlineReader != null);
            mParaPrReader = paraPrReader;
            mInlineReader = inlineReader;
        }

        // There are some interesting moments with reading paragraph child elements.
        // Some of them can occur before or after actual 'w:p' element.
        // For example, when bookmark starts from the beginning of the paragraph,
        // the bookmark start element is actually got placed before 'w:p' element
        // in WordML generated by MS Word:
        //
        //    <w:tbl>
        //        <w:tr>
        //            <w:tc>
        //                <aml:annotation aml:id="0" w:type="Word.Bookmark.Start" w:name="TableColumnBookmark" w:col-first="1" w:col-last="3" />
        //                <w:p>
        //                        ...
        //                <w:p />
        //            </w:tc>
        //        </w:tr>
        //        <aml:annotation aml:id="0" w:type="Word.Bookmark.End" w:col-first="1" w:col-last="3" />
        //    </w:tbl>
        //
        // Same is true for comment reference marks, although in our current model they are not stored:
        //    <aml:annotation aml:id="0" w:type="Word.Comment.Start" />
        //    <w:p>
        //        <w:r>
        //            <w:t>Some text, which the comment is referring to.</w:t>
        //        </w:r>
        //        <aml:annotation aml:id="0" w:type="Word.Comment.End" />
        //
        // Also, some of the 'w:p' child elements can produce more than one child node for the paragraph.
        //
        // So, to simplify things between DocxParaReader and paragraph child readers, such as
        // DocxParaChildReader and DocxAnnotationReader, let's put all child nodes being read
        // by child readers to a PendingNodes list in DocxReader.
        // All nodes from there are to be appended to the paragraph,
        // first after the 'w:p' element start is encountered,
        // and then after each successful 'w:p' child element read.
        /// <summary>
        /// Reads 'w:p' element from the specified reader. Reader should be positioned to element start.
        /// </summary>
        /// <param name="reader">DocxReader to read from. Should be positioned to element start.</param>
        /// <returns>True if the paragraph is a section break.</returns>
        internal override bool Read(NrxDocumentReaderBase reader)
        {
            bool isSectionBreak = false;

            Paragraph para = new Paragraph(reader.Document);
            reader.AddAndPushContainer(para);

            // WORDSNET-10436 "w:br" element might be read, so flush the run before reading paragraph content.
            NrxRunReaderBase.FlushRun(reader, new RunPr());

            reader.FlushPendingInlines();
            reader.FlushPendingCrossStructureAnnotations();
            reader.FlushPendingMarkup(para);

            // WORDSNET-10994 Flush formatting collected outside paragraph element.
            if (reader.GlobalParaPr.Count > 0)
            {
                reader.GlobalParaPr.ExpandTo(para.ParaPr);
                reader.GlobalParagraphBreakRunPr.ExpandTo(para.ParagraphBreakRunPr);

                reader.GlobalParaPr.Clear();
                reader.GlobalParagraphBreakRunPr.Clear();
            }

            // Read 'p' element attributes.
            if(!reader.LoadOptions.SkipFormatting)
                ReadPElementAttributes(reader, para);

            NrxXmlReader xmlReader = reader.XmlReader;

            // Read elements.
            xmlReader.MoveToElement();
            while (xmlReader.ReadChild("p"))
            {
                switch (xmlReader.LocalName)
                {
                    case "pPr":
                        isSectionBreak = mParaPrReader.Read(reader, para.ParaPr, para.ParagraphBreakRunPr);
                        break;
                    case "rPr":
                    {
                        // WORDSNET-22764 The document contains 'rPr' element in 'p'. MS Word reads it to
                        // para.ParagraphBreakRunPr.
                        DocxReaderFactory.RunReader.ReadTextLevelElement(reader, para.ParagraphBreakRunPr);
                        break;
                    }
                    default:
                        mInlineReader.ReadChild(reader);
                        break;
                }
            }

            // WORDSNET-22587 When Normal is not default paragraph style and there is no style defined at the paragraph,
            // Word applies default style to this paragraph explicitly.
            reader.ApplyDefaultStyle(para.ParaPr, StyleType.Paragraph);

            xmlReader.RsidRDefault = 0;

            // andrnosk: WORDSNET-8164 Markup elements should be closed after the last read paragraph.
            // Since upon reading AltChunk we add placeholder paragraph and we should close SDT after it,
            // that is why use CurContainer as PossibleSdtEnd. If there is no AltChunk CurContainer is para.
            Debug.Assert(reader.CurContainer is Paragraph);
            xmlReader.PossibleSdtEnd = reader.CurContainer;

            FormatRevisionUtil.ConvertToPositiveDifference((Paragraph)reader.CurContainer);

            reader.PopContainer(NodeType.Paragraph);
            return isSectionBreak;
        }

        /// <summary>
        /// Reads attribute of 'p' XML element.
        /// </summary>
        private static void ReadPElementAttributes(NrxDocumentReaderBase reader, Paragraph para)
        {
            NrxXmlReader xmlReader = reader.XmlReader;
            while (xmlReader.MoveToNextAttribute())
            {
                // The reading below is not entirely correct because not all rsid attributes are in the model now.
                switch (xmlReader.LocalName)
                {
                    case "paraId":
                    {
                        int paraId = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        // WORDSNET-22313 Store ParaId and resolve the duplicate ParaIds used in comments if necessary.
                        // WORDSNET-24100 Word ignores negative ParaId.
                        if(paraId > 0)
                            (reader as DocxDocumentReaderBase).MapParaId(paraId, para);
                        break;
                    }
                    case "textId":
                        para.TextId = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        break;
                    case "rsidDel":
                        // RK Don't know how to handle yet.
                        break;
                    case "rsidP":
                    {
                        // Specifies a unique identifier used to track the editing session when the
                        // paragraph's properties were last modified in this document.
                        int rsid = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        if (rsid != int.MinValue)
                            para.ParaPr.SetAttr(ParaAttr.RsidP, rsid);
                        break;
                    }
                    case "rsidR":
                    {
                        // Specifies a unique identifier used to track the editing session when the
                        // paragraph was added to the main document.
                        int rsid = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        if (rsid != int.MinValue)
                            para.ParagraphBreakRunPr.SetAttr(FontAttr.RsidR, rsid);
                        break;
                    }
                    case "rsidRDefault":
                    {
                        // Specifies a unique identifier used for all runs in this paragraph which do not
                        // explicitly declare an rsidR attribute. This attribute allows consumers to optimize
                        // the locations where rsid* values are written in this document.
                        int rsid = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        if (rsid != int.MinValue)
                            xmlReader.RsidRDefault = rsid;
                        break;
                    }
                    case "rsidRPr":
                    {
                        // Specifies a unique identifier used to track the editing session when
                        // the glyph character representing the paragraph mark was last modified in the document.
                        int rsid = NrxXmlUtil.TryHexToInt(xmlReader.Value);
                        if (rsid != int.MinValue)
                            para.ParagraphBreakRunPr.SetAttr(FontAttr.RsidRPr, rsid);
                        break;
                    }
                    default:
                        // Do nothing.
                        break;
                }
            }
        }

        private readonly DocxParaPrReader mParaPrReader;
        private readonly DocxInlineReader mInlineReader;
    }
}
