// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 13/02/2013 by Dmitry Matveenko

using System.Collections.Generic;
using Aspose.Collections;
using Aspose.Words.TableLayout;

namespace Aspose.Words.Tables
{
    /// <summary>
    /// The class implements table grid calculation for tables with a fixed layout.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Earlier, the main approach was to use the column widths stored in the document.
    /// TblGrid (in case of docx files) or cell widths (for doc files) were used.
    /// It works very well, naturally, when the widths are stored by MS Word itself.
    /// However, MS Word seems to re-calculate the column widths from the table and cell properties
    /// on opening a document and disregarding the stored grid when it does not match the result.
    /// So when the grid stored in the document is not correct, the columns in AW output may have incorrect widths.
    /// There are scores of CRs about it linked to WORDSNET-832
    /// Very often the documents with the incorrect grid are generated by AW itself.
    /// This is an attempt to re-construct the grid from table/cell properties.
    /// </para>
    /// <para>
    /// The grid reconstruction must be very reliable, because the result will replace the values stored in the document.
    /// The current implementation does not cover all possible cases.
    /// There are some known issues and in some cases MS Word behavior was not fully tested / understood.
    /// If during the grid calculation it is detected that the case is not supported,
    /// the calculated grid is not applied and AW falls back to the original approach of using the grid from the document.
    /// </para>
    /// <para>
    /// The class deals with the fixed table layout. Some methods are re-used by auto-fit table layout grid calculation.
    /// </para>
    /// </remarks>
    internal class FixedGridCalculator
    {
        /// <summary>
        /// Creates a new instance of the grid calculator and initializes the data needed for grid re-calculation from the table/cell properties.
        /// </summary>
        /// <param name="table">The table to calculate the grid for.</param>
        /// <param name="useOriginalTableGrid">Indicates if the original table grid from the document is to be used.
        /// When a document is just loading, the grid stored in the document may affect the width of the automatic cells.
        /// After the document is loaded, the effect of the original grid must be reflected in the model and the original grid
        /// should be disregarded if the grid is re-calculated because it may not be applicable due to model changes.
        /// </param>
        /// <remarks>
        /// <para>
        /// The constructor is private, the callers should use static methods to update table grid.
        /// </para>
        /// </remarks>
        private FixedGridCalculator(Table table, bool useOriginalTableGrid)
        {
            Document document = table.FetchDocument();

            // This option affects the calculation.
            mUseWord2003Rules = document.DocPr.CompatibilityOptions.AutofitToFirstFixedWidthCell;

            // Get the cell and row attributes needed to construct the grid.
            // Some of the attributes (cell spans) may change in the process.
            // So we cannot work directly with cell attributes in the model until it is clear that the grid may be applied.
            mRows = new List<RowSpan>();
            foreach (Row row in table.Rows)
            {
                RowSpan rowSpan = new RowSpan(row, useOriginalTableGrid);
                if (rowSpan.Cells.Count > 0)
                    mRows.Add(rowSpan);
            }

            Debug.Assert(mRows.Count > 0);

            IntList gridFromDocument = new IntList();
            if (useOriginalTableGrid)
            {
                TableGridColumnsAttr gridFromDoc = (TableGridColumnsAttr)table.TablePr.GetDirectAttr(TableAttr.Sys_TableGridForNewAlgorithm);
                if (gridFromDoc != null)
                {
                    // Copy the original grid column widths.
                    // The working copy may be changed during construction (columns merged or added).
                    gridFromDocument.AddRange(gridFromDoc.GridColumns);
                }
            }
            else
            {
                TableGridAttr calculatedGrid = table.TablePr.CalculatedGrid;
                if (calculatedGrid != null)
                {
                    // Calculated grid should be applied for fixed layout tables.
                    Debug.Assert((calculatedGrid.State == GridState.Applied) || table.AllowAutoFit);

                    // WORDSNET-16756 Use the calculated grid to avoid having default column widths in jagged tables.
                    gridFromDocument.AddRange(calculatedGrid.Columns);
                }
            }

            GridFromDocument = gridFromDocument;
        }

        /// <summary>
        /// Recalculates the table grid from table/cell properties for fixed table layout.
        /// </summary>
        /// <param name="table">The table to calculate the grid for.</param>
        /// <param name="isLoading">Indicates if the grid is updated for the first time during document loading. </param>
        /// <remarks>
        /// When a document is just loading, the grid stored in the document may affect the width of the automatic cells.
        /// After the document is loaded, the effect of the original grid must be reflected in the model and the original grid
        /// should be disregarded if the grid is re-calculated because it may not be applicable due to model changes.
        /// Also, some other attributes like width before are treated differently during loading because they may be updated both
        /// by the new and the old grid calculation algorithms.
        /// </remarks>
        internal static void UpdateTableGrid(Table table, bool isLoading)
        {
            // Nothing to do for a table with no rows.
            if (table.FirstRow == null)
                return;

            TableGridAttr grid = table.TablePr.CalculatedGrid;

            // Check if it is some of the known issues which can break tests etc.
            if (!IsGridCalculationSafe(table))
            {
                TableGridDebugLogger.DebugWriteLine(
                    string.Format("Condition unsupported by grid calculation found for table {0} in {1}.", table, table.ParentNode));

                if (grid == null)
                {
                    // Make an empty grid.
                    grid = new TableGridAttr();
                    table.TablePr.CalculatedGrid = grid;
                }

                // Remember the state that will prevent future re-calculations.
                // It will also prevent auto-fit grid calculation.
                grid.State = GridState.CalculationFailed;
                return;
            }

            if (table.FirstRow.TablePr.AllowAutoFit)
            {
                // Correct auto-fit table grid can only be constructed by using content metrics.
                // It is done in the layout engine.
                return;
            }

            // Some fixed grid tests fail when grid is calculated 2 times.
            if (grid != null)
            {
                bool previousGridCalculationSuccessful = (grid.State == GridState.Applied);

                if (!previousGridCalculationSuccessful)
                {
                    // As the previous grid calculation failed (or was unsafe),
                    // there is even less chance that a repeated attempt will succeed.
                    TableGridDebugLogger.DebugWriteLine("Not applied grid is not re-calculated.");
                    return;
                }

                bool isFixedLayoutTableHandledInLayout = !table.AllowAutoFit && table.NeedsShapeContainerWidth;
                if (!isLoading && isFixedLayoutTableHandledInLayout)
                {
                    // After initial loading, do not re-calculate grids for fixed layout tables if they require layout model.
                    // These are currently tables relying on container text box content area width.
                    // Content area width is (supposed to be) computed by rendering more reliably.
                    // Fixed grid calculator uses a simplistic method for text area calculation.
                    // So re-calculating existing grids is likely to produce a worse result.
                    TableGridDebugLogger.DebugWriteLine("Existing grid is not re-calculated for a table in text box.");
                    return;
                    // A scenario when a table inside text box was changed after initial loading is not handled by this condition.
                    // But then it is logical to update layout after model manipualtion in that case.
                }
            }

            TableGridDebugLogger.DebugWriteLine(string.Format("Updating fixed layout grid for {0} in {1}.", table, table.ParentNode));

            FixedGridCalculator gridCalculator = new FixedGridCalculator(table, isLoading);
            gridCalculator.UpdateTableGridCore(table);
        }

        internal static void SetGridCalculationFailed(Table table)
        {
            SetGridState(table, GridState.CalculationFailed);
        }

        private static void SetGridState(Table table, GridState state)
        {
            // In some cases, the grid in tablePr may not be set yet.
            if (table.TablePr.CalculatedGrid == null)
                table.TablePr.CalculatedGrid = new TableGridAttr();

            table.TablePr.CalculatedGrid.State = state;
        }

        /// <summary>
        /// Gets a boolean value indicating if grid calculation can be safely attempted for the given table.
        /// </summary>
        /// <remarks>
        /// Most of the conditions were added when some tests were broken because of grid calculation.
        /// For example, mere attempting to call FetchCellAttr() may break some tests because it may
        /// cause table style instantiation and as consequence, style attributes expansion on saving to some flow formats.
        /// The cases here should be investigated and handled, eventually.
        /// </remarks>
        private static bool IsGridCalculationSafe(Table table)
        {
            Document doc = table.Document as Document;
            // Do not build grid for tables in glossary document. The widths for them are not needed anyway.
            if (doc == null)
                return false;

            if (!IsTableContainerWidthCalculationSupported(table))
            {
                TableGridDebugLogger.DebugWriteLine("Table container width calculation is not implemented.");
                return false;
            }

            if (!table.AllowAutoFit && table.IsNested)
            {
                // Check that the parent grid is calculated for fixed layout.
                Table parent = (Table)table.GetAncestor(NodeType.Table);
                TableGridAttr parentGrid = parent.TablePr.CalculatedGrid;
                if (parentGrid == null || parentGrid.State != GridState.Applied)
                {
                    TableGridDebugLogger.DebugWriteLine("Nested table container grid is not calculated.");
                    return false;
                }
            }

            // There is TestDefect10334ForceUpgrade (made from TestDefect10334) where AW loads a document with
            // ForceUpgrade option. MS Word treats it as 2013, and that leads to different table width calculation.
            // Fall-back for unspecified Word version for now.
            if (doc.DocPr.ForceUpgrade && table.AllowAutoFit)
                return false;
            // Strangely enough, it works better without fall-back for a fixed layout table in the same TestDefect10334,
            // so I added fall-back for auto-fit tables only.

            // No point in trying to calculate the grid for an empty table.
            if (!TableHasCells(table))
                return false;

            // Getting the correct attribute value in presence of revisions is not implemented.
            if (TableHasRevisions(table))
                return false;

            // Added to bypass TestDefect5011_GoodWithCalcOffa.
            // The issue with the test is actually different (preferred widths are not present in the model).
            // But the grid is not calculated correctly for tables with spacing as well (left and right cells in the row are not correct).
            if (TableHasUnsupportedFeatures(table))
                return false;
            // The condition originally was (table.CellSpacing > 0d), but it does not detect when cell spacing is actually 0.
            // It was changed to ensure fall-back for auto-fit layout, but may probably make some fixed-layout documents worse
            // if they were originally handled by the new algorithm.

            return true;
        }

        /// <summary>
        /// Gets a boolean value indicating some of the table, row or cell properties have revisions.
        /// </summary>
        /// <remarks>
        /// TODO consider checking the revisions only for the properties affecting grid calculation.
        /// </remarks>
        private static bool TableHasRevisions(Table table)
        {
            // This checks table and row properties.
            if (table.TablePr.HasRevisions || table.HasRevision)
                return true;

            // Check cells.
            foreach (Row row in table.Rows)
                foreach (Cell cell in row.Cells)
                    if (cell.CellPr.HasRevisions)
                        return true;

            return false;
        }

        /// <summary>
        /// Indicates if a table has at lest one cell.
        /// </summary>
        private static bool TableHasCells(Table table)
        {
            // Check cells.
            foreach (Row row in table.Rows)
                foreach (Cell cell in row.Cells)
                        return true;

            return false;
        }

        /// <summary>
        /// Gets a boolean value indicating if cell spacing prevents correct grid calculation,
        /// or there are cells with grid span 0.
        /// </summary>
        /// <remarks>
        /// Returns true even if the specified spacing is zero.
        /// Zero spacing is very different from no spacing in MS Word layout.
        /// One exception is when there is no vertical borders in the table.
        /// In that case, zero spacing does not affect column widths.
        /// The case is detected in order to apply the new algorithm to fix WORDSNET-13923
        /// The code should not be needed when cell spacing is supported properly.
        /// </remarks>
        private static bool TableHasUnsupportedFeatures(Table table)
        {
            Row firstRow = table.FirstRow;
            if (firstRow == null)
                return false;

            // This fixes golds for a bunch of model tests.
            // A spacing vs border check that always accessed table style was removed per WORDSNET-4794
            // Without the access, TableNormal is removed from the saved documents and it breaks some golds.
            // Access table style in order to preserve the golds.
            TableStyle style = table.Style as TableStyle;
            bool hasStyle = (style != null);
            // This can be removed after model code is reworked to create TableNormal unconditionally.
            bool hasFitTextOptions = hasStyle && style.CellPr.FitText;

            bool hasSpacing = firstRow.HasCellSpacing;
            int spacing = firstRow.CellSpacing;

            // Need to check all rows as spacing may be specified as an exception.
            foreach (Row row in table.Rows)
            {
                if (row.Cells.Count >= TableGridConstructor.ColumnCountLimit64)
                {
                    // Happens with a generated table in TestCellReferences().
                    TableGridDebugLogger.DebugWriteLine(string.Format("Row cell count exceeds the number supported by MS Word ({0}).",
                        TableGridConstructor.ColumnCountLimit64));
                    return true;
                }

                if ((hasSpacing != row.HasCellSpacing) || (spacing != row.CellSpacing))
                {
                    TableGridDebugLogger.DebugWriteLine("Different cell spacing settings within a table are not supported.");
                    return true;
                }

                Cell firstInMerge = null;
                foreach (Cell cell in row.Cells)
                {
                    CellPr cellPr = cell.CellPr;

                    if ((cellPr.GridSpan <= 0) &&
                        ((cellPr.HorizontalMerge != CellMerge.Previous) || (firstInMerge == null)))
                    {
                        // For merged cells I understand how to handle grid span 0.
                        // Such cells usually have zero width in doc/rtf files.

                        // A regular (not merged or first in merge) cell with zero grid span should not normally happen.
                        TableGridDebugLogger.DebugWriteLine(
                            string.Format("A not merged cell with grid span 0: {0} encountered. Grid calculation aborted.", cell));
                        return true;
                    }

                    switch (cellPr.HorizontalMerge)
                    {
                        case CellMerge.None:
                            firstInMerge = null;
                            break;
                        case CellMerge.First:
                            firstInMerge = cell;
                            break;
                        default:
                            // First in merge remains the same.
                            break;
                    }

                    if (cellPr.FitText)
                        hasFitTextOptions = true;
                    // CellPr.FitText does not seem to resolve style attributes. Let it be for now.

                }
            }

            if (hasSpacing && hasFitTextOptions)
            {
                // UnifiedTestAll(): a fixed layout table with FitText set on one of the cells has a different grid.
                TableGridDebugLogger.DebugWriteLine("A cell with fit text option set encountered. Grid calculation aborted.");
                return true;
                // The fall-back was introduced for tables with spacing only.
                // Different widths in fixed layout table look like a glitch in MS Word.
                // If spacing is removed, the table has the same grid regardless of FitText option.
                // "Don't wrap text" option has no effect either, both with and without spacing.
            }

            // No unsupported features.
            return false;
        }

        /// <summary>
        /// Implements grid re-calculation from the table and cell properties for fixed table layout.
        /// </summary>
        private void UpdateTableGridCore(Table table)
        {
            Debug.Assert(!table.FirstRow.TablePr.AllowAutoFit);

            bool isAutoFit = false;
            bool isBinaryDocRtf = DocRtfGridHandler.IsGridStoredInCellWidths(table);
            int halfSpacing = table.AllowCellSpacing
                ? table.FirstRow.CellSpacing
                : TableGridMetrics.SpacingDisabled;
            TableGridConstructor gridCtor = new TableGridConstructor(GridFromDocument, mRows, halfSpacing, isAutoFit, mUseWord2003Rules, isBinaryDocRtf);
            bool gridResizingFailed = false;
            while (gridCtor.PrepareNextRowBlock())
            {
                gridCtor.GetGridFromCells();
                do
                {
                    // Grid resizing does not access rows, it just needs the grid for the current block and tblw.
                    gridResizingFailed |= ResizeGridForTableWidth(table, gridCtor.Grid);
                } while (!gridResizingFailed &&
                    gridCtor.RemoveIntersectionsAfterResizing());
            }

            // Merge all block grids and apply the result to the table if needed.
            bool isGridApplicable = !gridCtor.IsUnsupportedConditionDetected && !gridResizingFailed;
            TableGridAttr gridAttr = gridCtor.ApplyCombinedGrid(table, isGridApplicable);
            table.TablePr.CalculatedGrid = gridAttr;
        }

        /// <summary>
        /// Resizes the grid so that the sum of the column widths equals table width.
        /// </summary>
        /// <returns>A boolean value indicating if an unsupported condition was encountered during resize.</returns>
        private bool ResizeGridForTableWidth(Table table, TableGrid grid)
        {
            // Container width determines the table width for tblw in percent units, and for tblw auto.
            // For pct tblw the method actually calculates the specified percent from the container widths.
            int containerWidthDelta = Extensions.GetContainerWidthDelta(table);
            int maxWidthFromContainer = Extensions.GetMaxAllowedWidthFromContainer(table, containerWidthDelta);
            // The conversion is unnecessary as the attribute is stored in twips.
            // However, the methods that resolve styles are hidden, so it is simpler to convert it back.

            int tableIndent = ConvertUtilCore.PointToTwip(table.LeftIndent);
            int halfSpacing = table.FirstRow.CellSpacing;

            // Get the padding/border needed for the max table width adjustment.
            int maxWidthAdjustment = 0;
            if (!(table.Document.DocPr.CompatibilityOptions.IsWord2013OrLaterCompatible || table.IsNested))
            {
                // The code handles experimental table width adjustment logic which was not fully tested as the case is rare.
                // 2013 mode, nested tables were not tested.
                // Fall-back happens in any case. The logic is needed for some tests that took a long time to investigate.
                // Perhaps the value could be included in maxWidthFromContainer, but it is not clear in the moment.

                Cell firstCell = table.FirstRow.FirstCell;
                int leftBorderTwips = Extensions.GetLeftBorderTwips(firstCell);
                int leftBorderTwipsHalf = MathUtil.Divide(leftBorderTwips, 2);
                int leftPadding = Extensions.ResolvedLeftPadding(firstCell);

                maxWidthAdjustment = System.Math.Max(leftPadding, leftBorderTwipsHalf);
            }

            TableGridResizer resizer = new TableGridResizer(grid, mUseWord2003Rules,
                maxWidthFromContainer, maxWidthAdjustment,
                table.PreferredWidth, tableIndent,
                halfSpacing);

            resizer.Resize();
            return resizer.IsUnsupportedCaseDetected;
        }

        /// <summary>
        /// Gets a boolean value indicating if the container width can be relied upon.
        /// </summary>
        /// <remarks>
        /// It checks if the table is in a floating frame or in a comment.
        /// </remarks>
        internal static bool IsTableContainerWidthCalculationSupported(Table table)
        {
            bool isContainerSupported;

            NodeType containerType = table.FirstNonMarkupParentNode.NodeType;
            if (containerType == NodeType.Comment)
            {
                // Container width in comments does not look straightforward, see TestTblwPctInCommentNotApplied.
                isContainerSupported = false;
            }
            // There is TestTblwInFrame in fixed layout that checks re-calculation for tblw auto and twips.
            // For auto-fit, tables in frames were not investigated, and removing this fall-back fails about 10 tests.
            else if (table.AllowAutoFit || table.PreferredWidth.IsPercent)
            {
                // Check if the first table paragraph has frame attributes.
                // Frame attributes are ignored in a nested table.
                Paragraph firstParagraph = GetFirstTableParagraph(table);
                bool isInFloatingFrame = (firstParagraph != null) &&
                    (containerType != NodeType.Cell) &&
                    HasFrameAttributes(firstParagraph);
                isContainerSupported = !isInFloatingFrame;
            }
            else
                isContainerSupported = true;

            return isContainerSupported;
        }

        private static Paragraph GetFirstTableParagraph(Table table)
        {
            Node firstContent = table;

            while ((firstContent != null) && (firstContent.NodeType == NodeType.Table) && ((Table)firstContent).HasCells)
            {
                firstContent = ((Table)firstContent).FirstRow.FirstCell.FirstNonMarkupCompositeDescendant;
            }

            return (firstContent != null) && (firstContent.NodeType == NodeType.Paragraph)
                ? (Paragraph) firstContent
                : null;
        }

        private static bool HasFrameAttributes(Paragraph para)
        {
            ParaPr paraPr = para.GetExpandedParaPr(ParaPrExpandFlags.DocumentDefaults);

            return paraPr.HasFrameAttributes;
        }

        /// <summary>
        /// Gets the grid columns originally defined in the document.
        /// </summary>
        /// <remarks>
        /// The values are stored in tblGrid for docx files, or derived from cell widths stored in doc files.
        /// The values are normally re-calculated as a result of grid update.
        /// The original values may affect the grid construction in some cases though.
        /// </remarks>
        private IntList GridFromDocument { get; }

        private readonly List<RowSpan> mRows;
        private readonly bool mUseWord2003Rules;
    }
}
