// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// DO NOT MODIFY. THIS FILE IS AUTOGENERATED FROM
// X:\awnet\Aspose.Words\Model\Drawing\ShapeAttr.cs

using Aspose.Collections;
using Aspose.Words.Drawing.Core.Dml;

namespace Aspose.Words.Drawing.Core
{
    internal class ShapePrBag
    {
        internal object TransformRotation;
        internal object LockAgainstUngrouping;
        internal object LockRotation;
        internal object LockAspectRatio;
        internal object LockPosition;
        internal object LockAgainstSelect;
        internal object LockCropping;
        internal object LockVertices;
        internal object LockText;
        internal object LockAdjustHandles;
        internal object LockAgainstGrouping;
        internal object TextboxTxid;
        internal object TextboxLeft;
        internal object TextboxTop;
        internal object TextboxRight;
        internal object TextboxBottom;
        internal object TextboxWrapMode;
        internal object TextboxZoom;
        internal object TextboxAnchor;
        internal object TextboxLayoutFlow;
        internal object TextboxFontRotation;
        internal object TextboxNextShapeId;
        internal object TextDirection;
        internal object TextboxColumns;
        internal object TextboxColumnMargin;
        internal object TextboxNextShapeIdRaw;
        internal object TextboxSelectText;
        internal object TextboxAutoTextMargin;
        internal object TextboxRotateText;
        internal object TextboxFitShapeToText;
        internal object TextboxFitTextToShape;
        internal object GeoTextText;
        internal object GeoTextRtf;
        internal object GeoTextAlign;
        internal object GeoTextSize;
        internal object GeoTextSpacing;
        internal object GeoTextFont;
        internal object GeoTextCssFont;
        internal object GeoTextReverseRows;
        internal object GeoTextOn;
        internal object GeoTextVertical;
        internal object GeoTextKerning;
        internal object GeoTextTight;
        internal object GeoTextStretch;
        internal object GeoTextShrinkFit;
        internal object GeoTextBestFit;
        internal object GeoTextNormalize;
        internal object GeoTextDxMeasure;
        internal object GeoTextBold;
        internal object GeoTextItalic;
        internal object GeoTextUnderline;
        internal object GeoTextShadow;
        internal object GeoTextSmallCaps;
        internal object GeoTextStrikeThrough;
        internal object ImageCropTop;
        internal object ImageCropBottom;
        internal object ImageCropLeft;
        internal object ImageCropRight;
        internal object GraphicFrameExtWidth;
        internal object GraphicFrameExtHeight;
        internal object ImageTransparent;
        internal object ImageContrast;
        internal object ImageBrightness;
        internal object ImageGamma;
        internal object OleTxid;
        internal object ImageDblCrMod;
        internal object ImageFillCrMod;
        internal object ImageLineCrMod;
        internal object ImageTransparentExt;
        internal object ImageTransparentExtMod;
        internal object ImageRecolor;
        internal object ImageRecolorExt;
        internal object Undocumented284;
        internal object ImageRecolorExtCrMod;
        internal object Undocumented286;
        internal object Undocumented287;
        internal object ImagePreserveGrays;
        internal object ImageNoHitTest;
        internal object ImageGrayScale;
        internal object ImageBiLevel;
        internal object ImageActive;
        internal object GeometryVertices;
        internal object GeometrySegmentInfo;
        internal object GeometryAdjust1;
        internal object GeometryAdjust2;
        internal object GeometryAdjust3;
        internal object GeometryAdjust4;
        internal object GeometryAdjust5;
        internal object GeometryAdjust6;
        internal object GeometryAdjust7;
        internal object GeometryAdjust8;
        internal object GeometryAdjust9;
        internal object GeometryAdjust10;
        internal object GeometryConnectLocs;
        internal object GeometryConnectAngles;
        internal object GeometryXLimo;
        internal object GeometryYLimo;
        internal object GeometryHandles;
        internal object GeometryFormulas;
        internal object GeometryPathTextBoxRects;
        internal object GeometryConnectionSiteType;
        internal object GeometryShadowOK;
        internal object GeometryThreeDOK;
        internal object GeometryLineOK;
        internal object GeometryGTextOK;
        internal object GeometryFillShadeShapeOK;
        internal object GeometryFillOK;
        internal object FillType;
        internal object FillColor;
        internal object FillOpacity;
        internal object FillBackColor;
        internal object FillBackOpacity;
        internal object FillCrMod;
        internal object FillBlipName;
        internal object FillBlipNameFlags;
        internal object FillWidth;
        internal object FillHeight;
        internal object FillAngle;
        internal object FillFocus;
        internal object FillToLeft;
        internal object FillToTop;
        internal object FillToRight;
        internal object FillToBottom;
        internal object FillRectLeft;
        internal object FillRectTop;
        internal object FillRectRight;
        internal object FillRectBottom;
        internal object FillDimensionType;
        internal object FillShadePreset;
        internal object FillShadeColors;
        internal object FillOriginX;
        internal object FillOriginY;
        internal object FillShapeOriginX;
        internal object FillShapeOriginY;
        internal object FillShadeType;
        internal object FillColorExt;
        internal object FillColorExtCMY;
        internal object FillColorExtMod;
        internal object Undocumented417;
        internal object FillBackColorExt;
        internal object FillBackColorExtCMY;
        internal object FillBackColorExtMod;
        internal object Undocumented421;
        internal object FillColorExtK;
        internal object FillBackColorExtK;
        internal object FillRecolorAsPicture;
        internal object FillUseShapeAnchor;
        internal object Filled;
        internal object FillHitTest;
        internal object FillShape;
        internal object FillUseRect;
        internal object FillNoFillHitTest;
        internal object LineColor;
        internal object LineOpacity;
        internal object LineBackColor;
        internal object LineCrMod;
        internal object LineFillType;
        internal object LineFillBlipName;
        internal object LineFillBlipNameFlags;
        internal object LineFillWidth;
        internal object LineFillHeight;
        internal object LineFillDimensionType;
        internal object LineWidth;
        internal object LineMiterLimit;
        internal object LineStyle;
        internal object LineDashStyle;
        internal object LineDashData;
        internal object LineStartArrow;
        internal object LineEndArrow;
        internal object LineStartArrowWidth;
        internal object LineStartArrowLength;
        internal object LineEndArrowWidth;
        internal object LineEndArrowLength;
        internal object LineJoinStyle;
        internal object LineEndCapStyle;
        internal object LineColorExt;
        internal object LineColorExtCMY;
        internal object LineColorExtMod;
        internal object Undocumented476;
        internal object LineBackColorExt;
        internal object LineBackColorExtCMY;
        internal object LineBackColorExtMod;
        internal object Undocumented480;
        internal object LineColorExtK;
        internal object LineBackColorExtK;
        internal object LineRecolorFillAsPicture;
        internal object LineUseShapeAnchor;
        internal object LineInsetPen;
        internal object LineInsetPenOk;
        internal object LineArrowHeadsOK;
        internal object LineOn;
        internal object LineHitTest;
        internal object LineFillShape;
        internal object LineNoLineDrawDash;
        internal object ShadowType;
        internal object ShadowColor;
        internal object ShadowHighlight;
        internal object ShadowCrMod;
        internal object ShadowOpacity;
        internal object ShadowOffsetX;
        internal object ShadowOffsetY;
        internal object ShadowSecondOffsetX;
        internal object ShadowSecondOffsetY;
        internal object ShadowScaleXtoX;
        internal object ShadowScaleYtoX;
        internal object ShadowScaleXtoY;
        internal object ShadowScaleYtoY;
        internal object ShadowPerspectiveX;
        internal object ShadowPerspectiveY;
        internal object ShadowWeight;
        internal object ShadowOriginX;
        internal object ShadowOriginY;
        internal object ShadowColorExt;
        internal object ShadowColorExtCMY;
        internal object ShadowColorExtMod;
        internal object Undocumented533;
        internal object ShadowHighlightExt;
        internal object ShadowHighlightExtCMY;
        internal object ShadowHighlightExtMod;
        internal object Undocumented537;
        internal object ShadowColorExtK;
        internal object ShadowHighlightExtK;
        internal object ShadowOn;
        internal object ShadowObscured;
        internal object PerspectiveType;
        internal object PerspectiveOffsetX;
        internal object PerspectiveOffsetY;
        internal object PerspectiveScaleXToX;
        internal object PerspectiveScaleYToX;
        internal object PerspectiveScaleXToY;
        internal object PerspectiveScaleYToY;
        internal object PerspectiveX;
        internal object PerspectiveY;
        internal object PerspectiveWeight;
        internal object PerspectiveOriginX;
        internal object PerspectiveOriginY;
        internal object PerspectiveOn;
        internal object TDSpecularAmount;
        internal object TDDiffuseAmount;
        internal object TDShininess;
        internal object TDEdgeThickness;
        internal object TDExtrudeForward;
        internal object TDExtrudeBackward;
        internal object TDExtrudePlane;
        internal object TDExtrusionColor;
        internal object TDCrMod;
        internal object TDExtrusionColorExt;
        internal object TDExtrusionColorExtCMY;
        internal object TDExtrusionColorExtMod;
        internal object Undocumented652;
        internal object TDExtrusionColorExtK;
        internal object Undocumented663;
        internal object Undocumented666;
        internal object TDOn;
        internal object TDMetallic;
        internal object TDUseExtrusionColor;
        internal object TDLightFace;
        internal object TDRotationAngleY;
        internal object TDRotationAngleX;
        internal object TDRotationAxisX;
        internal object TDRotationAxisY;
        internal object TDRotationAxisZ;
        internal object TDRotationAngle;
        internal object TDRotationCenterX;
        internal object TDRotationCenterY;
        internal object TDRotationCenterZ;
        internal object TDRenderMode;
        internal object TDTolerance;
        internal object TDViewpointX;
        internal object TDViewpointY;
        internal object TDViewpointZ;
        internal object TDOriginX;
        internal object TDOriginY;
        internal object TDSkewAngle;
        internal object TDSkewAmount;
        internal object TDAmbientIntensity;
        internal object TDKeyX;
        internal object TDKeyY;
        internal object TDKeyZ;
        internal object TDKeyIntensity;
        internal object TDFillX;
        internal object TDFillY;
        internal object TDFillZ;
        internal object TDFillIntensity;
        internal object TDConstrainRotation;
        internal object TDRotationCenterAuto;
        internal object TDParallel;
        internal object TDKeyHarsh;
        internal object TDFillHarsh;
        internal object ConnectorType;
        internal object BWMode;
        internal object BWPure;
        internal object BWNormal;
        internal object DiagramNodeLayout;
        internal object DiagramNodeKind;
        internal object DiagramLayoutMRU;
        internal object EquationXML;
        internal object PolicyLabel;
        internal object PolicyBarCode;
        internal object FlipHQFE5152;
        internal object FlipVQFE5152;
        internal object OleIcon;
        internal object PreferRelativeResize;
        internal object LockShapeType;
        internal object Initiator;
        internal object DeleteAttachedObject;
        internal object CalloutType;
        internal object CalloutGap;
        internal object CalloutAngle;
        internal object CalloutDropType;
        internal object CalloutDropDistance;
        internal object CalloutLength;
        internal object CalloutOn;
        internal object CalloutAccentBar;
        internal object CalloutTextBorder;
        internal object CalloutMinusX;
        internal object CalloutMinusY;
        internal object CalloutDropAuto;
        internal object CalloutLengthSpecified;
        internal object ShapeName;
        internal object ShapeDescription;
        internal object ShapeTitle;
        internal object HyperlinkAddress;
        internal object WrapPolygonVertices;
        internal object DistanceLeft;
        internal object DistanceTop;
        internal object DistanceRight;
        internal object DistanceBottom;
        internal object RegroupId;
        internal object ScreenTip;
        internal object ScriptText;
        internal object HorizontalAlignment;
        internal object RelativeHorizontalPosition;
        internal object VerticalAlignment;
        internal object RelativeVerticalPosition;
        internal object HRPct;
        internal object HRAlign;
        internal object HRHeight;
        internal object HRWidth;
        internal object ScriptType;
        internal object ScriptLanguage;
        internal object ScriptIdAttr;
        internal object ScriptLanguageName;
        internal object BorderTopColor;
        internal object BorderLeftColor;
        internal object BorderBottomColor;
        internal object BorderRightColor;
        internal object MetroBlob;
        internal object Dhgt;
        internal object AllowInCell;
        internal object PictureBullet;
        internal object HRStandard;
        internal object HRNoShade;
        internal object HROn;
        internal object UserDrawn;
        internal object AllowOverlap;
        internal object ReallyHidden;
        internal object ScriptAnchor;
        internal object EditedWrap;
        internal object BehindText;
        internal object OnDblClickNotify;
        internal object Button;
        internal object OneD;
        internal object Hidden;
        internal object Print;
        internal object UnknownHtmlFlags;
        internal object EditAs;
        internal object DiagramStyle;
        internal object Undocumented1282;
        internal object Undocumented1283;
        internal object DiagramRelationsTable;
        internal object DiagramScaleX;
        internal object DiagramScaleY;
        internal object DiagramFontSize;
        internal object DiagramConstrainBounds;
        internal object DiagramBaseTextScale;
        internal object DiagramAutoFormat;
        internal object DiagramReverse;
        internal object DiagramAutoLayout;
        internal object PseudoInline;
        internal object ClipVertices;
        internal object ClipSegmentInfo;
        internal object ClipShapePath;
        internal object ClipToWrap;
        internal object ClipOK;
        internal object InkData;
        internal object InkAnnotation;
        internal object SigSetupId;
        internal object SigSetupProvId;
        internal object SigSetupSuggSigner;
        internal object SigSetupSuggSigner2;
        internal object SigSetupSuggSignerEmail;
        internal object SigSetupSignInst;
        internal object SigSetupAddlXml;
        internal object SigSetupProvUrl;
        internal object SigSetupShowSignDate;
        internal object SigSetupAllowComments;
        internal object SigSetupSignInstSet;
        internal object IsSignatureLine;
        internal object LeftPercent;
        internal object TopPercent;
        internal object WidthPercent;
        internal object HeightPercent;
        internal object RelativeWidth;
        internal object RelativeHeight;
        internal object ColStart;
        internal object ColSpan;
        internal object Flip;
        internal object WrapType;
        internal object WrapSide;
        internal object AnchorLocked;
        internal object ImageBytes;
        internal object ImageTitle;
        internal object ImageSourceFullName;
        internal object BorderTop;
        internal object BorderLeft;
        internal object BorderBottom;
        internal object BorderRight;
        internal object LineImageBytes;
        internal object FillImageBytes;
        internal object OleObject;
        internal object OleProgID;
        internal object OleSourceFullName;
        internal object OleSourceItem;
        internal object OleAutoUpdate;
        internal object OleLocked;
        internal object OleLinkType;
        internal object OleFormatUpdateType;
        internal object HyperlinkTarget;
        internal object LineFillPresetTexture;
        internal object FillPresetTexture;
        internal object ShapeId;
        internal object CoordOriginX;
        internal object CoordOriginY;
        internal object CoordSizeWidth;
        internal object CoordSizeHeight;
        internal object Left;
        internal object Top;
        internal object Width;
        internal object Height;
        internal object DmlLockArrowHeads;
        internal object DmlLockResize;
        internal object DmlLockDrillDown;
        internal object DmlEffectExtentLeft;
        internal object DmlEffectExtentTop;
        internal object DmlEffectExtentRight;
        internal object DmlEffectExtentBottom;
        internal object ThemeColor;
        internal object ThemeShade;
        internal object ThemeTint;
        internal object ZOrder;
        internal object ShapeType;
        internal StringToObjDictionary<DmlExtension> DocPrExtensions;

        internal void Reset()
        {
            TransformRotation = null;
            LockAgainstUngrouping = null;
            LockRotation = null;
            LockAspectRatio = null;
            LockPosition = null;
            LockAgainstSelect = null;
            LockCropping = null;
            LockVertices = null;
            LockText = null;
            LockAdjustHandles = null;
            LockAgainstGrouping = null;
            TextboxTxid = null;
            TextboxLeft = null;
            TextboxTop = null;
            TextboxRight = null;
            TextboxBottom = null;
            TextboxWrapMode = null;
            TextboxZoom = null;
            TextboxAnchor = null;
            TextboxLayoutFlow = null;
            TextboxFontRotation = null;
            TextboxNextShapeId = null;
            TextDirection = null;
            TextboxColumns = null;
            TextboxColumnMargin = null;
            TextboxNextShapeIdRaw = null;
            TextboxSelectText = null;
            TextboxAutoTextMargin = null;
            TextboxRotateText = null;
            TextboxFitShapeToText = null;
            TextboxFitTextToShape = null;
            GeoTextText = null;
            GeoTextRtf = null;
            GeoTextAlign = null;
            GeoTextSize = null;
            GeoTextSpacing = null;
            GeoTextFont = null;
            GeoTextCssFont = null;
            GeoTextReverseRows = null;
            GeoTextOn = null;
            GeoTextVertical = null;
            GeoTextKerning = null;
            GeoTextTight = null;
            GeoTextStretch = null;
            GeoTextShrinkFit = null;
            GeoTextBestFit = null;
            GeoTextNormalize = null;
            GeoTextDxMeasure = null;
            GeoTextBold = null;
            GeoTextItalic = null;
            GeoTextUnderline = null;
            GeoTextShadow = null;
            GeoTextSmallCaps = null;
            GeoTextStrikeThrough = null;
            ImageCropTop = null;
            ImageCropBottom = null;
            ImageCropLeft = null;
            ImageCropRight = null;
            GraphicFrameExtWidth = null;
            GraphicFrameExtHeight = null;
            ImageTransparent = null;
            ImageContrast = null;
            ImageBrightness = null;
            ImageGamma = null;
            OleTxid = null;
            ImageDblCrMod = null;
            ImageFillCrMod = null;
            ImageLineCrMod = null;
            ImageTransparentExt = null;
            ImageTransparentExtMod = null;
            ImageRecolor = null;
            ImageRecolorExt = null;
            Undocumented284 = null;
            ImageRecolorExtCrMod = null;
            Undocumented286 = null;
            Undocumented287 = null;
            ImagePreserveGrays = null;
            ImageNoHitTest = null;
            ImageGrayScale = null;
            ImageBiLevel = null;
            ImageActive = null;
            GeometryVertices = null;
            GeometrySegmentInfo = null;
            GeometryAdjust1 = null;
            GeometryAdjust2 = null;
            GeometryAdjust3 = null;
            GeometryAdjust4 = null;
            GeometryAdjust5 = null;
            GeometryAdjust6 = null;
            GeometryAdjust7 = null;
            GeometryAdjust8 = null;
            GeometryAdjust9 = null;
            GeometryAdjust10 = null;
            GeometryConnectLocs = null;
            GeometryConnectAngles = null;
            GeometryXLimo = null;
            GeometryYLimo = null;
            GeometryHandles = null;
            GeometryFormulas = null;
            GeometryPathTextBoxRects = null;
            GeometryConnectionSiteType = null;
            GeometryShadowOK = null;
            GeometryThreeDOK = null;
            GeometryLineOK = null;
            GeometryGTextOK = null;
            GeometryFillShadeShapeOK = null;
            GeometryFillOK = null;
            FillType = null;
            FillColor = null;
            FillOpacity = null;
            FillBackColor = null;
            FillBackOpacity = null;
            FillCrMod = null;
            FillBlipName = null;
            FillBlipNameFlags = null;
            FillWidth = null;
            FillHeight = null;
            FillAngle = null;
            FillFocus = null;
            FillToLeft = null;
            FillToTop = null;
            FillToRight = null;
            FillToBottom = null;
            FillRectLeft = null;
            FillRectTop = null;
            FillRectRight = null;
            FillRectBottom = null;
            FillDimensionType = null;
            FillShadePreset = null;
            FillShadeColors = null;
            FillOriginX = null;
            FillOriginY = null;
            FillShapeOriginX = null;
            FillShapeOriginY = null;
            FillShadeType = null;
            FillColorExt = null;
            FillColorExtCMY = null;
            FillColorExtMod = null;
            Undocumented417 = null;
            FillBackColorExt = null;
            FillBackColorExtCMY = null;
            FillBackColorExtMod = null;
            Undocumented421 = null;
            FillColorExtK = null;
            FillBackColorExtK = null;
            FillRecolorAsPicture = null;
            FillUseShapeAnchor = null;
            Filled = null;
            FillHitTest = null;
            FillShape = null;
            FillUseRect = null;
            FillNoFillHitTest = null;
            LineColor = null;
            LineOpacity = null;
            LineBackColor = null;
            LineCrMod = null;
            LineFillType = null;
            LineFillBlipName = null;
            LineFillBlipNameFlags = null;
            LineFillWidth = null;
            LineFillHeight = null;
            LineFillDimensionType = null;
            LineWidth = null;
            LineMiterLimit = null;
            LineStyle = null;
            LineDashStyle = null;
            LineDashData = null;
            LineStartArrow = null;
            LineEndArrow = null;
            LineStartArrowWidth = null;
            LineStartArrowLength = null;
            LineEndArrowWidth = null;
            LineEndArrowLength = null;
            LineJoinStyle = null;
            LineEndCapStyle = null;
            LineColorExt = null;
            LineColorExtCMY = null;
            LineColorExtMod = null;
            Undocumented476 = null;
            LineBackColorExt = null;
            LineBackColorExtCMY = null;
            LineBackColorExtMod = null;
            Undocumented480 = null;
            LineColorExtK = null;
            LineBackColorExtK = null;
            LineRecolorFillAsPicture = null;
            LineUseShapeAnchor = null;
            LineInsetPen = null;
            LineInsetPenOk = null;
            LineArrowHeadsOK = null;
            LineOn = null;
            LineHitTest = null;
            LineFillShape = null;
            LineNoLineDrawDash = null;
            ShadowType = null;
            ShadowColor = null;
            ShadowHighlight = null;
            ShadowCrMod = null;
            ShadowOpacity = null;
            ShadowOffsetX = null;
            ShadowOffsetY = null;
            ShadowSecondOffsetX = null;
            ShadowSecondOffsetY = null;
            ShadowScaleXtoX = null;
            ShadowScaleYtoX = null;
            ShadowScaleXtoY = null;
            ShadowScaleYtoY = null;
            ShadowPerspectiveX = null;
            ShadowPerspectiveY = null;
            ShadowWeight = null;
            ShadowOriginX = null;
            ShadowOriginY = null;
            ShadowColorExt = null;
            ShadowColorExtCMY = null;
            ShadowColorExtMod = null;
            Undocumented533 = null;
            ShadowHighlightExt = null;
            ShadowHighlightExtCMY = null;
            ShadowHighlightExtMod = null;
            Undocumented537 = null;
            ShadowColorExtK = null;
            ShadowHighlightExtK = null;
            ShadowOn = null;
            ShadowObscured = null;
            PerspectiveType = null;
            PerspectiveOffsetX = null;
            PerspectiveOffsetY = null;
            PerspectiveScaleXToX = null;
            PerspectiveScaleYToX = null;
            PerspectiveScaleXToY = null;
            PerspectiveScaleYToY = null;
            PerspectiveX = null;
            PerspectiveY = null;
            PerspectiveWeight = null;
            PerspectiveOriginX = null;
            PerspectiveOriginY = null;
            PerspectiveOn = null;
            TDSpecularAmount = null;
            TDDiffuseAmount = null;
            TDShininess = null;
            TDEdgeThickness = null;
            TDExtrudeForward = null;
            TDExtrudeBackward = null;
            TDExtrudePlane = null;
            TDExtrusionColor = null;
            TDCrMod = null;
            TDExtrusionColorExt = null;
            TDExtrusionColorExtCMY = null;
            TDExtrusionColorExtMod = null;
            Undocumented652 = null;
            TDExtrusionColorExtK = null;
            Undocumented663 = null;
            Undocumented666 = null;
            TDOn = null;
            TDMetallic = null;
            TDUseExtrusionColor = null;
            TDLightFace = null;
            TDRotationAngleY = null;
            TDRotationAngleX = null;
            TDRotationAxisX = null;
            TDRotationAxisY = null;
            TDRotationAxisZ = null;
            TDRotationAngle = null;
            TDRotationCenterX = null;
            TDRotationCenterY = null;
            TDRotationCenterZ = null;
            TDRenderMode = null;
            TDTolerance = null;
            TDViewpointX = null;
            TDViewpointY = null;
            TDViewpointZ = null;
            TDOriginX = null;
            TDOriginY = null;
            TDSkewAngle = null;
            TDSkewAmount = null;
            TDAmbientIntensity = null;
            TDKeyX = null;
            TDKeyY = null;
            TDKeyZ = null;
            TDKeyIntensity = null;
            TDFillX = null;
            TDFillY = null;
            TDFillZ = null;
            TDFillIntensity = null;
            TDConstrainRotation = null;
            TDRotationCenterAuto = null;
            TDParallel = null;
            TDKeyHarsh = null;
            TDFillHarsh = null;
            ConnectorType = null;
            BWMode = null;
            BWPure = null;
            BWNormal = null;
            DiagramNodeLayout = null;
            DiagramNodeKind = null;
            DiagramLayoutMRU = null;
            EquationXML = null;
            PolicyLabel = null;
            PolicyBarCode = null;
            FlipHQFE5152 = null;
            FlipVQFE5152 = null;
            OleIcon = null;
            PreferRelativeResize = null;
            LockShapeType = null;
            Initiator = null;
            DeleteAttachedObject = null;
            CalloutType = null;
            CalloutGap = null;
            CalloutAngle = null;
            CalloutDropType = null;
            CalloutDropDistance = null;
            CalloutLength = null;
            CalloutOn = null;
            CalloutAccentBar = null;
            CalloutTextBorder = null;
            CalloutMinusX = null;
            CalloutMinusY = null;
            CalloutDropAuto = null;
            CalloutLengthSpecified = null;
            ShapeName = null;
            ShapeDescription = null;
            ShapeTitle = null;
            HyperlinkAddress = null;
            WrapPolygonVertices = null;
            DistanceLeft = null;
            DistanceTop = null;
            DistanceRight = null;
            DistanceBottom = null;
            RegroupId = null;
            ScreenTip = null;
            ScriptText = null;
            HorizontalAlignment = null;
            RelativeHorizontalPosition = null;
            VerticalAlignment = null;
            RelativeVerticalPosition = null;
            HRPct = null;
            HRAlign = null;
            HRHeight = null;
            HRWidth = null;
            ScriptType = null;
            ScriptLanguage = null;
            ScriptIdAttr = null;
            ScriptLanguageName = null;
            BorderTopColor = null;
            BorderLeftColor = null;
            BorderBottomColor = null;
            BorderRightColor = null;
            MetroBlob = null;
            Dhgt = null;
            AllowInCell = null;
            PictureBullet = null;
            HRStandard = null;
            HRNoShade = null;
            HROn = null;
            UserDrawn = null;
            AllowOverlap = null;
            ReallyHidden = null;
            ScriptAnchor = null;
            EditedWrap = null;
            BehindText = null;
            OnDblClickNotify = null;
            Button = null;
            OneD = null;
            Hidden = null;
            Print = null;
            UnknownHtmlFlags = null;
            EditAs = null;
            DiagramStyle = null;
            Undocumented1282 = null;
            Undocumented1283 = null;
            DiagramRelationsTable = null;
            DiagramScaleX = null;
            DiagramScaleY = null;
            DiagramFontSize = null;
            DiagramConstrainBounds = null;
            DiagramBaseTextScale = null;
            DiagramAutoFormat = null;
            DiagramReverse = null;
            DiagramAutoLayout = null;
            PseudoInline = null;
            ClipVertices = null;
            ClipSegmentInfo = null;
            ClipShapePath = null;
            ClipToWrap = null;
            ClipOK = null;
            InkData = null;
            InkAnnotation = null;
            SigSetupId = null;
            SigSetupProvId = null;
            SigSetupSuggSigner = null;
            SigSetupSuggSigner2 = null;
            SigSetupSuggSignerEmail = null;
            SigSetupSignInst = null;
            SigSetupAddlXml = null;
            SigSetupProvUrl = null;
            SigSetupShowSignDate = null;
            SigSetupAllowComments = null;
            SigSetupSignInstSet = null;
            IsSignatureLine = null;
            LeftPercent = null;
            TopPercent = null;
            WidthPercent = null;
            HeightPercent = null;
            RelativeWidth = null;
            RelativeHeight = null;
            ColStart = null;
            ColSpan = null;
            Flip = null;
            WrapType = null;
            WrapSide = null;
            AnchorLocked = null;
            ImageBytes = null;
            ImageTitle = null;
            ImageSourceFullName = null;
            BorderTop = null;
            BorderLeft = null;
            BorderBottom = null;
            BorderRight = null;
            LineImageBytes = null;
            FillImageBytes = null;
            OleObject = null;
            OleProgID = null;
            OleSourceFullName = null;
            OleSourceItem = null;
            OleAutoUpdate = null;
            OleLocked = null;
            OleLinkType = null;
            OleFormatUpdateType = null;
            HyperlinkTarget = null;
            LineFillPresetTexture = null;
            FillPresetTexture = null;
            ShapeId = null;
            CoordOriginX = null;
            CoordOriginY = null;
            CoordSizeWidth = null;
            CoordSizeHeight = null;
            Left = null;
            Top = null;
            Width = null;
            Height = null;
            DmlLockArrowHeads = null;
            DmlLockResize = null;
            DmlLockDrillDown = null;
            DmlEffectExtentLeft = null;
            DmlEffectExtentTop = null;
            DmlEffectExtentRight = null;
            DmlEffectExtentBottom = null;
            ThemeColor = null;
            ThemeShade = null;
            ThemeTint = null;
            ZOrder = null;
            ShapeType = null;
            DocPrExtensions = null;
        }

        internal void Fill(ShapePr shapepr)
        {
            int count = shapepr.Count;
            for (int i = 0; i < count; i++)
            {
                int key = shapepr.GetKey(i);
                object value = shapepr.GetByIndex(i);
                switch (key)
                {
                    case ShapeAttr.TransformRotation:
                        TransformRotation = value;
                        break;
                    case ShapeAttr.LockAgainstUngrouping:
                        LockAgainstUngrouping = value;
                        break;
                    case ShapeAttr.LockRotation:
                        LockRotation = value;
                        break;
                    case ShapeAttr.LockAspectRatio:
                        LockAspectRatio = value;
                        break;
                    case ShapeAttr.LockPosition:
                        LockPosition = value;
                        break;
                    case ShapeAttr.LockAgainstSelect:
                        LockAgainstSelect = value;
                        break;
                    case ShapeAttr.LockCropping:
                        LockCropping = value;
                        break;
                    case ShapeAttr.LockVertices:
                        LockVertices = value;
                        break;
                    case ShapeAttr.LockText:
                        LockText = value;
                        break;
                    case ShapeAttr.LockAdjustHandles:
                        LockAdjustHandles = value;
                        break;
                    case ShapeAttr.LockAgainstGrouping:
                        LockAgainstGrouping = value;
                        break;
                    case ShapeAttr.TextboxTxid:
                        TextboxTxid = value;
                        break;
                    case ShapeAttr.TextboxLeft:
                        TextboxLeft = value;
                        break;
                    case ShapeAttr.TextboxTop:
                        TextboxTop = value;
                        break;
                    case ShapeAttr.TextboxRight:
                        TextboxRight = value;
                        break;
                    case ShapeAttr.TextboxBottom:
                        TextboxBottom = value;
                        break;
                    case ShapeAttr.TextboxWrapMode:
                        TextboxWrapMode = value;
                        break;
                    case ShapeAttr.TextboxZoom:
                        TextboxZoom = value;
                        break;
                    case ShapeAttr.TextboxAnchor:
                        TextboxAnchor = value;
                        break;
                    case ShapeAttr.TextboxLayoutFlow:
                        TextboxLayoutFlow = value;
                        break;
                    case ShapeAttr.TextboxFontRotation:
                        TextboxFontRotation = value;
                        break;
                    case ShapeAttr.TextboxNextShapeId:
                        TextboxNextShapeId = value;
                        break;
                    case ShapeAttr.TextDirection:
                        TextDirection = value;
                        break;
                    case ShapeAttr.TextboxColumns:
                        TextboxColumns = value;
                        break;
                    case ShapeAttr.TextboxColumnMargin:
                        TextboxColumnMargin = value;
                        break;
                    case ShapeAttr.Sys_TextboxNextShapeIdRaw:
                        TextboxNextShapeIdRaw = value;
                        break;
                    case ShapeAttr.TextboxSelectText:
                        TextboxSelectText = value;
                        break;
                    case ShapeAttr.TextboxAutoTextMargin:
                        TextboxAutoTextMargin = value;
                        break;
                    case ShapeAttr.TextboxRotateText:
                        TextboxRotateText = value;
                        break;
                    case ShapeAttr.TextboxFitShapeToText:
                        TextboxFitShapeToText = value;
                        break;
                    case ShapeAttr.TextboxFitTextToShape:
                        TextboxFitTextToShape = value;
                        break;
                    case ShapeAttr.GeoTextText:
                        GeoTextText = value;
                        break;
                    case ShapeAttr.GeoTextRtf:
                        GeoTextRtf = value;
                        break;
                    case ShapeAttr.GeoTextAlign:
                        GeoTextAlign = value;
                        break;
                    case ShapeAttr.GeoTextSize:
                        GeoTextSize = value;
                        break;
                    case ShapeAttr.GeoTextSpacing:
                        GeoTextSpacing = value;
                        break;
                    case ShapeAttr.GeoTextFont:
                        GeoTextFont = value;
                        break;
                    case ShapeAttr.GeoTextCssFont:
                        GeoTextCssFont = value;
                        break;
                    case ShapeAttr.GeoTextReverseRows:
                        GeoTextReverseRows = value;
                        break;
                    case ShapeAttr.GeoTextOn:
                        GeoTextOn = value;
                        break;
                    case ShapeAttr.GeoTextVertical:
                        GeoTextVertical = value;
                        break;
                    case ShapeAttr.GeoTextKerning:
                        GeoTextKerning = value;
                        break;
                    case ShapeAttr.GeoTextTight:
                        GeoTextTight = value;
                        break;
                    case ShapeAttr.GeoTextStretch:
                        GeoTextStretch = value;
                        break;
                    case ShapeAttr.GeoTextShrinkFit:
                        GeoTextShrinkFit = value;
                        break;
                    case ShapeAttr.GeoTextBestFit:
                        GeoTextBestFit = value;
                        break;
                    case ShapeAttr.GeoTextNormalize:
                        GeoTextNormalize = value;
                        break;
                    case ShapeAttr.GeoTextDxMeasure:
                        GeoTextDxMeasure = value;
                        break;
                    case ShapeAttr.GeoTextBold:
                        GeoTextBold = value;
                        break;
                    case ShapeAttr.GeoTextItalic:
                        GeoTextItalic = value;
                        break;
                    case ShapeAttr.GeoTextUnderline:
                        GeoTextUnderline = value;
                        break;
                    case ShapeAttr.GeoTextShadow:
                        GeoTextShadow = value;
                        break;
                    case ShapeAttr.GeoTextSmallCaps:
                        GeoTextSmallCaps = value;
                        break;
                    case ShapeAttr.GeoTextStrikeThrough:
                        GeoTextStrikeThrough = value;
                        break;
                    case ShapeAttr.ImageCropTop:
                        ImageCropTop = value;
                        break;
                    case ShapeAttr.ImageCropBottom:
                        ImageCropBottom = value;
                        break;
                    case ShapeAttr.ImageCropLeft:
                        ImageCropLeft = value;
                        break;
                    case ShapeAttr.ImageCropRight:
                        ImageCropRight = value;
                        break;
                    case ShapeAttr.GraphicFrameExtWidth:
                        GraphicFrameExtWidth = value;
                        break;
                    case ShapeAttr.GraphicFrameExtHeight:
                        GraphicFrameExtHeight = value;
                        break;
                    case ShapeAttr.ImageTransparent:
                        ImageTransparent = value;
                        break;
                    case ShapeAttr.ImageContrast:
                        ImageContrast = value;
                        break;
                    case ShapeAttr.ImageBrightness:
                        ImageBrightness = value;
                        break;
                    case ShapeAttr.ImageGamma:
                        ImageGamma = value;
                        break;
                    case ShapeAttr.OleTxid:
                        OleTxid = value;
                        break;
                    case ShapeAttr.ImageDblCrMod:
                        ImageDblCrMod = value;
                        break;
                    case ShapeAttr.ImageFillCrMod:
                        ImageFillCrMod = value;
                        break;
                    case ShapeAttr.ImageLineCrMod:
                        ImageLineCrMod = value;
                        break;
                    case ShapeAttr.ImageTransparentExt:
                        ImageTransparentExt = value;
                        break;
                    case ShapeAttr.ImageTransparentExtMod:
                        ImageTransparentExtMod = value;
                        break;
                    case ShapeAttr.ImageRecolor:
                        ImageRecolor = value;
                        break;
                    case ShapeAttr.ImageRecolorExt:
                        ImageRecolorExt = value;
                        break;
                    case ShapeAttr.Undocumented284:
                        Undocumented284 = value;
                        break;
                    case ShapeAttr.ImageRecolorExtCrMod:
                        ImageRecolorExtCrMod = value;
                        break;
                    case ShapeAttr.Undocumented286:
                        Undocumented286 = value;
                        break;
                    case ShapeAttr.Undocumented287:
                        Undocumented287 = value;
                        break;
                    case ShapeAttr.ImagePreserveGrays:
                        ImagePreserveGrays = value;
                        break;
                    case ShapeAttr.ImageNoHitTest:
                        ImageNoHitTest = value;
                        break;
                    case ShapeAttr.ImageGrayScale:
                        ImageGrayScale = value;
                        break;
                    case ShapeAttr.ImageBiLevel:
                        ImageBiLevel = value;
                        break;
                    case ShapeAttr.ImageActive:
                        ImageActive = value;
                        break;
                    case ShapeAttr.GeometryVertices:
                        GeometryVertices = value;
                        break;
                    case ShapeAttr.GeometrySegmentInfo:
                        GeometrySegmentInfo = value;
                        break;
                    case ShapeAttr.GeometryAdjust1:
                        GeometryAdjust1 = value;
                        break;
                    case ShapeAttr.GeometryAdjust2:
                        GeometryAdjust2 = value;
                        break;
                    case ShapeAttr.GeometryAdjust3:
                        GeometryAdjust3 = value;
                        break;
                    case ShapeAttr.GeometryAdjust4:
                        GeometryAdjust4 = value;
                        break;
                    case ShapeAttr.GeometryAdjust5:
                        GeometryAdjust5 = value;
                        break;
                    case ShapeAttr.GeometryAdjust6:
                        GeometryAdjust6 = value;
                        break;
                    case ShapeAttr.GeometryAdjust7:
                        GeometryAdjust7 = value;
                        break;
                    case ShapeAttr.GeometryAdjust8:
                        GeometryAdjust8 = value;
                        break;
                    case ShapeAttr.GeometryAdjust9:
                        GeometryAdjust9 = value;
                        break;
                    case ShapeAttr.GeometryAdjust10:
                        GeometryAdjust10 = value;
                        break;
                    case ShapeAttr.GeometryConnectLocs:
                        GeometryConnectLocs = value;
                        break;
                    case ShapeAttr.GeometryConnectAngles:
                        GeometryConnectAngles = value;
                        break;
                    case ShapeAttr.GeometryXLimo:
                        GeometryXLimo = value;
                        break;
                    case ShapeAttr.GeometryYLimo:
                        GeometryYLimo = value;
                        break;
                    case ShapeAttr.GeometryHandles:
                        GeometryHandles = value;
                        break;
                    case ShapeAttr.GeometryFormulas:
                        GeometryFormulas = value;
                        break;
                    case ShapeAttr.GeometryPathTextBoxRects:
                        GeometryPathTextBoxRects = value;
                        break;
                    case ShapeAttr.GeometryConnectionSiteType:
                        GeometryConnectionSiteType = value;
                        break;
                    case ShapeAttr.GeometryShadowOK:
                        GeometryShadowOK = value;
                        break;
                    case ShapeAttr.GeometryThreeDOK:
                        GeometryThreeDOK = value;
                        break;
                    case ShapeAttr.GeometryLineOK:
                        GeometryLineOK = value;
                        break;
                    case ShapeAttr.GeometryGTextOK:
                        GeometryGTextOK = value;
                        break;
                    case ShapeAttr.GeometryFillShadeShapeOK:
                        GeometryFillShadeShapeOK = value;
                        break;
                    case ShapeAttr.GeometryFillOK:
                        GeometryFillOK = value;
                        break;
                    case ShapeAttr.FillType:
                        FillType = value;
                        break;
                    case ShapeAttr.FillColor:
                        FillColor = value;
                        break;
                    case ShapeAttr.FillOpacity:
                        FillOpacity = value;
                        break;
                    case ShapeAttr.FillBackColor:
                        FillBackColor = value;
                        break;
                    case ShapeAttr.FillBackOpacity:
                        FillBackOpacity = value;
                        break;
                    case ShapeAttr.FillCrMod:
                        FillCrMod = value;
                        break;
                    case ShapeAttr.FillBlipName:
                        FillBlipName = value;
                        break;
                    case ShapeAttr.FillBlipNameFlags:
                        FillBlipNameFlags = value;
                        break;
                    case ShapeAttr.FillWidth:
                        FillWidth = value;
                        break;
                    case ShapeAttr.FillHeight:
                        FillHeight = value;
                        break;
                    case ShapeAttr.FillAngle:
                        FillAngle = value;
                        break;
                    case ShapeAttr.FillFocus:
                        FillFocus = value;
                        break;
                    case ShapeAttr.FillToLeft:
                        FillToLeft = value;
                        break;
                    case ShapeAttr.FillToTop:
                        FillToTop = value;
                        break;
                    case ShapeAttr.FillToRight:
                        FillToRight = value;
                        break;
                    case ShapeAttr.FillToBottom:
                        FillToBottom = value;
                        break;
                    case ShapeAttr.FillRectLeft:
                        FillRectLeft = value;
                        break;
                    case ShapeAttr.FillRectTop:
                        FillRectTop = value;
                        break;
                    case ShapeAttr.FillRectRight:
                        FillRectRight = value;
                        break;
                    case ShapeAttr.FillRectBottom:
                        FillRectBottom = value;
                        break;
                    case ShapeAttr.FillDimensionType:
                        FillDimensionType = value;
                        break;
                    case ShapeAttr.FillShadePreset:
                        FillShadePreset = value;
                        break;
                    case ShapeAttr.FillShadeColors:
                        FillShadeColors = value;
                        break;
                    case ShapeAttr.FillOriginX:
                        FillOriginX = value;
                        break;
                    case ShapeAttr.FillOriginY:
                        FillOriginY = value;
                        break;
                    case ShapeAttr.FillShapeOriginX:
                        FillShapeOriginX = value;
                        break;
                    case ShapeAttr.FillShapeOriginY:
                        FillShapeOriginY = value;
                        break;
                    case ShapeAttr.FillShadeType:
                        FillShadeType = value;
                        break;
                    case ShapeAttr.FillColorExt:
                        FillColorExt = value;
                        break;
                    case ShapeAttr.FillColorExtCMY:
                        FillColorExtCMY = value;
                        break;
                    case ShapeAttr.FillColorExtMod:
                        FillColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented417:
                        Undocumented417 = value;
                        break;
                    case ShapeAttr.FillBackColorExt:
                        FillBackColorExt = value;
                        break;
                    case ShapeAttr.FillBackColorExtCMY:
                        FillBackColorExtCMY = value;
                        break;
                    case ShapeAttr.FillBackColorExtMod:
                        FillBackColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented421:
                        Undocumented421 = value;
                        break;
                    case ShapeAttr.FillColorExtK:
                        FillColorExtK = value;
                        break;
                    case ShapeAttr.FillBackColorExtK:
                        FillBackColorExtK = value;
                        break;
                    case ShapeAttr.FillRecolorAsPicture:
                        FillRecolorAsPicture = value;
                        break;
                    case ShapeAttr.FillUseShapeAnchor:
                        FillUseShapeAnchor = value;
                        break;
                    case ShapeAttr.Filled:
                        Filled = value;
                        break;
                    case ShapeAttr.FillHitTest:
                        FillHitTest = value;
                        break;
                    case ShapeAttr.FillShape:
                        FillShape = value;
                        break;
                    case ShapeAttr.FillUseRect:
                        FillUseRect = value;
                        break;
                    case ShapeAttr.FillNoFillHitTest:
                        FillNoFillHitTest = value;
                        break;
                    case ShapeAttr.LineColor:
                        LineColor = value;
                        break;
                    case ShapeAttr.LineOpacity:
                        LineOpacity = value;
                        break;
                    case ShapeAttr.LineBackColor:
                        LineBackColor = value;
                        break;
                    case ShapeAttr.LineCrMod:
                        LineCrMod = value;
                        break;
                    case ShapeAttr.LineFillType:
                        LineFillType = value;
                        break;
                    case ShapeAttr.LineFillBlipName:
                        LineFillBlipName = value;
                        break;
                    case ShapeAttr.LineFillBlipNameFlags:
                        LineFillBlipNameFlags = value;
                        break;
                    case ShapeAttr.LineFillWidth:
                        LineFillWidth = value;
                        break;
                    case ShapeAttr.LineFillHeight:
                        LineFillHeight = value;
                        break;
                    case ShapeAttr.LineFillDimensionType:
                        LineFillDimensionType = value;
                        break;
                    case ShapeAttr.LineWidth:
                        LineWidth = value;
                        break;
                    case ShapeAttr.LineMiterLimit:
                        LineMiterLimit = value;
                        break;
                    case ShapeAttr.LineStyle:
                        LineStyle = value;
                        break;
                    case ShapeAttr.LineDashStyle:
                        LineDashStyle = value;
                        break;
                    case ShapeAttr.LineDashData:
                        LineDashData = value;
                        break;
                    case ShapeAttr.LineStartArrow:
                        LineStartArrow = value;
                        break;
                    case ShapeAttr.LineEndArrow:
                        LineEndArrow = value;
                        break;
                    case ShapeAttr.LineStartArrowWidth:
                        LineStartArrowWidth = value;
                        break;
                    case ShapeAttr.LineStartArrowLength:
                        LineStartArrowLength = value;
                        break;
                    case ShapeAttr.LineEndArrowWidth:
                        LineEndArrowWidth = value;
                        break;
                    case ShapeAttr.LineEndArrowLength:
                        LineEndArrowLength = value;
                        break;
                    case ShapeAttr.LineJoinStyle:
                        LineJoinStyle = value;
                        break;
                    case ShapeAttr.LineEndCapStyle:
                        LineEndCapStyle = value;
                        break;
                    case ShapeAttr.LineColorExt:
                        LineColorExt = value;
                        break;
                    case ShapeAttr.LineColorExtCMY:
                        LineColorExtCMY = value;
                        break;
                    case ShapeAttr.LineColorExtMod:
                        LineColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented476:
                        Undocumented476 = value;
                        break;
                    case ShapeAttr.LineBackColorExt:
                        LineBackColorExt = value;
                        break;
                    case ShapeAttr.LineBackColorExtCMY:
                        LineBackColorExtCMY = value;
                        break;
                    case ShapeAttr.LineBackColorExtMod:
                        LineBackColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented480:
                        Undocumented480 = value;
                        break;
                    case ShapeAttr.LineColorExtK:
                        LineColorExtK = value;
                        break;
                    case ShapeAttr.LineBackColorExtK:
                        LineBackColorExtK = value;
                        break;
                    case ShapeAttr.LineRecolorFillAsPicture:
                        LineRecolorFillAsPicture = value;
                        break;
                    case ShapeAttr.LineUseShapeAnchor:
                        LineUseShapeAnchor = value;
                        break;
                    case ShapeAttr.LineInsetPen:
                        LineInsetPen = value;
                        break;
                    case ShapeAttr.LineInsetPenOk:
                        LineInsetPenOk = value;
                        break;
                    case ShapeAttr.LineArrowHeadsOK:
                        LineArrowHeadsOK = value;
                        break;
                    case ShapeAttr.LineOn:
                        LineOn = value;
                        break;
                    case ShapeAttr.LineHitTest:
                        LineHitTest = value;
                        break;
                    case ShapeAttr.LineFillShape:
                        LineFillShape = value;
                        break;
                    case ShapeAttr.LineNoLineDrawDash:
                        LineNoLineDrawDash = value;
                        break;
                    case ShapeAttr.ShadowType:
                        ShadowType = value;
                        break;
                    case ShapeAttr.ShadowColor:
                        ShadowColor = value;
                        break;
                    case ShapeAttr.ShadowHighlight:
                        ShadowHighlight = value;
                        break;
                    case ShapeAttr.ShadowCrMod:
                        ShadowCrMod = value;
                        break;
                    case ShapeAttr.ShadowOpacity:
                        ShadowOpacity = value;
                        break;
                    case ShapeAttr.ShadowOffsetX:
                        ShadowOffsetX = value;
                        break;
                    case ShapeAttr.ShadowOffsetY:
                        ShadowOffsetY = value;
                        break;
                    case ShapeAttr.ShadowSecondOffsetX:
                        ShadowSecondOffsetX = value;
                        break;
                    case ShapeAttr.ShadowSecondOffsetY:
                        ShadowSecondOffsetY = value;
                        break;
                    case ShapeAttr.ShadowScaleXtoX:
                        ShadowScaleXtoX = value;
                        break;
                    case ShapeAttr.ShadowScaleYtoX:
                        ShadowScaleYtoX = value;
                        break;
                    case ShapeAttr.ShadowScaleXtoY:
                        ShadowScaleXtoY = value;
                        break;
                    case ShapeAttr.ShadowScaleYtoY:
                        ShadowScaleYtoY = value;
                        break;
                    case ShapeAttr.ShadowPerspectiveX:
                        ShadowPerspectiveX = value;
                        break;
                    case ShapeAttr.ShadowPerspectiveY:
                        ShadowPerspectiveY = value;
                        break;
                    case ShapeAttr.ShadowWeight:
                        ShadowWeight = value;
                        break;
                    case ShapeAttr.ShadowOriginX:
                        ShadowOriginX = value;
                        break;
                    case ShapeAttr.ShadowOriginY:
                        ShadowOriginY = value;
                        break;
                    case ShapeAttr.ShadowColorExt:
                        ShadowColorExt = value;
                        break;
                    case ShapeAttr.ShadowColorExtCMY:
                        ShadowColorExtCMY = value;
                        break;
                    case ShapeAttr.ShadowColorExtMod:
                        ShadowColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented533:
                        Undocumented533 = value;
                        break;
                    case ShapeAttr.ShadowHighlightExt:
                        ShadowHighlightExt = value;
                        break;
                    case ShapeAttr.ShadowHighlightExtCMY:
                        ShadowHighlightExtCMY = value;
                        break;
                    case ShapeAttr.ShadowHighlightExtMod:
                        ShadowHighlightExtMod = value;
                        break;
                    case ShapeAttr.Undocumented537:
                        Undocumented537 = value;
                        break;
                    case ShapeAttr.ShadowColorExtK:
                        ShadowColorExtK = value;
                        break;
                    case ShapeAttr.ShadowHighlightExtK:
                        ShadowHighlightExtK = value;
                        break;
                    case ShapeAttr.ShadowOn:
                        ShadowOn = value;
                        break;
                    case ShapeAttr.ShadowObscured:
                        ShadowObscured = value;
                        break;
                    case ShapeAttr.PerspectiveType:
                        PerspectiveType = value;
                        break;
                    case ShapeAttr.PerspectiveOffsetX:
                        PerspectiveOffsetX = value;
                        break;
                    case ShapeAttr.PerspectiveOffsetY:
                        PerspectiveOffsetY = value;
                        break;
                    case ShapeAttr.PerspectiveScaleXToX:
                        PerspectiveScaleXToX = value;
                        break;
                    case ShapeAttr.PerspectiveScaleYToX:
                        PerspectiveScaleYToX = value;
                        break;
                    case ShapeAttr.PerspectiveScaleXToY:
                        PerspectiveScaleXToY = value;
                        break;
                    case ShapeAttr.PerspectiveScaleYToY:
                        PerspectiveScaleYToY = value;
                        break;
                    case ShapeAttr.PerspectiveX:
                        PerspectiveX = value;
                        break;
                    case ShapeAttr.PerspectiveY:
                        PerspectiveY = value;
                        break;
                    case ShapeAttr.PerspectiveWeight:
                        PerspectiveWeight = value;
                        break;
                    case ShapeAttr.PerspectiveOriginX:
                        PerspectiveOriginX = value;
                        break;
                    case ShapeAttr.PerspectiveOriginY:
                        PerspectiveOriginY = value;
                        break;
                    case ShapeAttr.PerspectiveOn:
                        PerspectiveOn = value;
                        break;
                    case ShapeAttr.TDSpecularAmount:
                        TDSpecularAmount = value;
                        break;
                    case ShapeAttr.TDDiffuseAmount:
                        TDDiffuseAmount = value;
                        break;
                    case ShapeAttr.TDShininess:
                        TDShininess = value;
                        break;
                    case ShapeAttr.TDEdgeThickness:
                        TDEdgeThickness = value;
                        break;
                    case ShapeAttr.TDExtrudeForward:
                        TDExtrudeForward = value;
                        break;
                    case ShapeAttr.TDExtrudeBackward:
                        TDExtrudeBackward = value;
                        break;
                    case ShapeAttr.TDExtrudePlane:
                        TDExtrudePlane = value;
                        break;
                    case ShapeAttr.TDExtrusionColor:
                        TDExtrusionColor = value;
                        break;
                    case ShapeAttr.TDCrMod:
                        TDCrMod = value;
                        break;
                    case ShapeAttr.TDExtrusionColorExt:
                        TDExtrusionColorExt = value;
                        break;
                    case ShapeAttr.TDExtrusionColorExtCMY:
                        TDExtrusionColorExtCMY = value;
                        break;
                    case ShapeAttr.TDExtrusionColorExtMod:
                        TDExtrusionColorExtMod = value;
                        break;
                    case ShapeAttr.Undocumented652:
                        Undocumented652 = value;
                        break;
                    case ShapeAttr.TDExtrusionColorExtK:
                        TDExtrusionColorExtK = value;
                        break;
                    case ShapeAttr.Undocumented663:
                        Undocumented663 = value;
                        break;
                    case ShapeAttr.Undocumented666:
                        Undocumented666 = value;
                        break;
                    case ShapeAttr.TDOn:
                        TDOn = value;
                        break;
                    case ShapeAttr.TDMetallic:
                        TDMetallic = value;
                        break;
                    case ShapeAttr.TDUseExtrusionColor:
                        TDUseExtrusionColor = value;
                        break;
                    case ShapeAttr.TDLightFace:
                        TDLightFace = value;
                        break;
                    case ShapeAttr.TDRotationAngleY:
                        TDRotationAngleY = value;
                        break;
                    case ShapeAttr.TDRotationAngleX:
                        TDRotationAngleX = value;
                        break;
                    case ShapeAttr.TDRotationAxisX:
                        TDRotationAxisX = value;
                        break;
                    case ShapeAttr.TDRotationAxisY:
                        TDRotationAxisY = value;
                        break;
                    case ShapeAttr.TDRotationAxisZ:
                        TDRotationAxisZ = value;
                        break;
                    case ShapeAttr.TDRotationAngle:
                        TDRotationAngle = value;
                        break;
                    case ShapeAttr.TDRotationCenterX:
                        TDRotationCenterX = value;
                        break;
                    case ShapeAttr.TDRotationCenterY:
                        TDRotationCenterY = value;
                        break;
                    case ShapeAttr.TDRotationCenterZ:
                        TDRotationCenterZ = value;
                        break;
                    case ShapeAttr.TDRenderMode:
                        TDRenderMode = value;
                        break;
                    case ShapeAttr.TDTolerance:
                        TDTolerance = value;
                        break;
                    case ShapeAttr.TDViewpointX:
                        TDViewpointX = value;
                        break;
                    case ShapeAttr.TDViewpointY:
                        TDViewpointY = value;
                        break;
                    case ShapeAttr.TDViewpointZ:
                        TDViewpointZ = value;
                        break;
                    case ShapeAttr.TDOriginX:
                        TDOriginX = value;
                        break;
                    case ShapeAttr.TDOriginY:
                        TDOriginY = value;
                        break;
                    case ShapeAttr.TDSkewAngle:
                        TDSkewAngle = value;
                        break;
                    case ShapeAttr.TDSkewAmount:
                        TDSkewAmount = value;
                        break;
                    case ShapeAttr.TDAmbientIntensity:
                        TDAmbientIntensity = value;
                        break;
                    case ShapeAttr.TDKeyX:
                        TDKeyX = value;
                        break;
                    case ShapeAttr.TDKeyY:
                        TDKeyY = value;
                        break;
                    case ShapeAttr.TDKeyZ:
                        TDKeyZ = value;
                        break;
                    case ShapeAttr.TDKeyIntensity:
                        TDKeyIntensity = value;
                        break;
                    case ShapeAttr.TDFillX:
                        TDFillX = value;
                        break;
                    case ShapeAttr.TDFillY:
                        TDFillY = value;
                        break;
                    case ShapeAttr.TDFillZ:
                        TDFillZ = value;
                        break;
                    case ShapeAttr.TDFillIntensity:
                        TDFillIntensity = value;
                        break;
                    case ShapeAttr.TDConstrainRotation:
                        TDConstrainRotation = value;
                        break;
                    case ShapeAttr.TDRotationCenterAuto:
                        TDRotationCenterAuto = value;
                        break;
                    case ShapeAttr.TDParallel:
                        TDParallel = value;
                        break;
                    case ShapeAttr.TDKeyHarsh:
                        TDKeyHarsh = value;
                        break;
                    case ShapeAttr.TDFillHarsh:
                        TDFillHarsh = value;
                        break;
                    case ShapeAttr.ConnectorType:
                        ConnectorType = value;
                        break;
                    case ShapeAttr.BWMode:
                        BWMode = value;
                        break;
                    case ShapeAttr.BWPure:
                        BWPure = value;
                        break;
                    case ShapeAttr.BWNormal:
                        BWNormal = value;
                        break;
                    case ShapeAttr.DiagramNodeLayout:
                        DiagramNodeLayout = value;
                        break;
                    case ShapeAttr.DiagramNodeKind:
                        DiagramNodeKind = value;
                        break;
                    case ShapeAttr.DiagramLayoutMRU:
                        DiagramLayoutMRU = value;
                        break;
                    case ShapeAttr.EquationXML:
                        EquationXML = value;
                        break;
                    case ShapeAttr.PolicyLabel:
                        PolicyLabel = value;
                        break;
                    case ShapeAttr.PolicyBarCode:
                        PolicyBarCode = value;
                        break;
                    case ShapeAttr.FlipHQFE5152:
                        FlipHQFE5152 = value;
                        break;
                    case ShapeAttr.FlipVQFE5152:
                        FlipVQFE5152 = value;
                        break;
                    case ShapeAttr.OleIcon:
                        OleIcon = value;
                        break;
                    case ShapeAttr.PreferRelativeResize:
                        PreferRelativeResize = value;
                        break;
                    case ShapeAttr.LockShapeType:
                        LockShapeType = value;
                        break;
                    case ShapeAttr.Initiator:
                        Initiator = value;
                        break;
                    case ShapeAttr.DeleteAttachedObject:
                        DeleteAttachedObject = value;
                        break;
                    case ShapeAttr.CalloutType:
                        CalloutType = value;
                        break;
                    case ShapeAttr.CalloutGap:
                        CalloutGap = value;
                        break;
                    case ShapeAttr.CalloutAngle:
                        CalloutAngle = value;
                        break;
                    case ShapeAttr.CalloutDropType:
                        CalloutDropType = value;
                        break;
                    case ShapeAttr.CalloutDropDistance:
                        CalloutDropDistance = value;
                        break;
                    case ShapeAttr.CalloutLength:
                        CalloutLength = value;
                        break;
                    case ShapeAttr.CalloutOn:
                        CalloutOn = value;
                        break;
                    case ShapeAttr.CalloutAccentBar:
                        CalloutAccentBar = value;
                        break;
                    case ShapeAttr.CalloutTextBorder:
                        CalloutTextBorder = value;
                        break;
                    case ShapeAttr.CalloutMinusX:
                        CalloutMinusX = value;
                        break;
                    case ShapeAttr.CalloutMinusY:
                        CalloutMinusY = value;
                        break;
                    case ShapeAttr.CalloutDropAuto:
                        CalloutDropAuto = value;
                        break;
                    case ShapeAttr.CalloutLengthSpecified:
                        CalloutLengthSpecified = value;
                        break;
                    case ShapeAttr.ShapeName:
                        ShapeName = value;
                        break;
                    case ShapeAttr.ShapeDescription:
                        ShapeDescription = value;
                        break;
                    case ShapeAttr.ShapeTitle:
                        ShapeTitle = value;
                        break;
                    case ShapeAttr.HyperlinkAddress:
                        HyperlinkAddress = value;
                        break;
                    case ShapeAttr.WrapPolygonVertices:
                        WrapPolygonVertices = value;
                        break;
                    case ShapeAttr.DistanceLeft:
                        DistanceLeft = value;
                        break;
                    case ShapeAttr.DistanceTop:
                        DistanceTop = value;
                        break;
                    case ShapeAttr.DistanceRight:
                        DistanceRight = value;
                        break;
                    case ShapeAttr.DistanceBottom:
                        DistanceBottom = value;
                        break;
                    case ShapeAttr.RegroupId:
                        RegroupId = value;
                        break;
                    case ShapeAttr.ScreenTip:
                        ScreenTip = value;
                        break;
                    case ShapeAttr.ScriptText:
                        ScriptText = value;
                        break;
                    case ShapeAttr.HorizontalAlignment:
                        HorizontalAlignment = value;
                        break;
                    case ShapeAttr.RelativeHorizontalPosition:
                        RelativeHorizontalPosition = value;
                        break;
                    case ShapeAttr.VerticalAlignment:
                        VerticalAlignment = value;
                        break;
                    case ShapeAttr.RelativeVerticalPosition:
                        RelativeVerticalPosition = value;
                        break;
                    case ShapeAttr.HRPct:
                        HRPct = value;
                        break;
                    case ShapeAttr.HRAlign:
                        HRAlign = value;
                        break;
                    case ShapeAttr.HRHeight:
                        HRHeight = value;
                        break;
                    case ShapeAttr.HRWidth:
                        HRWidth = value;
                        break;
                    case ShapeAttr.ScriptType:
                        ScriptType = value;
                        break;
                    case ShapeAttr.ScriptLanguage:
                        ScriptLanguage = value;
                        break;
                    case ShapeAttr.ScriptIdAttr:
                        ScriptIdAttr = value;
                        break;
                    case ShapeAttr.ScriptLanguageName:
                        ScriptLanguageName = value;
                        break;
                    case ShapeAttr.BorderTopColor:
                        BorderTopColor = value;
                        break;
                    case ShapeAttr.BorderLeftColor:
                        BorderLeftColor = value;
                        break;
                    case ShapeAttr.BorderBottomColor:
                        BorderBottomColor = value;
                        break;
                    case ShapeAttr.BorderRightColor:
                        BorderRightColor = value;
                        break;
                    case ShapeAttr.MetroBlob:
                        MetroBlob = value;
                        break;
                    case ShapeAttr.Dhgt:
                        Dhgt = value;
                        break;
                    case ShapeAttr.AllowInCell:
                        AllowInCell = value;
                        break;
                    case ShapeAttr.PictureBullet:
                        PictureBullet = value;
                        break;
                    case ShapeAttr.HRStandard:
                        HRStandard = value;
                        break;
                    case ShapeAttr.HRNoShade:
                        HRNoShade = value;
                        break;
                    case ShapeAttr.HROn:
                        HROn = value;
                        break;
                    case ShapeAttr.UserDrawn:
                        UserDrawn = value;
                        break;
                    case ShapeAttr.AllowOverlap:
                        AllowOverlap = value;
                        break;
                    case ShapeAttr.ReallyHidden:
                        ReallyHidden = value;
                        break;
                    case ShapeAttr.ScriptAnchor:
                        ScriptAnchor = value;
                        break;
                    case ShapeAttr.EditedWrap:
                        EditedWrap = value;
                        break;
                    case ShapeAttr.BehindText:
                        BehindText = value;
                        break;
                    case ShapeAttr.OnDblClickNotify:
                        OnDblClickNotify = value;
                        break;
                    case ShapeAttr.Button:
                        Button = value;
                        break;
                    case ShapeAttr.OneD:
                        OneD = value;
                        break;
                    case ShapeAttr.Hidden:
                        Hidden = value;
                        break;
                    case ShapeAttr.Print:
                        Print = value;
                        break;
                    case ShapeAttr.UnknownHtmlFlags:
                        UnknownHtmlFlags = value;
                        break;
                    case ShapeAttr.EditAs:
                        EditAs = value;
                        break;
                    case ShapeAttr.DiagramStyle:
                        DiagramStyle = value;
                        break;
                    case ShapeAttr.Undocumented1282:
                        Undocumented1282 = value;
                        break;
                    case ShapeAttr.Undocumented1283:
                        Undocumented1283 = value;
                        break;
                    case ShapeAttr.DiagramRelationsTable:
                        DiagramRelationsTable = value;
                        break;
                    case ShapeAttr.DiagramScaleX:
                        DiagramScaleX = value;
                        break;
                    case ShapeAttr.DiagramScaleY:
                        DiagramScaleY = value;
                        break;
                    case ShapeAttr.DiagramFontSize:
                        DiagramFontSize = value;
                        break;
                    case ShapeAttr.DiagramConstrainBounds:
                        DiagramConstrainBounds = value;
                        break;
                    case ShapeAttr.DiagramBaseTextScale:
                        DiagramBaseTextScale = value;
                        break;
                    case ShapeAttr.DiagramAutoFormat:
                        DiagramAutoFormat = value;
                        break;
                    case ShapeAttr.DiagramReverse:
                        DiagramReverse = value;
                        break;
                    case ShapeAttr.DiagramAutoLayout:
                        DiagramAutoLayout = value;
                        break;
                    case ShapeAttr.PseudoInline:
                        PseudoInline = value;
                        break;
                    case ShapeAttr.ClipVertices:
                        ClipVertices = value;
                        break;
                    case ShapeAttr.ClipSegmentInfo:
                        ClipSegmentInfo = value;
                        break;
                    case ShapeAttr.ClipShapePath:
                        ClipShapePath = value;
                        break;
                    case ShapeAttr.ClipToWrap:
                        ClipToWrap = value;
                        break;
                    case ShapeAttr.ClipOK:
                        ClipOK = value;
                        break;
                    case ShapeAttr.InkData:
                        InkData = value;
                        break;
                    case ShapeAttr.InkAnnotation:
                        InkAnnotation = value;
                        break;
                    case ShapeAttr.SigSetupId:
                        SigSetupId = value;
                        break;
                    case ShapeAttr.SigSetupProvId:
                        SigSetupProvId = value;
                        break;
                    case ShapeAttr.SigSetupSuggSigner:
                        SigSetupSuggSigner = value;
                        break;
                    case ShapeAttr.SigSetupSuggSigner2:
                        SigSetupSuggSigner2 = value;
                        break;
                    case ShapeAttr.SigSetupSuggSignerEmail:
                        SigSetupSuggSignerEmail = value;
                        break;
                    case ShapeAttr.SigSetupSignInst:
                        SigSetupSignInst = value;
                        break;
                    case ShapeAttr.SigSetupAddlXml:
                        SigSetupAddlXml = value;
                        break;
                    case ShapeAttr.SigSetupProvUrl:
                        SigSetupProvUrl = value;
                        break;
                    case ShapeAttr.SigSetupShowSignDate:
                        SigSetupShowSignDate = value;
                        break;
                    case ShapeAttr.SigSetupAllowComments:
                        SigSetupAllowComments = value;
                        break;
                    case ShapeAttr.SigSetupSignInstSet:
                        SigSetupSignInstSet = value;
                        break;
                    case ShapeAttr.IsSignatureLine:
                        IsSignatureLine = value;
                        break;
                    case ShapeAttr.LeftPercent:
                        LeftPercent = value;
                        break;
                    case ShapeAttr.TopPercent:
                        TopPercent = value;
                        break;
                    case ShapeAttr.WidthPercent:
                        WidthPercent = value;
                        break;
                    case ShapeAttr.HeightPercent:
                        HeightPercent = value;
                        break;
                    case ShapeAttr.RelativeWidth:
                        RelativeWidth = value;
                        break;
                    case ShapeAttr.RelativeHeight:
                        RelativeHeight = value;
                        break;
                    case ShapeAttr.ColStart:
                        ColStart = value;
                        break;
                    case ShapeAttr.ColSpan:
                        ColSpan = value;
                        break;
                    case ShapeAttr.Flip:
                        Flip = value;
                        break;
                    case ShapeAttr.WrapType:
                        WrapType = value;
                        break;
                    case ShapeAttr.WrapSide:
                        WrapSide = value;
                        break;
                    case ShapeAttr.AnchorLocked:
                        AnchorLocked = value;
                        break;
                    case ShapeAttr.ImageBytes:
                        ImageBytes = value;
                        break;
                    case ShapeAttr.ImageTitle:
                        ImageTitle = value;
                        break;
                    case ShapeAttr.ImageSourceFullName:
                        ImageSourceFullName = value;
                        break;
                    case ShapeAttr.BorderTop:
                        BorderTop = value;
                        break;
                    case ShapeAttr.BorderLeft:
                        BorderLeft = value;
                        break;
                    case ShapeAttr.BorderBottom:
                        BorderBottom = value;
                        break;
                    case ShapeAttr.BorderRight:
                        BorderRight = value;
                        break;
                    case ShapeAttr.LineImageBytes:
                        LineImageBytes = value;
                        break;
                    case ShapeAttr.FillImageBytes:
                        FillImageBytes = value;
                        break;
                    case ShapeAttr.OleObject:
                        OleObject = value;
                        break;
                    case ShapeAttr.OleProgID:
                        OleProgID = value;
                        break;
                    case ShapeAttr.OleSourceFullName:
                        OleSourceFullName = value;
                        break;
                    case ShapeAttr.OleSourceItem:
                        OleSourceItem = value;
                        break;
                    case ShapeAttr.OleAutoUpdate:
                        OleAutoUpdate = value;
                        break;
                    case ShapeAttr.OleLocked:
                        OleLocked = value;
                        break;
                    case ShapeAttr.OleLinkType:
                        OleLinkType = value;
                        break;
                    case ShapeAttr.OleFormatUpdateType:
                        OleFormatUpdateType = value;
                        break;
                    case ShapeAttr.HyperlinkTarget:
                        HyperlinkTarget = value;
                        break;
                    case ShapeAttr.LineFillPresetTexture:
                        LineFillPresetTexture = value;
                        break;
                    case ShapeAttr.FillPresetTexture:
                        FillPresetTexture = value;
                        break;
                    case ShapeAttr.ShapeId:
                        ShapeId = value;
                        break;
                    case ShapeAttr.CoordOriginX:
                        CoordOriginX = value;
                        break;
                    case ShapeAttr.CoordOriginY:
                        CoordOriginY = value;
                        break;
                    case ShapeAttr.CoordSizeWidth:
                        CoordSizeWidth = value;
                        break;
                    case ShapeAttr.CoordSizeHeight:
                        CoordSizeHeight = value;
                        break;
                    case ShapeAttr.Left:
                        Left = value;
                        break;
                    case ShapeAttr.Top:
                        Top = value;
                        break;
                    case ShapeAttr.Width:
                        Width = value;
                        break;
                    case ShapeAttr.Height:
                        Height = value;
                        break;
                    case ShapeAttr.DmlLockArrowHeads:
                        DmlLockArrowHeads = value;
                        break;
                    case ShapeAttr.DmlLockResize:
                        DmlLockResize = value;
                        break;
                    case ShapeAttr.DmlLockDrillDown:
                        DmlLockDrillDown = value;
                        break;
                    case ShapeAttr.DmlEffectExtentLeft:
                        DmlEffectExtentLeft = value;
                        break;
                    case ShapeAttr.DmlEffectExtentTop:
                        DmlEffectExtentTop = value;
                        break;
                    case ShapeAttr.DmlEffectExtentRight:
                        DmlEffectExtentRight = value;
                        break;
                    case ShapeAttr.DmlEffectExtentBottom:
                        DmlEffectExtentBottom = value;
                        break;
                    case ShapeAttr.ThemeColor:
                        ThemeColor = value;
                        break;
                    case ShapeAttr.ThemeShade:
                        ThemeShade = value;
                        break;
                    case ShapeAttr.ThemeTint:
                        ThemeTint = value;
                        break;
                    case ShapeAttr.ZOrder:
                        ZOrder = value;
                        break;
                    case ShapeAttr.ShapeType:
                        ShapeType = value;
                        break;
                    // WORDSNET-16589 Skip readonly attribute.
                    case ShapeAttr.GfxData:
                        break;
                    case ShapeAttr.ConnectorRule:
                        // Ignore this for a while.
                        break;

                    default:
                        Debug.Fail("Unknown attribute.");
                        break;
                }
            }
        }
    }
}
