// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 26/07/2006 by Roman Korchagin

using CodePorting.Translator.Cs2Cpp;

namespace Aspose.Words.Drawing.Core
{
    /// <summary>
    /// It is possible to group shape attributes into categories based on their id.
    /// </summary>
    [CppConstexpr]
    internal static class ShapeAttrCategory
    {
        internal const int CategoryMask = unchecked((int)0xffffffc0);

        /// <summary>
        /// 0x0000 - 0x003f
        /// </summary>
        internal const int Transform = 0x0000;
        /// <summary>
        /// 0x0040 - 0x007f
        /// </summary>
        internal const int Protection = 0x0040;
        /// <summary>
        /// 0x0080 - 0x00bf
        /// </summary>
        internal const int Text = 0x0080;
        /// <summary>
        /// 0x00c0 - 0x00ff
        /// </summary>
        internal const int GeoText = 0x00c0;
        /// <summary>
        /// 0x0100 - 0x013f
        /// </summary>
        internal const int Blip = 0x0100;
        /// <summary>
        /// 0x0140 - 0x017f
        /// </summary>
        internal const int Geometry = 0x0140;
        /// <summary>
        /// 0x0180 - 0x01bf
        /// </summary>
        internal const int Fill = 0x0180;
        /// <summary>
        /// 0x01c0 - 0x01ff
        /// </summary>
        internal const int Line = 0x01c0;
        /// <summary>
        /// 0x0200 - 0x023f
        /// </summary>
        internal const int Shadow = 0x0200;
        /// <summary>
        /// 0x0240 - 0x027f
        /// </summary>
        internal const int Perspective = 0x0240;
        /// <summary>
        /// 0x0280 - 0x02bf
        /// </summary>
        internal const int ThreeDObject = 0x0280;
        /// <summary>
        /// 0x02c0 - 0x03ff
        /// </summary>
        internal const int ThreeDStyle = 0x02c0;
        /// <summary>
        /// 0x0300 - 0x033f
        /// </summary>
        internal const int Shape = 0x0300;
        /// <summary>
        /// 0x0340 - 0x037f
        /// </summary>
        internal const int Callout = 0x0340;
        /// <summary>
        /// 0x0380 - 0x03bf
        /// </summary>
        internal const int GroupShape = 0x0380;
        /// <summary>
        /// 0x0400 - 0x043f
        /// </summary>
        internal const int Undocumented400 = 0x0400;
        /// <summary>
        /// 0x0500 - 0x053f
        /// </summary>
        internal const int Diagram = 0x0500;
        /// <summary>
        /// 0x0540 - 0x057f
        /// This category has same attributes as <see cref="Line"/>, but they are for the left line of the stroke.
        /// </summary>
        internal const int LineLeft = 0x0540;
        /// <summary>
        /// 0x0580 - 0x05bf
        /// This category has same attributes as <see cref="Line"/>, but they are for the top line of the stroke.
        /// </summary>
        internal const int LineTop = 0x0580;
        /// <summary>
        /// 0x05c0 - 0x05ff
        /// This category has same attributes as <see cref="Line"/>, but they are for the right line of the stroke.
        /// </summary>
        internal const int LineRight = 0x05c0;
        /// <summary>
        /// 0x0600 - 0x063f
        /// This category has same attributes as <see cref="Line"/>, but they are for the bottom line of the stroke.
        /// </summary>
        internal const int LineBottom = 0x0600;
        /// <summary>
        /// 0x0640 - 0x067f
        /// This category has same attributes as <see cref="Line"/>, but they are for the "column" line of the stroke. 
        /// I don't know what it is.
        /// </summary>
        internal const int LineColumn = 0x0640;
        /// <summary>
        /// 0x680 - 0x6bf Properties related to Web Component Functionality.
        /// </summary>
        internal const int WebComponent = 0x0680;
        /// <summary>
        /// 0x6c0 - 0x6ff This property set defines an additional clipping path for a shape or group. 
        /// </summary>
        internal const int Clip = 0x06c0;
        /// <summary>
        /// 0x0700 - 0x073f TabletPC Ink Attributes
        /// </summary>
        internal const int TabletPCInk = 0x0700;
        internal const int Undocumented740 = 0x0740;
        /// <summary>
        /// Signature. These properties specify that the shape is a signature 
        /// line a document generated by Office 2007 or later.
        /// </summary>
        internal const int Signature = 0x0780;
        /// <summary>
        /// 0x07c0 - 0x07ff
        /// </summary>
        internal const int GroupShape2 = 0x07c0;

        /// <summary>
        /// Undocumented properties. Seen in TestJira13676.doc
        /// </summary>
        internal const int Undocumented800 = 0x0800;
        internal const int Undocumented840 = 0x0840;
        internal const int Undocumented880 = 0x0880;

        /// <summary>
        /// Undocumented property. Seen in TestJira17028.docx
        /// </summary>
        internal const int Undocumented20C0 = 0x20C0;

        /// <summary>
        /// Undocumented property. Seen in TestJira16313.doc
        /// </summary>
        internal const int Undocumented2000 = 0x2000;

        /// <summary>
        /// 0x1000 - 0x103f
        /// </summary>
        internal const int Aspose = 0x1000;
    }
}
