// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 28/11/2022 by Alexander Zhiltsov

using System.Collections.Generic;
using Aspose.Words.Drawing.Charts.Core.ComplexTypes;
using Aspose.Words.Drawing.Charts.Core.SimpleTypes;

namespace Aspose.Words.Drawing.Charts.Core
{
    /// <summary>
    /// Allows to retrieve information about data points/data labels related to a particular chart data value.
    /// </summary>
    internal class ChartExDataPointInfoRetriever
    {
        /// <summary>
        /// Creates an instance of this class.
        /// </summary>
        internal ChartExDataPointInfoRetriever(ChartSeries series, bool isForDataModification)
        {
            mSeries = series;
            mIsForDataModification = isForDataModification;
        }

        /// <summary>
        /// Gets infos of data points/labels that relate to a value with the specified index. The returned array is
        /// sorted by the point index.
        /// </summary>
        /// <remarks>
        /// There may be several points related to a chart data value. For example, if a Sunburst chart has a branch
        /// with one stem and one leaf, there are three data points and three labels that relate to the value: one is
        /// for the branch level, the second is for the stem level and the third is for the leaf level.
        /// </remarks>
        internal DataPointInfo[] GetDataPointInfos(int valueIndex, bool includeNextValueDataPointsForMultilevelChart)
        {
            switch (mSeries.LayoutType)
            {
                case SeriesLayout.BoxWhisker:
                    // Gets a data point of the specified value and service data points of the value's category.
                    return GetBoxWhiskerDataPointInfos(valueIndex);
                case SeriesLayout.Treemap:
                case SeriesLayout.Sunburst:
                    // Branch/stem data points are included only if they are located just before the specified value.
                    // Also data points of the next data value are retrieved if it is specified.
                    // DataPointInfo.IsPointReferencedByOtherValues is always 'false' in the returned data for a case
                    // e.g. when the first data value in a branch is replaced with a value having different branch:
                    // branch/stem data points/labels must be moved to a position after the updated data value if the
                    // next value has the same branch/stem. Let's remove and recreate such data points/labels for now.
                    return GetMultilevelChartDataPointInfos(valueIndex, includeNextValueDataPointsForMultilevelChart);
                case SeriesLayout.ClusteredColumn:
                {
                    if (mSeries.LayoutPr.IsAggregation)
                    {
                        // Pareto chart
                        return GetParetoDataPointInfos(valueIndex);
                    }
                    else
                    {
                        // Histogram chart
                        // If there is a fixed bin size or a fixed bin count, inserting/removing a value does not affect
                        // the points and labels. If the bins are auto generated by MS Word, its algorithm is too complex,
                        // we cannot forecast which bin will be removed by Word. Thus, let's keep existing points/labels:
                        // return an empty array that means that there are no points/label related to the value.
                        return new DataPointInfo[0];
                    }
                }
                case SeriesLayout.ParetoLine:
                    // It seems it is not possible to display data labels/data points for a pareto line in MS Word.
                    return new DataPointInfo[0];
                case SeriesLayout.Funnel:
                case SeriesLayout.RegionMap:
                case SeriesLayout.Waterfall:
                    // There is a single data point/label for a value in this chart types.
                    return new DataPointInfo[] { new DataPointInfo(valueIndex, valueIndex, 0, false) };
                default:
                    Debug.Assert(false, "Unknown series layout type.");
                    return new DataPointInfo[] { new DataPointInfo(valueIndex, valueIndex, 0, false) };
            }
        }

        /// <summary>
        /// Gets infos of data points/labels that relate to a value with the specified index in a Box and Whisker chart.
        /// </summary>
        /// <remarks>
        /// <p>A Box and Whisker chart category has the following additional data points: lower quantile, median, upper
        /// quantile, mean. They are located after value data points in that order. The value data points are located
        /// in order of their Y numeric values.</p>
        /// <p>The returned array is sorted by the point index.</p>
        /// </remarks>
        private DataPointInfo[] GetBoxWhiskerDataPointInfos(int valueIndex)
        {
            DmlChartValueCollection xValues = mSeries.X.Values;
            DmlChartValueCollection yValues = mSeries.Y.Values;

            DmlChartDataAnalyzer.AggregatedCategory category =
                mSeries.DataAnalyzer.GetBoxWhiskerCategoryInfo(xValues, yValues, valueIndex);
            if (category == null)
                return new DataPointInfo[0]; // The value is empty and has no data point.

            DataPointInfo[] infos = new DataPointInfo[BoxWhiskerSpecialPointCount + 1];
            // Calculate as the index of the value, when the values are ordered by category and value, plus the number
            // of special data points of preceding categories.
            int valuePointIndex = category.OrderedValueIndex + BoxWhiskerSpecialPointCount * category.CategoryIndex;
            infos[0] = new DataPointInfo(valuePointIndex, valueIndex, 0, false);

            int firstSpecialPointIndex =
                category.LastOrderedValueIndex + 1 + BoxWhiskerSpecialPointCount * category.CategoryIndex;

            for (int i = 0; i < BoxWhiskerSpecialPointCount; i++)
            {
                infos[i + 1] = new DataPointInfo(
                    firstSpecialPointIndex + i,
                    valueIndex,
                    -1,
                    !category.IsSingleValueCategory);
            }

            return infos;
        }

        /// <summary>
        /// Gets infos of data points/labels that relate to a value with the specified index and optionally for the next
        /// non-empty value in a Sunburst or Treemap chart. Infos for the next value are needed because when updating an
        /// X value of a Sunburst/Treemap chart data points/labels for the current and the next values may be affected.
        /// </summary>
        /// <remarks>
        /// <p>Data points/labels order: one for a branch if it is not empty and is different than the previous one;
        /// one for a stem if it is not empty and is different than the previous one, or its branch is different than
        /// the previous one; one for a leaf if it is not empty.</p>
        /// <p>The returned array is sorted by the point index.</p>
        /// </remarks>
        private DataPointInfo[] GetMultilevelChartDataPointInfos(int valueIndex, bool includeNextValueDataPoints)
        {
            DmlChartValueCollection xValues = mSeries.X.Values;
            List<DmlChartDataAnalyzer.Category> categories = mSeries.DataAnalyzer.GetCategories(xValues);
            List<DataPointInfo> infos = new List<DataPointInfo>();

            int currentValueIndex = valueIndex;
            foreach (DmlChartDataAnalyzer.Category category in categories)
            {
                // The categories are ordered by value index.
                if (category.FirstRelatedValueIndex < currentValueIndex)
                    continue;

                if (category.FirstRelatedValueIndex > currentValueIndex)
                {
                    // Break if next value data points are not needed or are already retrieved.
                    if (!includeNextValueDataPoints || (currentValueIndex > valueIndex))
                        break;
                    
                    currentValueIndex = category.FirstRelatedValueIndex;
                }

                // Return DataPointInfo.IsPointReferencedByOtherValues as 'false'; see the comment in the
                // GetDataPointInfos method.
                infos.Add(new DataPointInfo(category.Index, currentValueIndex, category.LevelIndex, false));
            }

            return infos.ToArray();
        }

        /// <summary>
        /// Gets infos of data points/labels that relate to a value with the specified index in a Pareto chart.
        /// </summary>
        /// <remarks>
        /// The returned array is sorted by the point index.
        /// </remarks>
        private DataPointInfo[] GetParetoDataPointInfos(int valueIndex)
        {
            Debug.Assert(mSeries.X.DimensionType == DimensionType.Category);

            DmlChartValueCollection xValues = mSeries.X.Values;
            DmlChartValueCollection yValues = mSeries.Y.Values;
            DmlChartMultiLvlStrValue value = (DmlChartMultiLvlStrValue)xValues[valueIndex];

            DmlChartDataAnalyzer.AggregatedCategory category =
                mSeries.DataAnalyzer.GetParetoCategoryInfo(xValues, yValues, valueIndex);

            if (category == null)
                return new DataPointInfo[0]; // The value is empty and has no data point.

            // When inserting/removing values in a Pareto chart, MS Word always inserts/removes the last label of
            // the series: return point index as 'category.CategoryCount - 1' here.
            int dataPointIndex = mIsForDataModification ? category.CategoryCount - 1 : category.CategoryIndex;

            return new DataPointInfo[]
            {
                new DataPointInfo(dataPointIndex, valueIndex, value.LevelsCount - 1, !category.IsSingleValueCategory)
            };
        }

        private readonly ChartSeries mSeries;
        private readonly bool mIsForDataModification;

        /// <summary>
        /// Gets a number of special data points/labels of a category in a Box and Whisker chart. The data points/labels
        /// are: lower quantile, median, upper quantile, mean.
        /// </summary>
        private const int BoxWhiskerSpecialPointCount = ChartSeriesHelper.BoxWhiskerSpecialPointCount;
    }
}
