// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 11/04/2013 by Victor Chebotok

using System.Collections;
using System.Collections.Generic;
using System.Text;
using Aspose.Collections.Generic;
using Aspose.Common;
using Aspose.Words.RW.HtmlCommon;

namespace Aspose.Words.RW.Html.Parser
{
    /// <summary>
    /// Collection of HTML attributes.
    /// </summary>
    internal class HtmlAttributeCollection : IEnumerable<HtmlAttribute>
    {
        /// <summary>
        /// Constructor. Initializes a new instance of the class.
        /// </summary>
        internal HtmlAttributeCollection()
        {
            mAttributes = new SortedStringListGeneric<HtmlAttribute>();
        }

        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(obj, null))
                return false;

            if (ReferenceEquals(obj, this))
                return true;

            if (obj.GetType() != typeof(HtmlAttributeCollection))
                return false;

            return Equals((HtmlAttributeCollection)obj);
        }

        /// <summary>
        /// Returns the hash code for this collection.
        /// </summary>
        public override int GetHashCode()
        {
            // Mimics hash code functions generated by Resharper.
            unchecked
            {
                int result = 0;
                foreach (HtmlAttribute attribute in mAttributes.Values)
                {
                    // The order of attributes in the backing collection does not depend on the order in which they were added,
                    // so a non-commutative operation can be used to calculate the hash code.
                    result = (result * 397) ^ attribute.GetHashCode();
                }
                return result;
            }
        }

        /// <summary>
        /// Adds the specified attribute to the collection.
        /// </summary>
        /// <param name="attribute">The attribute to insert. Must not be <c>null</c>.</param>
        /// <remarks>
        /// If an attribute with the same name is already added to the collection, the specified attribute will be ignored,
        /// as the HTML 5 Specification requires: http://www.w3.org/TR/html5/syntax.html#attribute-name-state
        /// </remarks>
        internal void Add(HtmlAttribute attribute)
        {
            Debug.Assert(attribute != null);

            // Add the attribute only if an attribute with the same name is not found in the collection.
            if (!mAttributes.ContainsKey(attribute.Name))
            {
                mAttributes.Add(attribute.Name, attribute);
                ++mVersion;
            }
        }

        /// <summary>
        /// Renames an attribute in the collection.
        /// </summary>
        /// <param name="oldName">The name of the attribute in the collection.</param>
        /// <param name="newName">The new name of the attribute.</param>
        internal void Rename(string oldName, string newName)
        {
            HtmlAttribute attribute = mAttributes.GetValueOrNull(oldName);
            if (attribute != null)
            {
                mAttributes.Remove(oldName);
                mAttributes.Add(newName, new HtmlAttribute(newName, attribute.Value));
                ++mVersion;
            }
        }

        /// <summary>
        /// Helper method to get the value of an attribute of this node. If the attribute is not found, the default value will be returned.
        /// </summary>
        /// <param name="name">The name of the attribute to get. May not be null.</param>
        /// <param name="defaultValue">The default value to return if the attribute is not found.</param>
        /// <returns>The value of the attribute if it is found, the default value otherwise.</returns>
        internal string GetAttributeValue(string name, string defaultValue)
        {
            Debug.Assert(StringUtil.HasChars(name));

            HtmlAttribute attribute = this[name];
            return (attribute != null)
                ? attribute.Value
                : defaultValue;
        }

        /// <summary>
        /// Helper method to get the value of an attribute of this node. If the attribute is not found, the default value will be returned.
        /// </summary>
        /// <param name="name">The name of the attribute to get. May not be null.</param>
        /// <param name="defaultValue">The default value to return if the attribute not found.</param>
        /// <returns>The value of the attribute if it is found, the default value otherwise.</returns>
        internal int GetAttributeValue(string name, int defaultValue)
        {
            Debug.Assert(StringUtil.HasChars(name));

            HtmlAttribute attribute = this[name];
            if (attribute == null)
            {
                return defaultValue;
            }

            int attributeValue = FormatterPal.TryParseInt(attribute.Value);
            return (attributeValue != int.MinValue)
                ? attributeValue
                : defaultValue;
        }

        /// <summary>
        /// Helper method to get the value of an attribute of this node. The value is parsed as integer and is clipped to the
        /// specified range. In case of a parsing error, the min specified value is returned.
        /// </summary>
        /// <param name="name">The name of the attribute to get. May not be null.</param>
        /// <param name="minValue">
        /// The lower bound of the value range. This value is also returned if the attribute is not found or cannot be parsed.
        /// </param>
        /// <param name="maxValue"> The upper bound of the value range.</param>
        /// <returns>
        /// The value of the attribute clipped to the specified range, if the attribute is present and is parsed without errors.
        /// The value specified in <paramref name="minValue"/> otherwise.
        /// </returns>
        internal int GetAttributeValue(string name, int minValue, int maxValue)
        {
            Debug.Assert(StringUtil.HasChars(name));

            HtmlAttribute attribute = this[name];
            if (attribute == null)
            {
                return minValue;
            }

            return HtmlUtil.ParseIntegerInRange(attribute.Value, minValue, maxValue);
        }

        public IEnumerator<HtmlAttribute> GetEnumerator()
        {
            return mAttributes.Values.GetEnumerator();
        }

        /// <summary>
        /// Gets an enumerator that iterates over all instances of <see cref="HtmlAttribute"/> in the collection.
        /// </summary>
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <summary>
        /// Determines whether this collection of attributes is equal to another collection of attributes.
        /// Equality of collections does not depend on the order in which attributes were added to each collection.
        /// </summary>
        /// <param name="otherAttributes">The collection of attributes to which current collection should be compared.</param>
        /// <returns><c>true</c>, if both collections contain same attributes; <c>false</c> otherwise.</returns>
        /// <remarks>
        /// Comparison of attributes is performed during construction of HTML tree, and follows the algorithm described here:
        /// http://www.w3.org/TR/html5/syntax.html#push-onto-the-list-of-active-formatting-elements
        /// </remarks>
        internal bool Equals(HtmlAttributeCollection otherAttributes)
        {
            if (ReferenceEquals(otherAttributes, null))
                return false;

            if (ReferenceEquals(otherAttributes, this))
                return true;

            if (mAttributes.Count != otherAttributes.Count)
                return false;

            foreach (HtmlAttribute attribute in mAttributes.Values)
            {
                HtmlAttribute otherAttribute = otherAttributes[attribute.Name];
                if ((otherAttribute == null) || (!otherAttribute.Equals(attribute)))
                {
                    return false;
                }
            }

            return true;
        }

        /// <summary>
        /// Serializes attributes of the collection to an HTML string. Attributes are sorted by name.
        /// </summary>
        /// <returns>
        /// The HTML string containing declarations of the attributes. 
        /// If the collection is empty, then an empty string is returned.
        /// </returns>
        /// <remarks>
        /// This method follows the algorithm described here: http://www.w3.org/TR/html5/syntax.html#serializing-html-fragments
        /// </remarks>
        internal string Serialize(XmlSerializationContext serializationContext)
        {
            StringBuilder result = new StringBuilder();

            bool appendDelimeter = false;

            // WORDSNET-23227 In case a HTML element contains embedded XML fragment (SVG or MathML) which contains
            // attributes with "xlink" prefix, upon serialization we should add the XLink namespace declaration to each element
            // that uses XLink attributes.
            // This behavior corresponds to how browsers serialize HTML elements to XML and this fix allows our SVG and MathML
            // readers to import such XML fragments correctly.
            List<HtmlAttribute> attributes = new List<HtmlAttribute>(mAttributes.Values);
            foreach (HtmlAttribute attribute in mAttributes.Values)
            {
                // The "xlink" prefix is hardcoded in browsers for the XLink namespace.
                if (!serializationContext.IsWellFormedName(attribute.Name) &&
                    StringUtil.StartsWithOrdinalIgnoreCase(attribute.Name, "xlink:"))
                {
                    serializationContext.AddXLinkNamespaceToContext();
                    attributes.Add(new HtmlAttribute("xmlns:xlink", W3CNamespaces.XLink));
                    break;
                }
            }

            foreach (HtmlAttribute attribute in attributes)
            {
                if (appendDelimeter)
                {
                    result.Append(' ');
                }
                appendDelimeter = true;

                result.Append(attribute.Name).Append("=\"");

                // Escaping of attribute values is described here: http://www.w3.org/TR/html5/syntax.html#escapingString
                for (int i = 0; i < attribute.Value.Length; i++)
                {
                    char c = attribute.Value[i];
                    switch (c)
                    {
                        case '&':
                            result.Append("&amp;");
                            break;
                        case '\u00A0':
                            // The "&nbsp;" entity is not defined in XML, so a numeric character reference is used instead.
                            result.Append(HtmlConstants.NoBreakSpaceHtmlNumericRef);
                            break;
                        case '\"':
                            result.Append("&quot;");
                            break;
                        // WORDSNET-21794 In HTML, characters "<" and ">" may appear unescaped in attribute values.
                        // However, this is not allowed in XML. Since we often re-parse serialized HTML as XML, we always escape
                        // those characters in attribute values during serialization.
                        case '<':
                            result.Append("&lt;");
                            break;
                        case '>':
                            result.Append("&gt;");
                            break;
                        default:
                            result.Append(c);
                            break;
                    }
                }

                result.Append('\"');
            }

            return result.ToString();
        }

        /// <summary>
        /// Gets the number of attributes contained in the collection.
        /// </summary>
        internal int Count
        {
            get { return mAttributes.Count; }
        }

        /// <summary>
        /// Gets an attribute from the collection by its name.
        /// </summary>
        /// <param name="name">The name of the attribute.</param>
        /// <returns>The requested attribute or <c>null</c> if no attribute with the specified name is found.</returns>
        internal HtmlAttribute this[string name]
        {
            get
            {
                Debug.Assert(StringUtil.HasChars(name));
                return mAttributes.GetValueOrNull(name);
            }
        }

        /// <summary>
        /// Gets a version number, which increases on every change to the collection.
        /// </summary>
        internal long Version
        {
            get { return mVersion; }
        }

        /// <summary>
        /// Map of attribute names to attribute instances.
        /// </summary>
        /// <remarks>
        /// Because a sorted collection is used, the order of attributes in it does not depend on the order in which they were
        /// added. The <see cref="GetHashCode"/> method relies on this feature. If you change the collection type, make sure
        /// <see cref="GetHashCode"/> is not broken.
        /// </remarks>
        private readonly SortedStringListGeneric<HtmlAttribute> mAttributes;

        /// <summary>
        /// Collection change marker. Is increased on every change to the collection.
        /// </summary>
        /// <remarks>
        /// Version starts from 1 so the default zero value can be considered an 'unknown' version that differs from any
        /// known version of the collection.
        /// </remarks>
        private long mVersion = 1;
    }
}
