// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 05/04/2013 by Victor Chebotok

namespace Aspose.Words.RW.Html.Parser
{
    /// <summary>
    /// Represents an HTML attribute.
    /// </summary>
    internal class HtmlAttribute
    {
        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="name">The attribute's name. Must not be empty or <c>null</c>.</param>
        /// <param name="value">The attribute's value. Must not be <c>null</c>.</param>
        internal HtmlAttribute(string name, string value)
        {
            Debug.Assert(StringUtil.HasChars(name));
            Debug.Assert(value != null);

            mName = name;
            mValue = value;
        }

        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(obj, null))
                return false;

            if (ReferenceEquals(obj, this))
                return true;

            if (obj.GetType() != typeof(HtmlAttribute))
                return false;

            return Equals((HtmlAttribute)obj);
        }

        /// <summary>
        /// Returns the hash code for this attribute.
        /// </summary>
        public override int GetHashCode()
        {
            // Generated by Resharper.
            unchecked
            {
                return (mName.GetHashCode() * 397) ^ mValue.GetHashCode();
            }
        }

        /// <summary>
        /// Determines whether the specified attribute is equal to the current attribute.
        /// </summary>
        internal bool Equals(HtmlAttribute other)
        {
            if (ReferenceEquals(other, null))
                return false;

            if (ReferenceEquals(other, this))
                return true;

            // Ordinal case-sensitive comparison.
            return (other.mName == mName) && (other.mValue == mValue);
        }

        /// <summary>
        /// Gets the name of the attribute.
        /// </summary>
        internal string Name
        {
            get { return mName; }
        }

        /// <summary>
        /// Gets the name of the attribute.
        /// </summary>
        internal string Value
        {
            get { return mValue; }
        }

        private readonly string mName;

        private readonly string mValue;
    }
}
