// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 25/04/2005 by Roman Korchagin

using System.Collections.Generic;
using System.ComponentModel;

namespace Aspose.Words
{
    /// <summary>
    /// Model class that represents custom column widths and spacings.
    /// This whole collection is stored in the section attributes as a single attribute.
    /// </summary>
    /// <dev>Note. Do not merge this class with <see cref="TextColumnCollection"/>. We did that in the past.
    /// It was wrong. The reason is that <see cref="TextColumnCollection"/> need to reference PageSetup and SectPr
    /// which is a wrong pattern for the attribute.</dev>
    internal class TextColumnCollectionInternal : IComplexAttr
    {
        /// <summary>
        /// Resizes the collection. When increasing the count, adds more text columns of zero width.
        /// </summary>
        /// <param name="newCount"></param>
        internal void SetCount(int newCount)
        {
            if (Count < newCount)
            {
                while (Count < newCount)
                    Add(new TextColumn());
            }
            else
            {
                while (Count > newCount)
                    RemoveAt(Count - 1);
            }
        }

        internal void Add(TextColumn column)
        {
            Debug.Assert(null != column);
            mItems.Add(column);
        }

        internal void RemoveAt(int index)
        {
            mItems.RemoveAt(index);
        }

        internal int Count
        {
            [System.Diagnostics.DebuggerStepThrough]
            [CodePorting.Translator.Cs2Cpp.CppConstMethod]
            get { return mItems.Count; }
        }

        internal TextColumn this[int index]
        {
            [CodePorting.Translator.Cs2Cpp.CppConstMethod]
            get { return mItems[index]; }
            set 
            {
                mItems[index] = value; 
            }
        }

        /// <summary>
        /// Returns <b>true</b> if the collection contains columns with non-empty width or space after.
        /// </summary>
        internal bool HasData
        {
            get
            {
                foreach (TextColumn column in mItems)
                {
                    if (column.HasData)
                        return true;
                }

                return false;
            }
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool IsInheritedComplexAttr
        {
            // Text column collection is never inherited from any parent.
            get { return false; }
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        IComplexAttr IComplexAttr.DeepCloneComplexAttr()
        {
            TextColumnCollectionInternal lhs = (TextColumnCollectionInternal)this.MemberwiseClone();
            lhs.mItems = new List<TextColumn>();
            foreach (TextColumn item in mItems)
            {
                TextColumn clone = item.Clone();
                lhs.mItems.Add(clone);
            }

            return lhs;
        }

        public override bool Equals(object obj)
        {
            // Generated by ReSharper. 
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != this.GetType())
                return false;

            TextColumnCollectionInternal rhs = (TextColumnCollectionInternal)obj;

            if (Count != rhs.Count)
                return false;

            for (int i = 0; i < Count; i++)
                if (!MathUtil.AreEqual(this[i].Width, rhs[i].Width) || !MathUtil.AreEqual(this[i].SpaceAfter, rhs[i].SpaceAfter)) 
                    return false;

            return true;
        }

        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                for (int i = 0; i < Count; i++)
                    result =  (result + (this[i].RawWidth * 397)) ^ this[i].RawSpaceAfter;
                return result;
            }
        }

        private List<TextColumn> mItems = new List<TextColumn>();
    }
}
