// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 29/08/2013 by Ivan Lyagin

// 
// This source code was auto-generated by Aspose.CsClassTransformer.ConsoleApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
// Do not change the file manually as your changes will be lost during next auto-generation session.
// 

using System;
using Aspose.Collections;
using Aspose.JavaAttributes;
using CodePorting.Translator.Cs2Cpp;
using NUnit.Framework;

namespace Aspose.Tests.Collections.Auto
{
    /// <summary>
    /// Tests StringList class' functionality.
    /// </summary>
    /// <remarks>
    /// Every individual test of this class corresponds to a StringList member.
    /// See the corresponding StringList members' descriptions for any additional information.
    /// </remarks>
    [TestFixture]
    public class TestStringList
    {
        [Test]
        public void TestAdd()
        {
            StringList list = new StringList();
            list.Add(FirstItem);
            Assert.That(list.Count, Is.EqualTo(1));
            Assert.That(list[0], Is.EqualTo(FirstItem));
        }

        [Test]
        public void TestAddRange()
        {
            StringList list1 = new StringList();
            list1.AddRange(gArray);
            Assert.That(list1.Count, Is.EqualTo(gArray.Length));
            Assert.That(list1.ToArray(), Is.EqualTo(gArray));

            StringList list2 = new StringList();
            list2.AddRange(list1);
            Assert.That(list2.Count, Is.EqualTo(gArray.Length));
            Assert.That(list2.ToArray(), Is.EqualTo(gArray));
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestAddRangeNullList()
        {
            StringList list = new StringList();
            list.AddRange((StringList)null);
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestAddRangeNullArray()
        {
            StringList list = new StringList();
            list.AddRange((string[])null);
        }

        [Test]
        public void TestSortBinarySearchFull()
        {
            string[] sortedArray = new string[gArray.Length];
            Array.Copy(gArray, sortedArray, gArray.Length);
            Array.Sort(sortedArray);

            StringList list = new StringList(gArray);
            list.Sort();
            Assert.That(list.ToArray(), Is.EqualTo(sortedArray));
            Assert.That(list.BinarySearch(FirstItem), Is.EqualTo(ArrayUtil.BinarySearch(sortedArray, 0, sortedArray.Length, FirstItem)));
            Assert.That(0, Is.GreaterThan(list.BinarySearch(gMissingItem)));
        }

        [Test]
        public void TestSortBinarySearchPart()
        {
            string[] sortedArray = new string[gArray.Length];
            Array.Copy(gArray, sortedArray, gArray.Length);
            Array.Sort(sortedArray, 1, sortedArray.Length - 1);

            StringList list = new StringList(gArray);
            list.Sort(1, list.Count - 1);
            Assert.That(list.ToArray(), Is.EqualTo(sortedArray));

            string lastItem = gArray[gArray.Length - 1];
            Assert.That(list.BinarySearch(1, list.Count - 1, lastItem), Is.EqualTo(ArrayUtil.BinarySearch(sortedArray, 1, sortedArray.Length - 1, lastItem)));
            Assert.That(0, Is.GreaterThan(list.BinarySearch(1, list.Count - 1, FirstItem)));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestSortNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.Sort(-1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestSortNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.Sort(0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestSortInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.Sort(0, list.Count + 1);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestBinarySearchNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.BinarySearch(-1, list.Count, FirstItem);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestBinarySearchNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.BinarySearch(0, -1, FirstItem);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestBinarySearchInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.BinarySearch(0, list.Count + 1, FirstItem);
        }

        [Test]
        public void TestClear()
        {
            StringList list = new StringList(gArray);
            list.Add(FirstItem);
            list.Clear();
            Assert.That(list.Count, Is.EqualTo(0));
        }

        [Test]
        public void TestContains()
        {
            StringList list = new StringList(gArray);
            Assert.That(list.Contains(FirstItem), Is.True);
            Assert.That(list.Contains(gMissingItem), Is.False);
        }

        [Test]
        public void TestCopyTo()
        {
            string[] expectedArray = new string[gArray.Length * 2 + 1];
            Array.Copy(gArray, expectedArray, gArray.Length);
            Array.Copy(gArray, 0, expectedArray, gArray.Length, gArray.Length);
            expectedArray[expectedArray.Length - 1] = gArray[gArray.Length - 1];

            string[] actualArray = new string[gArray.Length * 2 + 1];
            StringList list = new StringList(gArray);
            list.CopyTo(actualArray);
            list.CopyTo(actualArray, list.Count);
            list.CopyTo(list.Count - 1, actualArray, list.Count * 2, 1);

            Assert.That(actualArray, Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestCopyToNegativeIndex()
        {
            string[] array = new string[gArray.Length];
            StringList list = new StringList(gArray);
            list.CopyTo(-1, array, 0, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestCopyToNegativeCount()
        {
            string[] array = new string[gArray.Length];
            StringList list = new StringList(gArray);
            list.CopyTo(0, array, 0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestCopyToInvalidRange()
        {
            string[] array = new string[gArray.Length];
            StringList list = new StringList(gArray);
            list.CopyTo(0, array, 0, list.Count + 1);
        }

        [Test]
        [ExpectedException(typeof(ArgumentNullException))]
        public void TestCopyToNullArray()
        {
            StringList list = new StringList(gArray);
            list.CopyTo(0, null, 0, list.Count);
        }

        [Test]
        [JavaExpectedException(typeof(ArrayIndexOutOfBoundsException))]
        [ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestCopyToNegativeArrayIndex()
        {
            string[] array = new string[gArray.Length];
            StringList list = new StringList(gArray);
            list.CopyTo(0, array, -1, list.Count);
        }

        [Test]
        [JavaExpectedException(typeof(ArrayIndexOutOfBoundsException))]
        [ExpectedException(typeof(ArgumentException))]
        public void TestCopyToInvalidArrayRange()
        {
            string[] array = new string[gArray.Length - 1];
            StringList list = new StringList(gArray);
            list.CopyTo(0, array, 0, list.Count);
        }

        [Test]
        public void TestGetRange()
        {
            StringList list1 = new StringList(gArray);
            StringList list2 = list1.GetRange(1, list1.Count - 1);
            Assert.That(list2.Count, Is.EqualTo(list1.Count - 1));

            string[] expectedArray = new string[gArray.Length - 1];
            Array.Copy(gArray, 1, expectedArray, 0, gArray.Length - 1);
            Assert.That(list2.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestGetRangeNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.GetRange(-1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestGetRangeNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.GetRange(0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestGetRangeInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.GetRange(0, list.Count + 1);
        }

        [Test]
        public void TestIndexOf()
        {
            StringList list = new StringList(gArray);
            Assert.That(list.IndexOf(FirstItem), Is.EqualTo(0));
            Assert.That(list.IndexOf(gMissingItem), Is.EqualTo(-1));
            Assert.That(list.IndexOf(FirstItem, 1), Is.EqualTo(-1));
            Assert.That(list.IndexOf(FirstItem, 0), Is.EqualTo(0));
            Assert.That(list.IndexOf(FirstItem, 1, 1), Is.EqualTo(-1));
            Assert.That(list.IndexOf(FirstItem, 0, 0), Is.EqualTo(-1));
            Assert.That(list.IndexOf(FirstItem, 0, 1), Is.EqualTo(0));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestIndexOfNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.IndexOf(gMissingItem, -1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestIndexOfNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.IndexOf(gMissingItem, 0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestIndexOfInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.IndexOf(gMissingItem, 0, list.Count + 1);
        }

        [Test]
        public void TestInsert()
        {
            string[] expectedArray = new string[gArray.Length + 3];
            expectedArray[0] = gMissingItem;
            expectedArray[1] = FirstItem;
            expectedArray[2] = gMissingItem;
            expectedArray[expectedArray.Length - 1] = gMissingItem;
            Array.Copy(gArray, 1, expectedArray, 3, gArray.Length - 1);

            StringList list = new StringList(gArray);
            list.Insert(1, gMissingItem);
            list.Insert(0, gMissingItem);
            list.Insert(list.Count, gMissingItem);
            Assert.That(list.Count, Is.EqualTo(gArray.Length + 3));
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.Insert(-1, gMissingItem);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertExceedingIndex()
        {
            StringList list = new StringList(gArray);
            list.Insert(list.Count + 1, gMissingItem);
        }

        [Test]
        public void TestInsertRange()
        {
            string[] expectedArray = new string[gArray.Length * 4];
            Array.Copy(gArray, expectedArray, gArray.Length);
            expectedArray[gArray.Length] = FirstItem;
            Array.Copy(gArray, 0, expectedArray, gArray.Length + 1, gArray.Length);
            Array.Copy(gArray, 1, expectedArray, gArray.Length * 2 + 1, gArray.Length - 1);
            Array.Copy(gArray, 0, expectedArray, gArray.Length * 3, gArray.Length);

            StringList list1 = new StringList(gArray);
            StringList list2 = new StringList(gArray);
            list1.InsertRange(1, list2);
            list1.InsertRange(0, list2);
            list1.InsertRange(list1.Count, list2);
            list2.InsertRange(1, gArray);
            list2.InsertRange(0, gArray);
            list2.InsertRange(list2.Count, gArray);

            Assert.That(list1.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list1.ToArray(), Is.EqualTo(expectedArray));
            Assert.That(list2.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list2.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test]
        public void TestInsertRangeSelf()
        {
            string[] expectedArray = new string[gArray.Length * 2];
            expectedArray[0] = FirstItem;
            Array.Copy(gArray, 0, expectedArray, 1, gArray.Length);
            Array.Copy(gArray, 1, expectedArray, gArray.Length + 1, gArray.Length - 1);

            StringList list = new StringList(gArray);
            list.InsertRange(1, list);
            Assert.That(list.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestInsertRangeNullArray()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(1, (string[])null);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertRangeArrayNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(-1, gArray);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertRangeArrayExceedingIndex()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(list.Count + 1, gArray);
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestInsertRangeNullList()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(1, (StringList)null);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertRangeListNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(-1, list);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestInsertRangeListExceedingIndex()
        {
            StringList list = new StringList(gArray);
            list.InsertRange(list.Count + 1, list);
        }

        [Test]
        public void TestLastIndexOf()
        {
            StringList list = new StringList(gArray);
            int lastItemIndex = list.Count - 1;
            string lastItem = list[lastItemIndex];

            Assert.That(list.LastIndexOf(lastItem), Is.EqualTo(lastItemIndex));
            Assert.That(list.LastIndexOf(gMissingItem), Is.EqualTo(-1));
            Assert.That(list.LastIndexOf(lastItem, lastItemIndex - 1), Is.EqualTo(-1));
            Assert.That(list.LastIndexOf(lastItem, lastItemIndex), Is.EqualTo(lastItemIndex));
            Assert.That(list.LastIndexOf(lastItem, lastItemIndex - 1, 1), Is.EqualTo(-1));
            Assert.That(list.LastIndexOf(lastItem, lastItemIndex, 0), Is.EqualTo(-1));
            Assert.That(list.LastIndexOf(lastItem, lastItemIndex, 1), Is.EqualTo(lastItemIndex));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestLastIndexOfNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.LastIndexOf(gMissingItem, -1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestLastIndexOfNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.LastIndexOf(gMissingItem, list.Count - 1, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestLastIndexOfInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.LastIndexOf(gMissingItem, list.Count - 1, list.Count + 1);
        }

        [Test]
        public void TestRemove()
        {
            string[] expectedArray = new string[gArray.Length - 1];
            expectedArray[0] = FirstItem;
            Array.Copy(gArray, 2, expectedArray, 1, gArray.Length - 2);

            StringList list = new StringList(gArray);
            bool isRemoved = list.Remove(gArray[1]);
            Assert.That(isRemoved, Is.True);
            Assert.That(list.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));

            isRemoved = list.Remove(gMissingItem);
            Assert.That(isRemoved, Is.False);
            Assert.That(list.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test]
        public void TestRemoveAt()
        {
            string[] expectedArray = new string[gArray.Length - 1];
            expectedArray[0] = FirstItem;
            Array.Copy(gArray, 2, expectedArray, 1, gArray.Length - 2);

            StringList list = new StringList(gArray);
            list.RemoveAt(1);
            Assert.That(list.Count, Is.EqualTo(expectedArray.Length));
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestRemoveAtNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.RemoveAt(-1);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestRemoveAtExceedingIndex()
        {
            StringList list = new StringList(gArray);
            list.RemoveAt(list.Count);
        }

        [Test]
        public void TestRemoveRange()
        {
            StringList list = new StringList(gArray);
            list.RemoveRange(1, list.Count - 2);
            Assert.That(list.Count, Is.EqualTo(2));
            Assert.That(list[0], Is.EqualTo(FirstItem));
            Assert.That(list[1], Is.EqualTo(gArray[gArray.Length - 1]));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestRemoveRangeNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.RemoveRange(-1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestRemoveRangeNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.RemoveRange(0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestRemoveRangeInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.RemoveRange(0, list.Count + 1);
        }

        [Test]
        public void TestReverseFull()
        {
            string[] expectedArray = new string[gArray.Length];
            Array.Copy(gArray, expectedArray, gArray.Length);
            Array.Reverse(expectedArray);

            StringList list = new StringList(gArray);
            list.Reverse();
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test]
        public void TestReversePart()
        {
            string[] expectedArray = new string[gArray.Length];
            Array.Copy(gArray, expectedArray, gArray.Length);
            Array.Reverse(expectedArray, 1, expectedArray.Length - 2);

            StringList list = new StringList(gArray);
            list.Reverse(1, list.Count - 2);
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestReverseNegativeIndex()
        {
            StringList list = new StringList(gArray);
            list.Reverse(-1, list.Count);
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestReverseNegativeCount()
        {
            StringList list = new StringList(gArray);
            list.Reverse(0, -1);
        }

        [Test, ExpectedException(typeof(ArgumentException))]
        public void TestReverseInvalidRange()
        {
            StringList list = new StringList(gArray);
            list.Reverse(0, list.Count + 1);
        }

        [Test]
        public void TestToArray()
        {
            StringList list = new StringList(gArray);
            string[] array1 = list.ToArray();
            string[] array2 = list.ToArray();
            Assert.That(array2, IsNot.SameAs(array1));
            Assert.That(array1, Is.EqualTo(gArray));
            Assert.That(array2, Is.EqualTo(gArray));

            string[] expectedArray = new string[gArray.Length - 1];
            expectedArray[0] = FirstItem;
            Array.Copy(gArray, 2, expectedArray, 1, gArray.Length - 2);

            list.RemoveAt(1);
            Assert.That(list.ToArray(), Is.EqualTo(expectedArray));

            list.Clear();
            Assert.That(list.ToArray(), Is.EqualTo(new string[0]));
        }

        [Test]
        [CppSkipEntity("C# and Java implementation specific test")]
        public void TestTrimExcess()
        {
            StringList list = new StringList(10);
            list.Add(gMissingItem);
            list.TrimExcess();
            Assert.That(list.Capacity, Is.EqualTo(1));
        }

        [Test]
        [CppSkipEntity("C# and Java implementation specific test")]
        public void TestCapacityGrow()
        {
            StringList list = new StringList();
            Assert.That(list.Capacity, Is.EqualTo(0));

            list.Add(gMissingItem);
            int capacity = list.Capacity;
            Assert.That(capacity, Is.GreaterThan(list.Count));

            while (list.Count != capacity)
                list.Add(gMissingItem);

            Assert.That(list.Capacity, Is.EqualTo(list.Count));

            list.Add(gMissingItem);
            Assert.That(list.Capacity, Is.GreaterThan(list.Count));
        }

        [Test]
        [CppSkipEntity("C# and Java implementation specific test")]
        public void TestCapacity()
        {
            StringList list = new StringList(10);
            Assert.That(list.Capacity, Is.EqualTo(10));
            
            list.Capacity = 5;
            Assert.That(list.Capacity, Is.EqualTo(5));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestCapacityNegative()
        {
            StringList list = new StringList();
            list.Capacity = -1;
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestCapacityInferior()
        {
            StringList list = new StringList(gArray);
            list.Capacity = list.Count - 1;
        }

        [Test]
        public void TestCount()
        {
            StringList list = new StringList();
            Assert.That(list.Count, Is.EqualTo(0));

            list.Add(gMissingItem);
            Assert.That(list.Count, Is.EqualTo(1));

            list.Add(gMissingItem);
            Assert.That(list.Count, Is.EqualTo(2));

            list.RemoveAt(0);
            Assert.That(list.Count, Is.EqualTo(1));

            list.Clear();
            Assert.That(list.Count, Is.EqualTo(0));
        }

        [Test]
        public void TestGetSet()
        {
            StringList list = new StringList();
            list.Add(gMissingItem);
            Assert.That(list[0], Is.EqualTo(gMissingItem));

            list[0] = FirstItem;
            Assert.That(list[0], Is.EqualTo(FirstItem));
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestGetNegativeIndex()
        {
            StringList list = new StringList();
            string item = list[-1];
            Assert.Fail(string.Format(string.Empty, item)); // Force the compiler not to skip the previous instruction.
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestGetExceedingIndex()
        {
            StringList list = new StringList(gArray);
            string item = list[list.Count];
            Assert.Fail(string.Format(string.Empty, item)); // Force the compiler not to skip the previous instruction.
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestSetNegativeIndex()
        {
            StringList list = new StringList();
            list[-1] = gMissingItem;
        }

        [Test, ExpectedException(typeof(ArgumentOutOfRangeException))]
        public void TestSetExceedingIndex()
        {
            StringList list = new StringList(gArray);
            list[list.Count] = gMissingItem;
        }

        [Test]
        public void TestCopyCtors()
        {
            StringList list1 = new StringList(gArray);
            Assert.That(list1.ToArray(), Is.EqualTo(gArray));

            StringList list2 = new StringList(list1);
            Assert.That(list2.ToArray(), Is.EqualTo(gArray));
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestCopyCtorNullArray()
        {
            StringList list = new StringList((string[])null);
            Assert.Fail(string.Format(string.Empty, list)); // Force the compiler not to skip the previous instruction.
        }

        [Test, ExpectedException(typeof(ArgumentNullException))]
        public void TestCopyCtorNullList()
        {
            StringList list = new StringList((StringList)null);
            Assert.Fail(string.Format(string.Empty, list)); // Force the compiler not to skip the previous instruction.
        }

        /// <summary>
        /// Returns an array extensively used in this test.
        /// </summary>
        private static string[] GetArray()
        {
            return new string[] { "fa", "da", "aa", "ba", "ea", "ca" };
        }

        /// <summary>
        /// Returns an instance of string type missing in an array returned by <see cref="GetArray"/>.
        /// </summary>
        private static string GetMissingItem()
        {
            return "ga";
        }

        /// <summary>
        /// Gets the first item of the test array.
        /// </summary>
        private static string FirstItem
        {
            get { return gArray[0]; }
        }

        // Calculate once, use multiple times.
        private static readonly string[] gArray = GetArray();
        private static readonly string gMissingItem = GetMissingItem();
    }
}
