// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 29/08/2013 by Ivan Lyagin

// 
// This source code was auto-generated by Aspose.CsClassTransformer.ConsoleApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
// Do not change the file manually as your changes will be lost during next auto-generation session.
// 

using System;
using Aspose.Collections;
using NUnit.Framework;

namespace Aspose.Tests.Collections.Auto
{
    /// <summary>
    /// Tests Dictionary&lt;byte, uint&gt; class' functionality.
    /// </summary>
    [TestFixture]
    public class TestByteToUIntDictionary
    {
        /// <summary>
        /// Tests how items are added to a dictionary.
        /// </summary>
        [Test]
        public void TestAdd()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            dictionary.Add(gSecondKey, gSecondValue);
            Assert.That(dictionary.Count, Is.EqualTo(2));
            Assert.That(dictionary[gFirstKey], Is.EqualTo(gFirstValue));
            Assert.That(dictionary[gSecondKey], Is.EqualTo(gSecondValue));
        }

        /// <summary>
        /// Tests that duplicate keys can not be added to a dictionary.
        /// </summary>
        [Test]
        public void TestAddDuplicate()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            TestAddDuplicate(dictionary, gFirstKey);
        }

        /// <summary>
        /// Tests the addition of a duplicate key to a dictionary.
        /// </summary>
        private static void TestAddDuplicate(ByteToUIntDictionary dictionary, byte duplicateKey)
        {
            try
            {
                dictionary.Add(duplicateKey, gFirstValue);
            }
            catch (InvalidOperationException)
            {
                return;
            }

            Assert.Fail("An exception throw is expected.");
        }

        /// <summary>
        /// Tests removal of all items from a dictionary.
        /// </summary>
        [Test]
        public void TestClear()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            dictionary.Add(gSecondKey, gSecondValue);
            dictionary.Clear();
            Assert.That(dictionary.Count, Is.EqualTo(0));
        }

        /// <summary>
        /// Tests how dictionary key and value existence is checked.
        /// </summary>
        [Test]
        public void TestContains()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            Assert.That(dictionary.ContainsKey(gFirstKey), Is.True);
            Assert.That(dictionary.ContainsValue(gFirstValue), Is.True);
            Assert.That(dictionary.ContainsKey(gSecondKey), Is.False);
            Assert.That(dictionary.ContainsValue(gSecondValue), Is.False);
        }

        /// <summary>
        /// Tests how dictionary enumeration works.
        /// </summary>
        [Test]
        public void TestEnumerator()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            dictionary.Add(gSecondKey, gSecondValue);

            ByteToUIntDictionary.Enumerator enumerator = dictionary.GetEnumerator();
            TestEnumerator(dictionary, enumerator);

            // Reset the enumerator state and verify that it will work exactly in the same way.
            enumerator.Reset();
            TestEnumerator(dictionary, enumerator);
        }

        /// <summary>
        /// Tests a single pass of a dictionary enumerator.
        /// </summary>
        private static void TestEnumerator(ByteToUIntDictionary dictionary, ByteToUIntDictionary.Enumerator enumerator)
        {
            byte[] keys = new byte[dictionary.Count];
            uint[] values = new uint[dictionary.Count];
            int index = 0;

            while (enumerator.MoveNext())
            {
                keys[index] = enumerator.CurrentKey;
                values[index] = enumerator.CurrentValue;
                index++;
            }

            Assert.That(index, Is.EqualTo(2));

            int firstKeyIndex = Array.IndexOf(keys, gFirstKey);
            Assert.That(firstKeyIndex, Is.GreaterThanOrEqualTo(0));

            int secondKeyIndex = Array.IndexOf(keys, gSecondKey);
            Assert.That(secondKeyIndex, Is.GreaterThanOrEqualTo(0));
            Assert.That(secondKeyIndex, IsNot.EqualTo(firstKeyIndex));

            int firstValueIndex = Array.IndexOf(values, gFirstValue);
            Assert.That(firstValueIndex, Is.GreaterThanOrEqualTo(0));
            Assert.That(firstValueIndex, Is.EqualTo(firstKeyIndex));

            int secondValueIndex = Array.IndexOf(values, gSecondValue);
            Assert.That(secondValueIndex, Is.GreaterThanOrEqualTo(0));
            Assert.That(secondValueIndex, IsNot.EqualTo(firstValueIndex));
            Assert.That(secondValueIndex, Is.EqualTo(secondKeyIndex));
        }

        /// <summary>
        /// Tests that accessing of a dictionary key being enumerated is not allowed for a dictionary enumerator 
        /// which was not successfully moved.
        /// </summary>
        [Test, ExpectedException(typeof(InvalidOperationException))]
        public void TestEnumeratorGetKeyWithoutMove()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            ByteToUIntDictionary.Enumerator enumerator = dictionary.GetEnumerator();
            byte key = enumerator.CurrentKey;
            Assert.Fail(string.Format(string.Empty, key)); // Force the compiler not to skip the previous instruction.
        }

        /// <summary>
        /// Tests that accessing of a dictionary value being enumerated is not allowed for a dictionary enumerator 
        /// which was not successfully moved.
        /// </summary>
        [Test, ExpectedException(typeof(InvalidOperationException))]
        public void TestEnumeratorGetValueWithoutMove()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            ByteToUIntDictionary.Enumerator enumerator = dictionary.GetEnumerator();
            uint value = enumerator.CurrentValue;
            Assert.Fail(string.Format(string.Empty, value)); // Force the compiler not to skip the previous instruction.
        }

        /// <summary>
        /// Tests that modifications of a dictionary while its enumerating are prohibited.
        /// </summary>
        [Test, ExpectedException(typeof(InvalidOperationException))]
        public void TestEnumeratorChangeWhileMoving()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            
            ByteToUIntDictionary.Enumerator enumerator = dictionary.GetEnumerator();
            bool isMoved = enumerator.MoveNext();
            Assert.That(isMoved, Is.True);

            dictionary.Add(gSecondKey, gSecondValue);
            enumerator.MoveNext();
        }

        /// <summary>
        /// Tests how dictionary item removal works.
        /// </summary>
        [Test]
        public void TestRemove()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            bool isRemoved = dictionary.Remove(gSecondKey);
            Assert.That(isRemoved, Is.False);
            Assert.That(dictionary.Count, Is.EqualTo(1));

            isRemoved = dictionary.Remove(gFirstKey);
            Assert.That(isRemoved, Is.True);
            Assert.That(dictionary.Count, Is.EqualTo(0));

            isRemoved = dictionary.Remove(gFirstKey);
            Assert.That(isRemoved, Is.False);
            Assert.That(dictionary.Count, Is.EqualTo(0));
        }

        /// <summary>
        /// Tests how a null substitute value for a dictionary is checked.
        /// </summary>
        [Test]
        public void TestNullSubstitute()
        {
            // Ensure that the test is valid and the first test value is not a null substitute value.
            Assert.That(ByteToUIntDictionary.IsNullSubstitute(gFirstValue), Is.False);

            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            Assert.That(ByteToUIntDictionary.IsNullSubstitute(dictionary[gFirstKey]), Is.False);
            Assert.That(ByteToUIntDictionary.IsNullSubstitute(dictionary[gSecondKey]), Is.True);
        }

        /// <summary>
        /// Tests how dictionary item count calculation works.
        /// </summary>
        [Test]
        public void TestCount()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary.Add(gFirstKey, gFirstValue);
            Assert.That(dictionary.Count, Is.EqualTo(1));

            dictionary.Add(gSecondKey, gSecondValue);
            Assert.That(dictionary.Count, Is.EqualTo(2));

            dictionary.Remove(gSecondKey);
            Assert.That(dictionary.Count, Is.EqualTo(1));

            dictionary.Clear();
            Assert.That(dictionary.Count, Is.EqualTo(0));
        }

        /// <summary>
        /// Tests how dictionary values are set and retrieved according to their keys.
        /// </summary>
        [Test]
        public void TestGetSet()
        {
            ByteToUIntDictionary dictionary = new ByteToUIntDictionary();
            dictionary[gFirstKey] = gFirstValue;
            dictionary[gFirstKey] = gSecondValue;
            Assert.That(dictionary.Count, Is.EqualTo(1));
            Assert.That(dictionary[gFirstKey], Is.EqualTo(gSecondValue));
            Assert.That(ByteToUIntDictionary.IsNullSubstitute(dictionary[gSecondKey]), Is.True);
        }

        /// <summary>
        /// Tests how a dictionary contents are copied from another dictionary.
        /// </summary>
        [Test]
        public void TestCopyCtor()
        {
            ByteToUIntDictionary dictionary1 = new ByteToUIntDictionary();
            dictionary1[gFirstKey] = gFirstValue;
            dictionary1[gSecondKey] = gSecondValue;

            ByteToUIntDictionary dictionary2 = new ByteToUIntDictionary(dictionary1);
            Assert.That(dictionary2.Count, Is.EqualTo(2));
            Assert.That(dictionary2[gFirstKey], Is.EqualTo(gFirstValue));
            Assert.That(dictionary2[gSecondKey], Is.EqualTo(gSecondValue));

            // Ensure that the dictionaries are independent.
            dictionary2[gFirstKey] = gSecondValue;
            Assert.That(dictionary2[gFirstKey], Is.EqualTo(gSecondValue));
            Assert.That(dictionary1[gFirstKey], Is.EqualTo(gFirstValue));
        }




        /// <summary>
        /// Returns the first dictionary key to test.
        /// </summary>
        private static byte GetFirstKey()
        {
            return (byte)3;
        }

        /// <summary>
        /// Returns the second dictionary key to test.
        /// </summary>
        private static byte GetSecondKey()
        {
            return (byte)4;
        }

        /// <summary>
        /// Returns the first dictionary value to test.
        /// </summary>
        private static uint GetFirstValue()
        {
            return 1;
        }

        /// <summary>
        /// Returns the second dictionary value to test.
        /// </summary>
        private static uint GetSecondValue()
        {
            return 2;
        }

        // Calculate once, use multiple times.
        private static readonly byte gFirstKey = GetFirstKey();
        private static readonly byte gSecondKey = GetSecondKey();
        private static readonly uint gFirstValue = GetFirstValue();
        private static readonly uint gSecondValue = GetSecondValue();
    }
}
