// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 20/08/2013 by Ivan Lyagin

// 
// This source code was auto-generated by Aspose.CsClassTransformer.ConsoleApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
// Do not change the file manually as your changes will be lost during next auto-generation session.
// 

using System;
using System.Text;

namespace Aspose.Collections
{
    /// <summary>
    /// Represents a strongly typed list of objects that can be accessed by index. 
    /// Provides methods to search, sort, and manipulate lists.
    /// </summary>
    /// <dev>
    /// This class was created using ROTOR sources. It was reworked considering AW specifics and Java autoportability.
    /// </dev>
    public class CharList
    {
        /// <summary>
        /// Initializes a new instance of the CharList class that has the initial capacity compatible with
        /// old manually written classes.
        /// </summary>
        public static CharList CreateAllocated()
        {
            return new CharList(16);
        }

        /// <summary>
        /// Initializes a new instance of the CharList class that is empty and has the default initial capacity.
        /// </summary>
        public CharList()
        {
            mItems = gEmptyArray;
        }

        /// <summary>
        /// Initializes a new instance of the CharList class that is empty and has the specified initial capacity.
        /// </summary>
        public CharList(int capacity)
        {
            ArgumentUtil.CheckNonNegative(capacity, "capacity");
            mItems = new char[capacity];
        }

        /// <summary>
        /// Initializes a new instance of the CharList class that contains elements copied from the specified array 
        /// and has sufficient capacity to accommodate the number of elements copied.
        /// </summary>
        public CharList(char[] array)
            : this(array, true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the CharList class that wraps the specified array or contains elements copied from 
        /// the specified array and has sufficient capacity to accommodate the number of elements copied. It is important
        /// not to use <paramref name="array"/> object outside if it is wrapped as its elements are not copied in this case
        /// and are used directly by the list.
        /// </summary>
        public CharList(char[] array, bool needCopy)
        {
            ArgumentUtil.CheckNotNull(array, "array");
            mSize = array.Length;

            if (needCopy)
            {
                mItems = new char[mSize];
                array.CopyTo(mItems, 0);
            }
            else
            {
                mItems = array;
            }
        }

        /// <summary>
        /// Initializes a new instance of the CharList class that contains elements copied from the specified CharList 
        /// and has sufficient capacity to accommodate the number of elements copied.
        /// </summary>
        public CharList(CharList list)
        {
            ArgumentUtil.CheckNotNull(list, "list");
            mItems = list.ToArray();
            mSize = list.mSize;
        }

        /// <summary>
        /// Adds an object to the end of the CharList.
        /// </summary>
        public void Add(char item)
        {
            EnsureCapacity(mSize + 1);
            mItems[mSize++] = item;
        }

        /// <summary>
        /// Adds the elements of the specified array to the end of the CharList.
        /// </summary>
        public void AddRange(char[] array)
        {
            InsertRange(mSize, array);
        }

        /// <summary>
        /// Adds the elements of the specified CharList to the end of this CharList.
        /// </summary>
        public void AddRange(CharList list)
        {
            InsertRange(mSize, list);
        }

        /// <summary>
        /// Searches the entire sorted CharList for an element using the default comparer and returns 
        /// the zero-based index of the element.
        /// </summary>
        public int BinarySearch(char item)
        {
            return BinarySearch(0, mSize, item);
        }

        /// <summary>
        /// Searches a range of elements in the sorted CharList for an element using the default comparer 
        /// and returns the zero-based index of the element.
        /// </summary>
        public int BinarySearch(int index, int count, char item)
        {
            CheckIndexRange(index, count);
            return ArrayUtil.BinarySearch(mItems, index, count, item);
        }

        /// <summary>
        /// Checks whether the given index specifies a valid position in this list. Throws if it is not.
        /// </summary>
        private void CheckIndex(int index)
        {
            ArgumentUtil.CheckRangeInclusive(index, 0, mSize - 1, "index");
        }

        /// <summary>
        /// Checks whether the given index specifies a valid position in this list for an insert operation. 
        /// Throws if it is not.
        /// </summary>
        private void CheckIndexInsert(int index)
        {
            // Note that insertions at the end are legal.
            ArgumentUtil.CheckRangeInclusive(index, 0, mSize, "index");
        }

        /// <summary>
        /// Checks whether the given index and count specify a valid range in this list. Throws if they are not.
        /// </summary>
        private void CheckIndexRange(int index, int count)
        {
            ArgumentUtil.CheckNonNegative(index, "index");
            ArgumentUtil.CheckNonNegative(count, "count");
            if (index + count > mSize)
                throw new ArgumentException("The given index or/and count specify an invalid offset length.");
        }

        /// <summary>
        /// Removes all elements from the CharList.
        /// </summary>
        public void Clear()
        {
            // Don't need to doc this but we clear the elements so that the gc can reclaim the references.
            Array.Clear(mItems, 0, mSize);
            mSize = 0;
        }

        /// <summary>
        /// Determines whether an element is in the CharList.
        /// </summary>
        public bool Contains(char item)
        {
            if (mSize == 0)
                return false;

            return (IndexOf(item) >= 0);
        }

        /// <summary>
        /// Copies the entire CharList to a compatible one-dimensional array, starting at the beginning 
        /// of the target array.
        /// </summary>
        public void CopyTo(char[] array)
        {
            CopyTo(array, 0);
        }

        /// <summary>
        /// Copies the entire CharList to a compatible one-dimensional array, starting at the specified index 
        /// of the target array.
        /// </summary>
        public void CopyTo(char[] array, int arrayIndex)
        {
            // Delegate rest of error checking to Array.Copy.
            Array.Copy(mItems, 0, array, arrayIndex, mSize);
        }

        /// <summary>
        /// Copies a range of elements from the CharList to a compatible one-dimensional array, starting at 
        /// the specified index of the target array.
        /// </summary>
        public void CopyTo(int index, char[] array, int arrayIndex, int count)
        {
            CheckIndexRange(index, count);

            // Delegate rest of error checking to Array.Copy.
            Array.Copy(mItems, index, array, arrayIndex, count);
        }

        /// <summary>
        /// Ensures that the capacity of this list is at least the given minimum
        /// value. If the currect capacity of the list is less than min, the
        /// capacity is increased to twice the current capacity or to min,
        /// whichever is larger.
        /// </summary>
        private void EnsureCapacity(int min)
        {
            if (mItems.Length >= min)
                return;

            int newCapacity = (mItems.Length == 0) ? DefaultCapacity : (mItems.Length * 2);
            if (newCapacity < min)
                newCapacity = min;

            Capacity = newCapacity;
        }

        /// <summary>
        /// Creates a shallow copy of a range of elements in the source CharList.
        /// </summary>
        public CharList GetRange(int index, int count)
        {
            CheckIndexRange(index, count);

            CharList list = new CharList(count);
            Array.Copy(mItems, index, list.mItems, 0, count);
            list.mSize = count;
            return list;
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the first occurrence 
        /// within the entire CharList.
        /// </summary>
        public int IndexOf(char item)
        {
            return IndexOf(item, 0);
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the first occurrence 
        /// within the range of elements in the CharList that extends from the specified index to 
        /// the last element.
        /// </summary>
        public int IndexOf(char item, int index)
        {
            return IndexOf(item, index, mSize - index);
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the first occurrence 
        /// within the range of elements in the CharList that starts at the specified index 
        /// and contains the specified number of elements.
        /// </summary>
        public int IndexOf(char item, int index, int count)
        {
            CheckIndexRange(index, count);
            return Array.IndexOf(mItems, item, index, count);
        }

        /// <summary>
        /// Inserts an element into the CharList at the specified index.
        /// </summary>
        public void Insert(int index, char item)
        {
            CheckIndexInsert(index);
            EnsureCapacity(mSize + 1);

            if (index < mSize)
                Array.Copy(mItems, index, mItems, index + 1, mSize - index);

            mItems[index] = item;
            mSize++;
        }

        /// <summary>
        /// Inserts the elements of an array into the CharList at the specified index.
        /// </summary>
        public void InsertRange(int index, char[] array)
        {
            ArgumentUtil.CheckNotNull(array, "array");
            InsertRange(index, array, array.Length);
        }

        /// <summary>
        /// Inserts the elements of a CharList into this CharList at the specified index.
        /// </summary>
        public void InsertRange(int index, CharList list)
        {
            ArgumentUtil.CheckNotNull(list, "list");
            InsertRange(index, list.mItems, list.mSize);
        }

        /// <summary>
        /// Inserts the specified number of elements of a CharList into this CharList at the specified index.
        /// </summary>
        private void InsertRange(int index, char[] array, int count)
        {
            CheckIndexInsert(index);
            if (count == 0)
                return;

            EnsureCapacity(mSize + count);
            if (index < mSize)
                Array.Copy(mItems, index, mItems, index + count, mSize - index);

            // If we're inserting a CharList into itself, we want to be able to deal with that.
            if (mItems == array)
            {
                // Copy first part of mItems to insert location
                Array.Copy(mItems, 0, mItems, index, index);
                // Copy last part of mItems back to inserted location
                Array.Copy(mItems, index + count, mItems, index * 2, mSize - index);
            }
            else
            {
                Array.Copy(array, 0, mItems, index, count);
            }

            mSize += count;
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the last occurrence 
        /// within the entire CharList.
        /// </summary>
        public int LastIndexOf(char item)
        {
            return LastIndexOf(item, mSize - 1);
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the last occurrence 
        /// within the range of elements in the CharList that extends from the first element 
        /// to the specified index.
        /// </summary>
        public int LastIndexOf(char item, int index)
        {
            return LastIndexOf(item, index, index + 1);
        }

        /// <summary>
        /// Searches for the specified object and returns the zero-based index of the last occurrence 
        /// within the range of elements in the CharList that contains the specified number of elements 
        /// and ends at the specified index.
        /// </summary>
        public int LastIndexOf(char item, int index, int count)
        {
            CheckIndex(index);
            int invertedIndex = mSize - 1 - index; // Invert the index to perform the range check.
            CheckIndexRange(invertedIndex, count);
            return Array.LastIndexOf(mItems, item, index, count);
        }

        /// <summary>
        /// Removes the first occurrence of a specific object from the CharList.
        /// </summary>
        public bool Remove(char item)
        {
            int index = IndexOf(item);
            if (index >= 0)
            {
                RemoveAt(index);
                return true;
            }

            return false;
        }

        /// <summary>
        /// Removes the element at the specified index of the CharList.
        /// </summary>
        public void RemoveAt(int index)
        {
            CheckIndex(index);

            mSize--;
            if (index < mSize)
                Array.Copy(mItems, index + 1, mItems, index, mSize - index);

            mItems[mSize] = gDefaultValue;
        }

        /// <summary>
        /// Removes a range of elements from the CharList.
        /// </summary>
        public void RemoveRange(int index, int count)
        {
            CheckIndexRange(index, count);
            if (count == 0)
                return;

            mSize -= count;
            if (index < mSize)
                Array.Copy(mItems, index + count, mItems, index, mSize - index);

            Array.Clear(mItems, mSize, count);
        }

        /// <summary>
        /// Reverses the order of the elements in the entire CharList.
        /// </summary>
        public void Reverse()
        {
            Reverse(0, mSize);
        }

        /// <summary>
        /// Reverses the order of the elements in the specified range.
        /// </summary>
        public void Reverse(int index, int count)
        {
            CheckIndexRange(index, count);
            Array.Reverse(mItems, index, count);
        }

        /// <summary>
        /// Sorts the elements in the entire CharList using the default comparer.
        /// </summary>
        public void Sort()
        {
            Sort(0, mSize);
        }

        /// <summary>
        /// Sorts the elements in a range of elements in CharList using the default comparer.
        /// </summary>
        public void Sort(int index, int count)
        {
            CheckIndexRange(index, count);
            Array.Sort(mItems, index, count);
        }

        /// <summary>
        /// Copies the elements of the CharList to a new array.
        /// </summary>
        public char[] ToArray()
        {
            char[] array = new char[mSize];
            Array.Copy(mItems, 0, array, 0, mSize);
            return array;
        }

        public override string ToString()
        {
            // This is helpful for debugging.
            StringBuilder builder = new StringBuilder();

            for (int i = 0; i < mSize; i++)
            {
                if (i != 0)
                    builder.Append(" ");

                builder.Append(mItems[i]);
            }

            return builder.ToString();
        }

        /// <summary>
        /// Sets the capacity to the actual number of elements in the CharList, if that number is less than 
        /// a threshold value.
        /// </summary>
        public void TrimExcess()
        {
            int threshold = (int)(((double)mItems.Length) * 0.9);
            if (mSize < threshold)
                Capacity = mSize;
        }

        /// <summary>
        /// Gets or sets the total number of elements the internal data structure can hold without resizing.
        /// </summary>
        public int Capacity
        {
            get { return mItems.Length; }
            set
            {
                if (value == mItems.Length)
                    return;

                ArgumentUtil.CheckNonNegative(value, "value");
                if (value < mSize)
                    throw new ArgumentOutOfRangeException("value", "The specified capacity is less than the current size.");

                if (value > 0)
                {
                    char[] newItems = new char[value];
                    if (mSize > 0)
                        Array.Copy(mItems, 0, newItems, 0, mSize);

                    mItems = newItems;
                }
                else
                {
                    mItems = gEmptyArray;
                }
            }
        }

        /// <summary>
        /// Gets the number of elements actually contained in the CharList.
        /// </summary>
        public int Count
        {
            get { return mSize; }
        }

        /// <summary>
        /// Gets or sets the element at the specified index.
        /// </summary>
        public char this[int index]
        {
            get
            {
                CheckIndex(index);
                return mItems[index];
            }
            set
            {
                CheckIndex(index);
                mItems[index] = value;
            }
        }

        internal bool Equals(CharList rhs)
        {
            if (ReferenceEquals(null, rhs))
                return false;
            if (ReferenceEquals(this, rhs))
                return true;

            if (Count != rhs.Count)
                return false;

            for (int i = 0; i < Count; i++)
            {
                if (this[i] != rhs[i])
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Determines whether the specified object is equal in value to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != typeof(CharList))
                return false;

            return Equals((CharList)obj);
        }

        public override int GetHashCode()
        {
            int hashCode = 0;
            foreach (char value in mItems)
                hashCode = unchecked((hashCode * 397) ^ value.GetHashCode());
            return hashCode;
        }

        private char[] mItems;
        private int mSize;

        private static readonly char[] gEmptyArray = new char[0];

        // The default item value. The field is not readonly to satisfy Java final.
        private static char gDefaultValue;

        private const int DefaultCapacity = 4;
    }
}
