// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 12/06/2006 by Vladimir Averkin

using System;
using System.Text;
using Aspose.Common;
using Aspose.Words.Nrx;
using Aspose.Words.Properties;
using Aspose.Words.Settings;
using Aspose.Xml;

namespace Aspose.Words.RW.Nrx.Writer
{
    /// <summary>
    /// Helper methods to writes document properties to DOCX, WordML, HTML and RTF.
    /// This class is static.
    /// </summary>
    internal static class NrxDocPropertiesWriter
    {
        /// <summary>
        /// Write built-in and custom document properties in the WordML and HTML format.
        /// isInsideHtmlComment is used when writing in HTML since properties are written within
        /// comments and HTML comments don't allow "--" inside.
        /// </summary>
        internal static void WriteWml(Document doc, IAnyXmlBuilder builder, bool isInsideHtmlComment)
        {
            WriteBuiltInPropertiesWml(doc.BuiltInDocumentProperties, builder, isInsideHtmlComment);
            WriteCustomPropertiesWml(doc.CustomDocumentProperties, builder, isInsideHtmlComment);
        }

        private static void WriteBuiltInPropertiesWml(BuiltInDocumentProperties props, IAnyXmlBuilder builder, bool isInsideHtmlComment)
        {
            builder.StartElement("o:DocumentProperties");

            WriteOptionalStringElement(builder, "o:Title", props.Title, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:Subject", props.Subject, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:Author", props.Author, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:Keywords", props.Keywords, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:Description", props.Comments, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:LastAuthor", props.LastSavedBy, isInsideHtmlComment);
            builder.WriteElement("o:Revision", props.RevisionNumber);

            // o:AppName is the name of the application that last updated the document.
            // Word and Excel do not update this element.
            // MS Word even treats o:AppName element in WordML as an error, so we do not write it here.

            builder.WriteElement("o:TotalTime", props.TotalEditingTime);
            builder.WriteOptionalElement("o:LastPrinted", props.LastPrinted);
            builder.WriteOptionalElement("o:Created", props.CreatedTime);
            builder.WriteOptionalElement("o:LastSaved", props.LastSavedTime);
            builder.WriteElement("o:Pages", props.Pages);
            builder.WriteElement("o:Words", props.Words);
            builder.WriteElement("o:Characters", props.Characters);
            WriteOptionalStringElement(builder, "o:Category", props.Category, isInsideHtmlComment);

            // o:PresentationFormat element is not used in WordML.
            // Possible values: "On-screen Show", "A4 Paper (210x297 mm), etc.". Probably is for PowerPoint only.

            WriteOptionalStringElement(builder, "o:Manager", props.Manager, isInsideHtmlComment);
            WriteOptionalStringElement(builder, "o:Company", props.Company, isInsideHtmlComment);

            // TODO 3 o:Guid element is skipped now.
            // Don't know where to get it, have not seen it in WordML generated by MS Word yet.

            WriteOptionalStringElement(builder, "o:HyperlinkBase", props.HyperlinkBase, isInsideHtmlComment);

            DocumentProperty bytesProp = props[PropertyName.Bytes];
            if ((bytesProp.DefaultValueInternal == null) && (bytesProp.ToInt() > 0))
                builder.WriteElement("o:Bytes", props.Bytes);

            builder.WriteElement("o:Lines", props.Lines);
            builder.WriteElement("o:Paragraphs", props.Paragraphs);
            builder.WriteElement("o:CharactersWithSpaces", props.CharactersWithSpaces);

            builder.WriteElement("o:Version", NrxXmlUtil.VersionNumberToXml(props.Version));

            builder.EndElement(); //o:DocumentProperties
        }

        private static void WriteOptionalStringElement(IAnyXmlBuilder builder, string elementName, string value, bool isInsideHtmlComment)
        {
            builder.WriteOptionalElement(elementName, PrepareStringValue(value, isInsideHtmlComment));
        }

        private static string PrepareStringValue(string value, bool isInsideHtmlComment)
        {
            // Adding "\\&#x2d;\\&#x2d;" gives the same result here. Let's add resilience with a minus and a single space.
            // This will safely handle sequences of more than two minuses.
            // MS Word writes two minuses as "&#45;-". How can we escase this way? Maybe we should switch to using 
            // XmlTextWriter.WriteComment when writing anything inside comments.
            return isInsideHtmlComment ? value.Replace("--", "- ") : value;
        }

        private static void WriteCustomPropertiesWml(CustomDocumentProperties props, IAnyXmlBuilder builder, bool isInsideHtmlComment)
        {
            if (!HasWritableProperties(props))
                return;

            builder.StartElement("o:CustomDocumentProperties");
            
            foreach (DocumentProperty prop in props)
            {
                if (IsWritableProperty(prop))
                    WriteCustomPropertyWml(prop, builder, isInsideHtmlComment);
            }
            
            builder.EndElement(); //o:CustomDocumentProperties
        }

        private static void WriteCustomPropertyWml(DocumentProperty prop, IAnyXmlBuilder builder, bool isInsideHtmlComment)
        {
            builder.StartElement(MakePropertyNameWml(prop.Name));

            switch (prop.Type)
            {
                case PropertyType.Boolean:
                    builder.WriteAttributeString("dt:dt", "boolean");
                    builder.WriteString(prop.ToBool() ? "1" : "0");
                    break;
                case PropertyType.Number:
                    builder.WriteAttributeString("dt:dt", "float");
                    if (StringUtil.HasChars(prop.LinkTarget))
                        builder.WriteAttributeString("link", prop.LinkTarget);
                    builder.WriteString(prop.ToString());
                    break;
                case PropertyType.Double:
                    builder.WriteAttributeString("dt:dt", "float");
                    if (StringUtil.HasChars(prop.LinkTarget))
                        builder.WriteAttributeString("link", prop.LinkTarget);
                    builder.WriteString(FormatterPal.DoubleToStr(prop.ToDouble()));
                    break;
                case PropertyType.String:
                    builder.WriteAttributeString("dt:dt", "string");
                    // Only a text property can be a link target.
                    if (StringUtil.HasChars(prop.LinkTarget))
                        builder.WriteAttributeString("link", prop.LinkTarget);
                    builder.WriteString(PrepareStringValue(prop.ToString(), isInsideHtmlComment));
                    break;
                case PropertyType.DateTime:
                    builder.WriteAttributeString("dt:dt", "dateTime.tz");
                    builder.WriteString(FormatterPal.DateTimeToXmlUtc(prop.ToDateTime()));
                    break;
                default:
                    throw new InvalidOperationException("Unexpected property type.");
            }

            builder.EndElement();
        }

        /// <summary>
        /// Only alphanumeric strings are allowed as element names in XML.
        /// All other characters should be converted to hex representation.
        /// For example "Some name" should be converted to "Some_x0020_Name".
        /// </summary>
        private static string MakePropertyNameWml(string name)
        {
            StringBuilder sb = new StringBuilder("o:");

            for (int i = 0; i < name.Length; i++)
            {
                char ch = name[i];
                if (IsValidChar(ch, i == 0))
                    sb.Append(ch);
                else
                {
                    sb.Append("_x");
                    sb.Append(FormatterPal.IntToStrX4(ch));
                    sb.Append('_');
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// Determines whether the specified character is a valid character for a property name.
        /// For details, see https://www.w3.org/TR/REC-xml/#NT-NameStartChar.
        /// Note, that we excluded colon marked as permissible but it produced corrupted document.
        /// </summary>
        private static bool IsValidChar(char ch, bool isFirst)
        {
            // WORDSNET-26913 According to the documentation, a property name
            // can start with a letter or underline.
            if (char.IsLetter(ch) || ch == '_')
                return true;
            // Next characters can also contain digits, dashes and periods
            // without converting to hex.
            if (!isFirst && (char.IsDigit(ch) || ch == '-' || ch == '.'))
                return true;

            return false;
        }

        internal static bool HasWritableProperties(CustomDocumentProperties props)
        {
            foreach (DocumentProperty prop in props)
            {
                if (IsWritableProperty(prop))
                    return true;
            }
            return false;
        }

        /// <summary>
        /// Check if the custom document property is one of the properties we are writing to DOCX, RTF and WML.
        /// MS Word filters out some of the custom properties found in DOC files.
        /// </summary>
        internal static bool IsWritableProperty(DocumentProperty prop)
        {
            if (prop.Name.StartsWith("_PID_", StringComparison.Ordinal))
                return false;

            return IsWritableType(prop.Type);
        }

        private static bool IsWritableType(PropertyType type)
        {
            switch (type)
            {
                case PropertyType.Boolean:
                case PropertyType.DateTime:
                case PropertyType.Double:
                case PropertyType.Number:
                case PropertyType.String:
                    return true;
                case PropertyType.Other:
                default:
                    return false;
            }
        }

        internal static void WriteNoLineBreaks(DocPr docPr, NrxXmlBuilder builder, string lang)
        {
            if (StringUtil.HasChars(docPr.NoLineBreaksAfter))
            {
                builder.WriteElementWithAttributes(
                    "w:noLineBreaksAfter",
                    "w:lang", lang,
                    "w:val", docPr.NoLineBreaksAfter);
            }

            if (StringUtil.HasChars(docPr.NoLineBreaksBefore))
            {
                builder.WriteElementWithAttributes(
                    "w:noLineBreaksBefore",
                    "w:lang", lang,
                    "w:val", docPr.NoLineBreaksBefore);
            }
        }
    }
}
