// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 01/04/2016 by Konstantin Kornilov

namespace Aspose.Words.Drawing.Core.Dml.Diagrams.SimpleTypes
{
    /// <summary>
    /// 21.4.7.21 ST_ConstraintType (Constraint Type)
    /// </summary>
    internal enum DmlConstraintType
    {
        None,
        AlignmentOffset,
        Bottom,
        BeginningMargin,
        BeginPadding,
        BendingDistance,
        BottomMargin,
        BottomOffset,
        ConnectionDistance,
        CenterX,
        CenterXOffset,
        CenterY,
        CenterYOffset,
        Diameter,
        EndMargin,
        EndPadding,
        Height,
        ArrowheadHeight,
        HeightOffset,
        Left,
        LeftMargin,
        LeftOffset,
        PrimaryFontSize,
        PyramidAccentRatio,
        Right,
        RightMargin,
        RightOffset,
        SecondaryFontSize,
        SecondarySiblingSpacing,
        SiblingSpacing,
        Spacing,
        StemThickness,
        Top,
        TopMargin,
        TopOffset,
        UserA,
        UserB,
        UserC,
        UserD,
        UserE,
        UserF,
        UserG,
        UserH,
        UserI,
        UserJ,
        UserK,
        UserL,
        UserM,
        UserN,
        UserO,
        UserP,
        UserQ,
        UserR,
        UserS,
        UserT,
        UserU,
        UserV,
        UserW,
        UserX,
        UserY,
        UserZ,
        Width,
        ArrowheadWidth,
        WidthOffset
    }
}
