// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 31/07/2007 by Vladimir Averkin
using System;
using System.ComponentModel;
using Aspose.IO;
using Aspose.OpcPackaging;
using Aspose.Words.Nrx;
using Aspose.Words.RW.Nrx.Writer;
using Aspose.Words.Saving;
using Aspose.Words.Themes;

namespace Aspose.Words.RW.Docx.Writer
{
    /// <summary>
    /// Writers the main document to an OOXML part.
    /// </summary>
    internal class DocxDocumentWriter : DocxDocumentWriterBase
    {
        internal DocxDocumentWriter(DocxWriter writer, TempFiler tempFiler) :
            base(writer, writer.Document, writer.WarningCallback)
        {
            mTempFiler = tempFiler;
        }

        protected override OpcPackagePart DoCreateDocumentPart()
        {
            OpcPackagePart part = Package.CreateChildPart(null, "/word/document.xml", GetDocumentPartContentType(), RelTypes.OfficeDocument);
            // Create either FileStream or MemoryStream depending on SaveOption.TempFolder.
            // Avoid to recreate MemoryStream.
            if (mTempFiler.IsTempFilesEnabled)
                part.Stream = mTempFiler.GetNewStream();
            return part;
        }

        private string GetDocumentPartContentType()
        {
            switch (SaveInfo.SaveFormat)
            {
                case SaveFormat.Docx:
                case SaveFormat.FlatOpc:
                    return DocxContentType.Document;
                case SaveFormat.Docm:
                case SaveFormat.FlatOpcMacroEnabled:
                    return DocxContentType.DocumentMacroEnabled;
                case SaveFormat.Dotx:
                case SaveFormat.FlatOpcTemplate:
                    return DocxContentType.Template;
                case SaveFormat.Dotm:
                case SaveFormat.FlatOpcTemplateMacroEnabled:
                    return DocxContentType.TemplateMacroEnabled;
                default:
                    throw new InvalidOperationException("Unexpected file format.");
            }
        }

        protected override void DoWrite()
        {
            DocxCustomXmlPartWriter.Write(this);
            WriteDocument();
            DocxVbaWriter.Write(this);
            DocxCustomizationsWriter.Write(this);
            WriteGlossary();
            WriteTheme();
        }

        private void WriteDocument()
        {
            Document doc = SaveInfo.Document;
            ProgressProcessor = new SavingProgressProcessor(doc, SaveOptions, SavingStageType.Saving);

            DocxBuilder builder = CurrentBuilder;
            builder.StartDocumentWithStandardNamespaces("w:document");

            if (Compliance == OoxmlComplianceCore.IsoStrict)
                builder.WriteAttribute("w:conformance", "strict");

            if (SaveOptions.ExportGeneratorName)
                builder.WriteComment(string.Format(" Generated by {0} ", AssemblyConstants.GeneratorName));

            DocxBackgroundWriter.Write(this);

            builder.StartElement("w:body");
            WriteSections(doc);

            // Only section properties for the last section should be written from here.
            // Section properties for the other sections are written in the last paragraphs of these sections.
            if (CurrentSection.IsLastChild)
                NrxSectPrWriter.Write(CurrentSection, this);

            builder.EndElement("w:body");   // body

            builder.EndDocument();

            ProgressProcessor.Complete();
            // Reset reference to avoid progress call invocation for the glossary document.
            ProgressProcessor = null;
        }

        private void WriteGlossary()
        {
            CompositeNode glossary = SaveInfo.Document.GlossaryDocument;
            if ((glossary == null) || (!glossary.HasChildNodes))
                return;

            DocxGlossaryWriter glossaryWriter = new DocxGlossaryWriter(Writer);
            glossaryWriter.Write();
        }

        private void WriteTheme()
        {
            WriteTheme(SaveInfo.Document.GetThemeInternal(), this, false);
        }

        internal static void WriteTheme(Theme theme, DocxDocumentWriterBase writer, bool isThemeOverride)
        {
            if (theme == null)
                return;

            string contentType = isThemeOverride ? DocxContentType.ThemeOverride : DocxContentType.Theme;
            string relType = isThemeOverride ? writer.RelTypes.ThemeOverride : writer.RelTypes.Theme;
            int partNumber = writer.GetNextEmbeddedPartNumber(relType);
            string partName = isThemeOverride
                ? string.Format("../theme/themeOverride{0}.xml", partNumber)
                : string.Format("theme/theme{0}.xml", partNumber);

            OpcPackagePart parentPart = isThemeOverride ? writer.CurrentBuilder.Part : writer.DocumentPart;

            OpcPackagePart newThemePart;
            // If theme is not modified and format is not changed, we use unparsed stream.
            if (theme.IsModified ||
                theme.ThemeNamespace != DocxNamespaces.GetNamespace(DocxNamespace.DrawingMLMain,
                    writer.Compliance == OoxmlComplianceCore.IsoStrict))
            {
                string dummyRelId;
                DocxBuilder builder = writer.CreateChildPartAndBuilder(parentPart, partName, contentType, relType,
                    out dummyRelId);
                newThemePart = builder.Part;

                writer.PushBuilder(builder);
                ThemeWriter.Write(writer, theme, isThemeOverride);
                writer.PopBuilder();
            }
            else
            {
                newThemePart = writer.Package.CreateChildPart(parentPart, partName, contentType, relType);
                newThemePart.Stream = theme.ThemePart.Stream;
            }

            WriteUnparsedRels(theme.ThemePart, theme.RelatedParts, newThemePart, writer);
        }

        [CodePorting.Translator.Cs2Cpp.CppRenameEntity("Doc")] // Rename for C++, 'new' keyword is not properly handled.
        [EditorBrowsable(EditorBrowsableState.Never)]
        public new Document Document    // Reexpose this as a main document. Needs to be public for autoporting to work.
        {
            get { return (Document)base.Document; }
        }

        private readonly TempFiler mTempFiler;
    }
}
