// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 01/05/2013 by Konstantin Kornilov

using Aspose.Words.Drawing.Core.Dml.Diagrams.ComplexTypes;

namespace Aspose.Words.Drawing.Core.Dml.Diagrams
{
    /// <summary>
    /// 21.4.2.10 dataModel (Data Model)
    /// </summary>
    internal class DmlDiagramDataModel : DmlExtensionListSource
    {
        internal DmlDiagramPoint[] PointList
        {
            get { return mPointList; }
            set { mPointList = value; }
        }

        internal DmlDiagramConnection[] ConnectionList
        {
            get { return mConnectionList; }
            set { mConnectionList = value; }
        }

        internal ShapeBase Drawing
        {
            get { return mDrawing; }
            set { mDrawing = value; }
        }
        
        /// <summary>
        /// True if drawing is generated by our cold rendering.
        /// </summary>
        internal bool ColdRenderedDrawing { get; set; }

        internal DmlDiagramWholeFormatting WholeFormatting
        {
            get { return mWholeFormatting; }
            set { mWholeFormatting = value; }
        }

        internal DmlDiagramBackground Background
        {
            get { return mBackground; }
            set { mBackground = value; }
        }

        /// <summary>
        /// Used for sample data only.
        /// </summary>
        internal bool UseDefault
        {
            get { return mUseDefault; }
            set { mUseDefault = value; }
        }

        /// <summary>
        /// Specifies diagram drawing relId.
        /// </summary>
        internal string DrawingId
        {
            get { return mDrawingId; }
            set { mDrawingId = value; }
        }

        private bool mUseDefault;
        private DmlDiagramPoint[] mPointList;
        private DmlDiagramConnection[] mConnectionList;
        private ShapeBase mDrawing;
        private DmlDiagramWholeFormatting mWholeFormatting;
        private DmlDiagramBackground mBackground;
        private string mDrawingId;
    }
}
