// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 17/07/2010 by Roman Korchagin

namespace Aspose
{
    /// <summary>
    /// Specifies just the language (without a country). It seems to be the lower byte of the <see cref="Language"/> value.
    /// </summary>
    [CodePorting.Translator.Cs2Cpp.CppConstexpr]
    [CodePorting.Translator.Cs2Cpp.CppForceInclude("Aspose.Language", true)]
    public static class LanguageOnly
    {
        // ReSharper disable IdentifierTypo
        // The constants below are generated by TestLanguageOnly.GenerateLanguageOnlyConstants
        public const int Arabic = (int)Language.Arabic & 0xff;
        public const int Bulgarian = (int)Language.Bulgarian & 0xff;
        public const int Catalan = (int)Language.Catalan & 0xff;
        public const int Chinese = (int)Language.ChineseSimplified & 0xff;
        public const int Czech = (int)Language.Czech & 0xff;
        public const int Danish = (int)Language.Danish & 0xff;
        public const int German = (int)Language.German & 0xff;
        public const int Greek = (int)Language.Greek & 0xff;
        public const int English = (int)Language.English & 0xff;
        public const int Spanish = (int)Language.Spanish & 0xff;
        public const int Finnish = (int)Language.Finnish & 0xff;
        public const int French = (int)Language.French & 0xff;
        public const int Hebrew = (int)Language.Hebrew & 0xff;
        public const int Hungarian = (int)Language.Hungarian & 0xff;
        public const int Icelandic = (int)Language.Icelandic & 0xff;
        public const int Italian = (int)Language.Italian & 0xff;
        public const int Japanese = (int)Language.Japanese & 0xff;
        public const int Korean = (int)Language.Korean & 0xff;
        public const int Dutch = (int)Language.Dutch & 0xff;
        public const int Norwegian = (int)Language.Norwegian & 0xff;
        public const int Polish = (int)Language.Polish & 0xff;
        public const int Portuguese = (int)Language.Portuguese & 0xff;
        public const int Romanian = (int)Language.Romanian & 0xff;
        public const int Russian = (int)Language.Russian & 0xff;
        public const int Croatian = (int)Language.Croatian & 0xff;
        public const int Slovak = (int)Language.Slovak & 0xff;
        public const int Albanian = (int)Language.Albanian & 0xff;
        public const int Swedish = (int)Language.Swedish & 0xff;
        public const int Thai = (int)Language.Thai & 0xff;
        public const int Turkish = (int)Language.Turkish & 0xff;
        public const int Indonesian = (int)Language.Indonesian & 0xff;
        public const int Ukrainian = (int)Language.Ukrainian & 0xff;
        public const int Belarusian = (int)Language.Belarusian & 0xff;
        public const int Slovenian = (int)Language.Slovenian & 0xff;
        public const int Estonian = (int)Language.Estonian & 0xff;
        public const int Latvian = (int)Language.Latvian & 0xff;
        public const int Lithuanian = (int)Language.Lithuanian & 0xff;
        public const int Vietnamese = (int)Language.Vietnamese & 0xff;
        public const int Armenian = (int)Language.Armenian & 0xff;
        public const int Azeri = (int)Language.Azeri & 0xff;
        public const int Basque = (int)Language.Basque & 0xff;
        public const int Macedonian = (int)Language.Macedonian & 0xff;
        public const int Afrikaans = (int)Language.Afrikaans & 0xff;
        public const int Georgian = (int)Language.Georgian & 0xff;
        public const int Faeroese = (int)Language.Faeroese & 0xff;
        public const int Hindi = (int)Language.Hindi & 0xff;
        public const int Malay = (int)Language.Malay & 0xff;
        public const int Kazakh = (int)Language.Kazakh & 0xff;
        public const int Kyrgyz = (int)Language.Kyrgyz & 0xff;
        public const int Kiswahili = (int)Language.Kiswahili & 0xff;
        public const int Uzbek = (int)Language.Uzbek & 0xff;
        public const int Tatar = (int)Language.Tatar & 0xff;
        public const int Punjabi = (int)Language.Punjabi & 0xff;
        public const int Gujarati = (int)Language.Gujarati & 0xff;
        public const int Tamil = (int)Language.Tamil & 0xff;
        public const int Telugu = (int)Language.Telugu & 0xff;
        public const int Kannada = (int)Language.Kannada & 0xff;
        public const int Marathi = (int)Language.Marathi & 0xff;
        public const int Sanskrit = (int)Language.Sanskrit & 0xff;
        public const int Mongolian = (int)Language.Mongolian & 0xff;
        public const int Galician = (int)Language.Galician & 0xff;
        public const int Konkani = (int)Language.Konkani & 0xff;
        public const int Syriac = (int)Language.Syriac & 0xff;
        public const int Divehi = (int)Language.Divehi & 0xff;
        public const int NoProof = (int)Language.NoProof & 0xff;
        public const int RomanshSwitzerland = (int)Language.RomanshSwitzerland & 0xff;
        public const int Urdu = (int)Language.Urdu & 0xff;
        public const int Tajik = (int)Language.Tajik & 0xff;
        public const int Persian = (int)Language.Persian & 0xff;
        public const int Sorbian = (int)Language.Sorbian & 0xff;
        public const int Sutu = (int)Language.Sutu & 0xff;
        public const int Tsonga = (int)Language.Tsonga & 0xff;
        public const int Tswana = (int)Language.Tswana & 0xff;
        public const int Venda = (int)Language.Venda & 0xff;
        public const int Xhosa = (int)Language.Xhosa & 0xff;
        public const int Zulu = (int)Language.Zulu & 0xff;
        public const int Maltese = (int)Language.Maltese & 0xff;
        public const int SamiNorthernNorway = (int)Language.SamiNorthernNorway & 0xff;
        public const int GaelicScotland = (int)Language.GaelicScotland & 0xff;
        public const int Yiddish = (int)Language.Yiddish & 0xff;
        public const int Turkmen = (int)Language.Turkmen & 0xff;
        public const int Bengali = (int)Language.Bengali & 0xff;
        public const int Oriya = (int)Language.Oriya & 0xff;
        public const int Malayalam = (int)Language.Malayalam & 0xff;
        public const int Assamese = (int)Language.Assamese & 0xff;
        public const int Tibetan = (int)Language.TibetanChina & 0xff;
        public const int Welsh = (int)Language.Welsh & 0xff;
        public const int Khmer = (int)Language.Khmer & 0xff;
        public const int Lao = (int)Language.Lao & 0xff;
        public const int Burmese = (int)Language.Burmese & 0xff;
        public const int Manipuri = (int)Language.Manipuri & 0xff;
        public const int Devangari = (int)Language.SindhiDevanagaric & 0xff;
        public const int Sinhalese = (int)Language.Sinhalese & 0xff;
        public const int Cherokee = (int)Language.Cherokee & 0xff;
        public const int Inuktitut = (int)Language.Inuktitut & 0xff;
        public const int Amharic = (int)Language.Amharic & 0xff;
        public const int Tamazight = (int)Language.Tamazight & 0xff;
        public const int KashmiriArabic = (int)Language.KashmiriArabic & 0xff;
        public const int Nepali = (int)Language.Nepali & 0xff;
        public const int FrisianNetherlands = (int)Language.FrisianNetherlands & 0xff;
        public const int Pashto = (int)Language.Pashto & 0xff;
        public const int Filipino = (int)Language.Filipino & 0xff;
        public const int Edo = (int)Language.Edo & 0xff;
        public const int Fulfulde = (int)Language.Fulfulde & 0xff;
        public const int Hausa = (int)Language.Hausa & 0xff;
        public const int Ibibio = (int)Language.Ibibio & 0xff;
        public const int Yoruba = (int)Language.Yoruba & 0xff;
        public const int QuechuaBolivia = (int)Language.QuechuaBolivia & 0xff;
        public const int Sepedi = (int)Language.Sepedi & 0xff;
        public const int LuxembougishLuxemburg = (int)Language.LuxembougishLuxemburg & 0xff;
        public const int Igbo = (int)Language.Igbo & 0xff;
        public const int Kanuri = (int)Language.Kanuri & 0xff;
        public const int Oromo = (int)Language.Oromo & 0xff;
        public const int Ethiopian = (int)Language.TigrignaEthiopia & 0xff;
        public const int Guarani = (int)Language.Guarani & 0xff;
        public const int Hawaiian = (int)Language.Hawaiian & 0xff;
        public const int Latin = (int)Language.Latin & 0xff;
        public const int Somali = (int)Language.Somali & 0xff;
        public const int Yi = (int)Language.Yi & 0xff;
        public const int Papiamentu = (int)Language.Papiamentu & 0xff;
        public const int MapudungunChile = (int)Language.MapudungunChile & 0xff;
        public const int MohawkMohawk = (int)Language.MohawkMohawk & 0xff;
        public const int Breton = (int)Language.Breton & 0xff;
        public const int Maori = (int)Language.Maori & 0xff;
        public const int Alsatian = (int)Language.Alsatian & 0xff;
        // ReSharper restore IdentifierTypo

        /// <summary>
        /// Compares language codes without country.
        /// </summary>
        public static bool Compare(int langFirst, int langSecond)
        {
            return ToLanguageOnly(langFirst) == ToLanguageOnly(langSecond);
        }

        /// <summary>
        /// Extracts a part from locale ID that unique identifies a language group.
        /// </summary>
        public static int ToLanguageOnly(int locale)
        {
            return locale & 0xff;
        }
    }
}
