// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.
// 06/05/2005 by Roman Korchagin

using System;
using System.ComponentModel;
using Aspose.Common;
using Aspose.Drawing;
using Aspose.JavaAttributes;
using Aspose.Words.Drawing.Core.Dml.Themes;
using Aspose.Words.Themes;

namespace Aspose.Words
{
    /// <summary>
    /// Contains shading attributes for an object.
    /// <para>To learn more, visit the <a href="https://docs.aspose.com/words/net/programming-with-documents/">Programming with Documents</a> documentation article.</para>
    /// </summary>
    /// <dev>
    /// This is a model and also presentation class that allows to see and modify shading attributes.
    /// </dev>
    public class Shading : InternableComplexAttr, IComplexAttr 
    {
        /// <summary>
        /// Creates a non-inherited shading.
        /// </summary>
        internal Shading()
        {
            ClearFormatting();
        }

        /// <summary>
        /// Creates an inherited shading.
        /// </summary>
        internal Shading(IShadingAttrSource parent, int key)
        {
            mParent = parent;
            mKey = key;
        }

        /// <summary>
        /// Removes shading from the object.
        /// </summary>
        public void ClearFormatting()
        {
            mParent = null;
            mTexture = TextureIndex.TextureNone;
            mForegroundPatternColor = DrColor.Empty;
            mBackgroundPatternColor = DrColor.Empty;
            mThemeColor = null;
            mThemeShade = null;
            mThemeTint = null;
            mThemeFill = null;
            mThemeFillShade = null;
            mThemeFillTint = null;
        }

        /// <summary>
        /// Determines whether the specified <see cref="Shading"/> is equal in value to the current <see cref="Shading"/>.
        /// </summary>
        [JavaConvertCheckedExceptions]
        public bool Equals(Shading rhs)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, rhs))
                return false;
            if (ReferenceEquals(this, rhs))
                return true;

            return
                (Texture == rhs.Texture) &&
                (ForegroundPatternColorInternal == rhs.ForegroundPatternColorInternal) &&
                (BackgroundPatternColorInternal == rhs.BackgroundPatternColorInternal) &&
                (ThemeColor == rhs.ThemeColor) &&
                (ThemeShade == rhs.ThemeShade) &&
                (ThemeTint == rhs.ThemeTint) &&
                (ThemeFill == rhs.ThemeFill) &&
                (ThemeFillShade == rhs.ThemeFillShade) &&
                (ThemeFillTint == rhs.ThemeFillTint);
        }

        /// <summary>
        /// Determines whether the specified object is equal in value to the current object.
        /// </summary>
        public override bool Equals(object obj)
        {
            // Generated by ReSharper.
            if (ReferenceEquals(null, obj))
                return false;
            if (ReferenceEquals(this, obj))
                return true;
            if (obj.GetType() != typeof(Shading))
                return false;
            return Equals((Shading)obj);
        }

        /// <summary>
        /// Serves as a hash function for this type. 
        /// </summary>
        /// <javaName>int hashCode()</javaName>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = (int)mTexture;
                result = (result * 397) ^ (mForegroundPatternColor != null ? mForegroundPatternColor.GetHashCode() : 0);
                result = (result * 397) ^ (mBackgroundPatternColor != null ? mBackgroundPatternColor.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeColor != null ? mThemeColor.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeShade != null ? mThemeShade.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeTint != null ? mThemeTint.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeFill != null ? mThemeFill.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeFillShade != null ? mThemeFillShade.GetHashCode() : 0);
                result = (result * 397) ^ (mThemeFillTint != null ? mThemeFillTint.GetHashCode() : 0);
                return result;
            }
        }

        /// <summary>
        /// Copies inherited border values into this border and stops inheriting.
        /// </summary>
        private void BeforeChange()
        {
            NotifyChanging();
            if (IsInherited)
            {
                //Copy all attrs from the inherited border.
                CopyFrom(Inherited);
                mParent = null;
            }
        }

        private void CopyFrom(Shading src)
        {
            if (src == null)
                throw new ArgumentNullException("src");

            // There is no sense in assigning mParent here in the code because this method is called
            // from StopInherit which resets mParent to null right after the call. Normally shading can be inherited
            // from its' parent (e.g. ParagraphFormat->Paragraph->RunPr) but it cannot be inherited from already inherited shading.
            mParent = src.mParent;
            mKey = src.mKey;
            mTexture = src.Texture;
            mForegroundPatternColor = src.ForegroundPatternColorInternal;
            mBackgroundPatternColor = src.BackgroundPatternColorInternal;
            mThemeColor = src.ThemeColor;
            mThemeShade = src.ThemeShade;
            mThemeTint = src.ThemeTint;
            mThemeFill = src.ThemeFill;
            mThemeFillShade = src.ThemeFillShade;
            mThemeFillTint = src.ThemeFillTint;
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        bool IComplexAttr.IsInheritedComplexAttr
        {
            get { return IsInherited; }
        }

        /// <summary>
        /// Reserved for system use. IComplexAttr.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Never)]
        IComplexAttr IComplexAttr.DeepCloneComplexAttr()
        {
            if (IsInherited)
                throw new InvalidOperationException("Cannot clone an inherited attribute.");
            return (Shading)MemberwiseClone();
        }

        internal bool IsInherited
        {
            get { return (mParent != null); }
        }

        /// <summary>
        /// Gets or sets the color that's applied to the background of the <see cref="Shading"/> object.
        /// </summary>
        public System.Drawing.Color BackgroundPatternColor
        {
            get { return BackgroundPatternColorInternal.ToNativeColor(); }
            set
            {
                BackgroundPatternColorInternal = DrColor.FromNativeColor(value);

                // WORDSNET-15143 Reset theme color when RGB color is set.
                mThemeFill = null;
                mThemeFillShade = null;
                mThemeFillTint = null;
            }
        }

        internal DrColor BackgroundPatternColorInternal
        {
            get { return (IsInherited) ? Inherited.BackgroundPatternColorInternal : mBackgroundPatternColor; }
            set
            {
                BeforeChange();
                mBackgroundPatternColor = value;
            }
        }

        /// <summary>
        /// Gets or sets the color that's applied to the foreground of the <see cref="Shading"/> object.
        /// </summary>
        public System.Drawing.Color ForegroundPatternColor
        {
            get { return ForegroundPatternColorInternal.ToNativeColor(); }
            set
            {
                ForegroundPatternColorInternal = DrColor.FromNativeColor(value);

                // WORDSNET-15143 Reset theme color when RGB color is set.
                mThemeColor = null;
                mThemeShade = null;
                mThemeTint = null;
            }
        }

        internal DrColor ForegroundPatternColorInternal
        {
            get { return (IsInherited) ? Inherited.ForegroundPatternColorInternal : mForegroundPatternColor; }
            set
            {
                BeforeChange();
                mForegroundPatternColor = value;
            }
        }

        /// <summary>
        /// Gets or sets the shading texture.
        /// </summary>
        public TextureIndex Texture
        {
            get { return (IsInherited) ? Inherited.Texture : mTexture; }
            set
            {
                BeforeChange();
                mTexture = value;
            }
        }

        /// <summary>
        /// Gets or sets the foreground pattern theme color in the applied color scheme that is associated with this <see cref="Shading"/> object.
        /// </summary>
        public ThemeColor ForegroundPatternThemeColor
        {
            get
            {
                return ThemeColorConverter.FromString(mThemeColor);
            }
            set
            {
                mThemeColor = ThemeColorConverter.ToString(value);
                mForegroundPatternColor = DrColor.Empty;
            }
        }

        /// <summary>
        /// Gets or sets the background pattern theme color in the applied color scheme that is associated with this <see cref="Shading"/> object.
        /// </summary>
        public ThemeColor BackgroundPatternThemeColor
        {
            get
            {
                return ThemeColorConverter.FromString(mThemeFill);
            }
            set
            {
                mThemeFill = ThemeColorConverter.ToString(value);
                mBackgroundPatternColor = DrColor.Empty;
            }
        }

        /// <summary>
        /// Gets or sets a double value that lightens or darkens a foreground theme color.
        /// </summary>
        /// <remarks>
        /// <para>The allowed values are in the range from -1 (the darkest) to 1 (the lightest) for this property.</para>
        /// <para>Zero (0) is neutral.</para>
        /// </remarks>
        /// <exception cref="ArgumentOutOfRangeException">Throw if set this property to a value less than -1 or more than 1.</exception>
        /// <exception cref="InvalidOperationException">Throw if set this property for Shading object with non-theme colors.</exception>
        public double ForegroundTintAndShade
        {
            get
            {
                // Note, Word stores inverted values (1 - tint) and (1 + shade) in the document.
                return StringUtil.HasChars(mThemeTint)
                    ? 1.0d - ((double)FormatterPal.ParseHex(mThemeTint) / 255)
                    : StringUtil.HasChars(mThemeShade)
                        ? -1.0d - ((double)FormatterPal.ParseHex(mThemeShade) / -255)
                        : 0.0d;
            }
            set
            {
                // ForegroundTintAndShade does not work for non-theme colors.
                if (!StringUtil.HasChars(ThemeColor))
                    throw new InvalidOperationException("ForegroundTintAndShade cannot be applied to a non-theme color.");

                ArgumentUtil.CheckRangeInclusive(value, -1.0d, 1.0d, "ForegroundTintAndShade");

                ThemeTint = null;
                ThemeShade = null;
                // Note, Word stores inverted value (1 - tint) in the document.
                if (value > 0)
                    ThemeTint = FormatterPal.IntToStrX2((int)((1 - value) * 255));
                // Note, Word stores inverted value (1 + shade) in the document.
                if (value < 0)
                    ThemeShade = FormatterPal.IntToStrX2((int)((-1 - value) * -255));
            }
        }

        /// <summary>
        /// Gets or sets a double value that lightens or darkens a background theme color.
        /// </summary>
        /// <remarks>
        /// <para>The allowed values are in the range from -1 (the darkest) to 1 (the lightest) for this property.</para>
        /// <para>Zero (0) is neutral.</para>
        /// </remarks>
        /// <exception cref="ArgumentOutOfRangeException">Throw if set this property to a value less than -1 or more than 1.</exception>
        /// <exception cref="InvalidOperationException">Throw if set this property for Shading object with non-theme colors.</exception>
        public double BackgroundTintAndShade
        {
            get
            {
                // Note, Word stores inverted values (1 - tint) and (1 + shade) in the document.
                return StringUtil.HasChars(mThemeFillTint)
                    ? 1.0d - ((double)FormatterPal.ParseHex(mThemeFillTint) / 255)
                    : StringUtil.HasChars(mThemeFillShade)
                        ? -1.0d - ((double)FormatterPal.ParseHex(mThemeFillShade) / -255)
                        : 0.0d;
            }
            set
            {
                // BackgroundTintAndShade does not work for non-theme colors.
                if (!StringUtil.HasChars(ThemeFill))
                    throw new InvalidOperationException("BackgroundTintAndShade cannot be applied to a non-theme color.");

                ArgumentUtil.CheckRangeInclusive(value, -1.0d, 1.0d, "BackgroundTintAndShade");

                ThemeFillTint = null;
                ThemeFillShade = null;
                // Note, Word stores inverted value (1 - tint) in the document.
                if (value > 0)
                    ThemeFillTint = FormatterPal.IntToStrX2((int)((1 - value) * 255));
                // Note, Word stores inverted value (1 + shade) in the document.
                if (value < 0)
                    ThemeFillShade = FormatterPal.IntToStrX2((int)((-1 - value) * -255));
            }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeColor
        {
            get { return mThemeColor; }
            set { mThemeColor = value; }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeShade
        {
            get { return mThemeShade; }
            set { mThemeShade = value; }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeTint
        {
            get { return mThemeTint; }
            set { mThemeTint = value; }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeFill
        {
            get { return mThemeFill; }
            set { mThemeFill = value; }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeFillShade
        {
            get { return mThemeFillShade; }
            set { mThemeFillShade = value; }
        }

        /// <summary>
        /// At the moment just plain unparsed value from DOCX.
        /// </summary>
        internal string ThemeFillTint
        {
            get { return mThemeFillTint; }
            set { mThemeFillTint = value; }
        }

        /// <summary>
        /// Returns true if this shading object provides a texture or background color.
        /// </summary>
        internal bool IsVisible
        {
            get
            {
                // WORDSNET-17402 Word does not render shading with "nil" pattern type, even if background color is specified.
                return (Texture != TextureIndex.TextureNil) &&
                    ((Texture != TextureIndex.TextureNone) || !BackgroundPatternColorInternal.IsEmpty);
            }
        }

        internal Shading Clone()
        {
            // Not expected to create copies of inherited borders because inherited borders
            // are essentially presentation objects only and created on demand.
            if (IsInherited)
                throw new InvalidOperationException("Cannot clone an inherited attribute.");
            return (Shading)MemberwiseClone();
        }

        /// <summary>
        /// Gets the border that we are inheriting from.
        /// </summary>
        private Shading Inherited
        {
            get { return (Shading)mParent.FetchInheritedShadingAttr(mKey); }
        }

        /// <summary>
        /// Only set for an inherited shading object.
        /// </summary>
        [CodePorting.Translator.Cs2Cpp.CppWeakPtr]
        private IShadingAttrSource mParent;
        /// <summary>
        /// The key used to retrieve the parent shading object we are inheriting from.
        /// Only used for an inherited shading.
        /// </summary>
        private int mKey;
        private TextureIndex mTexture;
        private DrColor mForegroundPatternColor;
        private DrColor mBackgroundPatternColor;

        private string mThemeColor;
        private string mThemeShade;
        private string mThemeTint;
        private string mThemeFill;
        private string mThemeFillShade;
        private string mThemeFillTint;
    }
}
