// Copyright (c) 2001-2026 Aspose Pty Ltd. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.IO;
using Aspose.JavaAttributes;

namespace Aspose.TestFx
{
    /// <summary>
    /// Implements diffing of images
    /// </summary>
    [JavaManual]
    [AndroidDelete]
    internal static class DiffClient
    {
        /// <summary>
        /// Default path to the server executable.
        /// You can override this using <see cref="ENVAR"/> environment variable.
        /// </summary>
        internal const string SERVER = "x:/awnet/aspose.foundation/tools/imageservices/bin/aspose.imagediff.exe";
        internal static readonly string PIPE = System.IO.Path.GetFileNameWithoutExtension(SERVER) + ".pipe";
        internal static readonly string MUTEX = System.IO.Path.GetFileNameWithoutExtension(SERVER) + ".mutex";
        internal static readonly string ENVAR = System.IO.Path.GetFileNameWithoutExtension(SERVER) + ".path";

        /// <summary>
        /// Binary label, the files are binary equal
        /// </summary>
        public const string BINARY = "binary";
        /// <summary>
        /// Pixel label, the files are binary different but have no pixel difference
        /// </summary>
        public const string PIXEL = "pixel";
        /// <summary>
        /// This label is not generated by diff, but can be assumed for uncategorized differences.
        /// It is used as a folder name where diffs are collected.
        /// </summary>
        public const string OTHER = "other";

        /// <summary>
        /// Returns True if <paramref name="label"/> matches any of the <paramref name="labels"/>
        /// comparing case insensitive.
        /// </summary>
        public static bool IsMatching(IEnumerable<string> labels, string label)
        {
            foreach (string l in labels)
                if (string.Equals(l, label, StringComparison.OrdinalIgnoreCase))
                    return true;
            return false;
        }

        /// <summary>
        /// This is where diff images are collected. It will have subfolders named after labels.
        /// </summary>
        public const string LABEL_FOLDER = "x:/awnet/testout/temp/labels/";

        /// <summary>
        /// Converts pair of images to difference image.
        /// </summary>
        /// <param name="outputFolder">A folder where to generate difference images</param>
        /// <param name="first">A first image</param>
        /// <param name="second">A second image</param>
        /// <param name="formats">Formats of difference images to generate. Can be 'bmp', 'png' or 'bmp,png'</param>
        /// <param name="computeLabels">True to compute extended labels.
        /// If False then only empty or <see cref="PIXEL"/> label can be received.
        /// Empty label means existing pixel difference does not look like a known label.
        /// If files are binary equal and <paramref name="compareBinary"/> is False then empty label is returned!
        /// </param>
        /// <param name="compareBinary">True to return <see cref="BINARY"/> label when files are binary equal.
        /// Normally this method is called when caller already knows that files are not binary equal.
        /// </param>
        /// <param name="matchRgba">Color used when pixels match</param>
        /// <param name="nonmatchRgba">Color used when pixels do not match</param>
        /// <returns>Difference label</returns>
        /// <remarks>
        /// Parameters <paramref name="matchRgba"/> and <paramref name="nonmatchRgba"/> may produce
        /// non-standard image. Specifically MS Paint does not recognize colors and will always show black and white.
        /// Transparency while present in the color palette is ignored by GDI+.
        ///
        /// Argb refers to Alpha, Red, Green, Blue value, represented as uint 0xAARRGGBB [memory BB GG RR AA]
        /// This is how WinForms Colors work.
        /// Rgba (Abgr) refers to Red, Green, Blue, ALpha value, represented as uint 0xAABBGGRR [memory RR GG BB AA]
        /// This is how Diff library works (the bitmap format)
        /// </remarks>
        public static Result[] Generate(string outputFolder, string first, string second,
            string formats, bool computeLabels, bool compareBinary, uint matchRgba = 0xffffffff, uint nonmatchRgba = 0xff)
        {
            if (string.IsNullOrEmpty(first))
                throw new ArgumentException("first");

            // the tool can live without output folder, but the caller needs to understand the effect
            // of temporary files left in bin folder of the application, not good
            // so lets require output folder explicitly here, even when client does not want diff file itself
            if (string.IsNullOrEmpty(outputFolder))
                throw new ArgumentException("outputFolder");

            string output = ClientUtil.PostServerJobGetResults(MUTEX, PIPE, SERVER, ENVAR, new String[] {
                    !string.IsNullOrEmpty(outputFolder) ? "-o" + outputFolder : null,
                    computeLabels ? "-l" : null,
                    compareBinary ? "-b" : null,
                    "-f" + formats,
                    "-p" + matchRgba + "," + nonmatchRgba,
                    first,
                    second});

            string[] lines = output.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            Result[] results = new Result[lines.Length];
            for (int i = 0; i < results.Length; i++)
            {
                string line = lines[i];
                Debug.Assert(!string.IsNullOrEmpty(line));
                int index = line.LastIndexOf(':');
                // the format is 'name:label', name cannot be empty
                Debug.Assert(index > 0);
                results[i].Name = line.Substring(0, index);
                results[i].Label = line.Substring(index + 1);
            }

            return results;
        }

        /// <summary>
        /// Moves <see cref="_DiffPath"/> to label path
        /// </summary>
        public static string RelocateDiffFile(string sourcePath, string label)
        {
            if (sourcePath != null && !string.IsNullOrEmpty(label))
            {
                try
                {
                    string targetFolder = Path.Combine(LABEL_FOLDER, label);
                    Directory.CreateDirectory(targetFolder);
                    var targetPath = Path.Combine(targetFolder, Path.GetFileName(sourcePath));
                    File.Delete(targetPath);
                    File.Move(sourcePath, targetPath);
                    return targetPath;
                }
                catch
                {
                    Debug.WriteLine("failed to move diff file '" + sourcePath + "'");
                }
            }
            return null;
        }

        /// <summary>
        /// Returns full path to the diff image file when diff tool is used to compute diff of
        /// <paramref name="file1"/> and <paramref name="file2"/> and place it in to <paramref name="tempFolder"/>
        /// </summary>
        public static string GetDiffImagePath(string tempFolder, string file1, string file2)
        {
            return Path.Combine(tempFolder, Path.GetFileNameWithoutExtension(file1) + "-vs-" + Path.GetFileNameWithoutExtension(file2) + ".bmp");
        }

        /// <summary>
        /// Represents a sigle result of <see cref="Generate(string, string, string, string, bool, bool)"/>
        /// </summary>
        public struct Result
        {
            /// <summary>
            /// The diff image file name
            /// </summary>
            public string Name;
            /// <summary>
            /// The diff label
            /// </summary>
            public string Label;
        }
    }
}
